### ISSUE TITLE
Support Vue-2.3.x

### ISSUE THREAD

**Issue by clarkdo** [vuejs/vue-class-component#101]
Do we have any plan to support Vue-2.3.x ?

**Comment by ktsn** [comment]
It already supports Vue 2.3.
If you are using typescript, make sure to enable `--allowSyntheticDefaultImports `

**Comment by clarkdo** [comment]
@ktsn 
When I use @Component, vue will throw below exception, after changed back to normal component, it works fine.

TypeError: Cannot read property '_init' of undefined
    at VueComponent (/Users/clark/Projects/github/hare/node_modules/vue/dist/vue.runtime.common.js:4167:11)

**Comment by ktsn** [comment]
If that is the case, please provide reproduction by github repo, jsfiddle or so on.

**Comment by clarkdo** [comment]
@ktsn thanks for you patient reply, I haven taken a deeper look at my issue, it should be caused by another dependency, sorry for the bother, thanks again.
