### ISSUE TITLE
Watching a property and call a method

### ISSUE THREAD

**Issue by vishr** [vuejs/vue-class-component#103]
How can watch a property and invoke a function? I tried something like below but the reference to this is not the class object.

```js
@Component({
    components: {
      Multiselect
    },
    watch: {
      host: () => {
        // this.analytics()
      },
      interval: () => {
        // this.analytics()
      }
    }
  })
```

**Comment by HerringtonDarkholme** [comment]
Changing arrow function to plain function is enough.

http://exploringjs.com/es6/ch_arrow-functions.html

**Comment by vishr** [comment]
Thanks for your prompt response.

**Comment by wsajjadh** [comment]
> Changing arrow function to plain function is enough.
> 
> ```js
> @Component({
>     components: {
>       Multiselect
>     },
>     watch: {
>       host: function () {
>         this.analytics()
>       },
>       interval: function () {
>         this.analytics()
>       }
>     }
>   })
> ```
> 
> http://exploringjs.com/es6/ch_arrow-functions.html

This works for me. Thank you bro
