### ISSUE TITLE
Reentrancy breaks property decorators

### ISSUE THREAD

**Issue by SLaks** [vuejs/vue-class-component#104]
When using the pattern of

```js
@Component({
  components: { foo: require('./foo.vue') }
})
class ...
```

`foo.vue`'s class will be created during the initialization of its calling class.
This will end up applying all property decorators (eg, `@Watch` from https://github.com/kaorun343/vue-property-decorator) to `Foo` instead of the calling class.

To fix this, you need to change [`$decoratorQueue`](https://github.com/vuejs/vue-class-component/blob/cb8d9de02470f05b2bb9b3d59c9973f1b5d760ed/src/component.ts#L23) to a stack so that you can differentiate between properties applied to different reentrant class definitions.

**Comment by ktsn** [comment]
Could you explain more details what a problem you encounters?
I'm afraid I can't understand why we need to change `$decoratorQueue` to a stack.
I think it should be a queue to make consistent with the order of applying the native decorators.

**Comment by SLaks** [comment]
It looks like the problem only happens with TypeScript's decorator compilation, not Babel.

Repro: https://jsfiddle.net/SLaks/stuf0kex/3/

Typing in the first textbox does nothing (doesn't display a message from the `watch` handler).
Commenting out `components: { Child: require('child') }` (or changing the language to Babel) makes it work.

**Comment by ktsn** [comment]
Thanks for the repro. It seems like we need to assign `$decoratorQueue` for each class constructor to avoid to apply property decorators to wrong components.
