### ISSUE TITLE
Class accessors(get/set) not functioning as computed properties

### ISSUE THREAD

**Issue by whotakesmyid** [vuejs/vue-class-component#105]
Hi all, I have this very simple piece of code where I'm trying to use class accessors as computed property. 

```
export class LoginComponent extends Vue {
   private _userIdState: string = '';
   get userIdState(): string {
      return this._userIdState;
   }
   set userIdState(state: string) {
      this._userIdState = state;
   }
   login() { 
      this.userIdState = 'danger';
   }
}
```

Once the login function is triggered, I could see in the console that the private element did change to 'danger', but in the vue-devtool, neither the element or the computed property/get returns 'danger' (returns undefined if you haven't guessed). I've also tried $nextTick thinking it was an async problem. 

Not sure if I missed something here, or simply shouldn't have assumed ts class set is equivalent to set in computed property.

Thanks,

**Comment by kaorun343** [comment]
@whotakesmyid 

Hi. 😃 

Because the property which name starts with `_` will not be observed. 
`_userIdState` is defined as private in TS, so there's no worry that the property is accessed from outside. I recommend you to remove `_` from it.

**Comment by whotakesmyid** [comment]
Hi, @kaorun343 
Thanks for such prompt response. I'm away from my work computer so I can't try your solution at the moment, but would you mind telling me if this not-observing-`_variable` a vue rule or a ts rule, and if it's not too much trouble, would you mind sharing the link to this specific naming guide line. 

Thanks,

**Comment by kaorun343** [comment]
@whotakesmyid 

Could you read this section?
https://vuejs.org/v2/api/#data

**Comment by whotakesmyid** [comment]
Thank you. Closing ticket
