### ISSUE TITLE
Default component name with keep-alive

### ISSUE THREAD

**Issue by vishr** [vuejs/vue-class-component#106]
I am relying on the default component name (class name) and using it as a `include` property for keep-alive in router-view. Something like https://jsfiddle.net/Linusborg/L613xva0/4. What I observed is, for local development `npm run dev` works fine but when I build it for production `npm run build` it doesn't. For your reference, I use vue-cli.

**Comment by ktsn** [comment]
Can you provide a minimal reproduction by github repository?

**Comment by vishr** [comment]
Here is the working repo https://github.com/vishr/vue-test. You will see for local setup it works fine and mounted is not called going back and forth but for production build it does alert mounted for the same.

**Comment by ktsn** [comment]
Thanks for providing the repo. We'll look into it.

**Comment by ktsn** [comment]
This is because component classes are mangled by the minifier. I think we cannot do anything for you about this because it is caused outside of Vue/vue-class-component.
The workaround is using the `name` option as you described.
