### ISSUE TITLE
how can i use vuex mapState, mapGetter and  ssr asyncData in vue component?

### ISSUE THREAD

**Issue by chen6516** [vuejs/vue-class-component#107]
Hi guys, there have a detail description for this, i need your help , 3q!

**Comment by HerringtonDarkholme** [comment]
You can of course go to the new [Vue Land](https://vue-land.js.org/) for help!

GitHub Issue is mainly for bug reporting and feature request.

**Comment by amritk** [comment]
@chen6516 found a little workaround. You can add asyncData as a method on your class component, then in entry-server, change this:
```
Promise.all(matchedComponents.map(Component => {
    if (Component.asyncData) {
        return Component.asyncData({
            store,
            route: router.currentRoute
        })
    }
})).then(() => {
```
to this:
```
Promise.all(matchedComponents.map(Component => {
    if (Component.options.methods.asyncData) {
        return Component.options.methods.asyncData({
            store,
            route: router.currentRoute
        })
    }
})).then(() => {
```

**Comment by romandragan** [comment]
@amritk 

Just `Component.options.asyncData`

**Comment by amritk** [comment]
@romandragan that doesn't work for me for some reason

**Comment by romandragan** [comment]
@amritk, what Vue version are you using?

**Comment by amritk** [comment]
@romandragan If I try `Component.options.asyncData(...)` I get `TypeError: options.asyncData is not a function` however it works fine when I add methods in there.
Vue: 2.5.9
Vue-class-component: 6.1.1
Vue-property-decorator: 6.0.0
In my component I have:
```
    asyncData ({ store, route }: { store: Store<{}>, route: Route }) {
        return store.dispatch('explore/getPlace', route.params)
    }

    data () {
        return {
            tags: [] as string[],
            toggled: [] as string[]
        }
    }
```

**Comment by romandragan** [comment]
@amritk 

I also have registered `vue-class-component`'s hook for `asyncData`. Maybe that's the reason.

**Comment by amritk** [comment]
@romandragan yea that's probably it
