### ISSUE TITLE
vue-class-component how to use vue-router lazyload js file when the routes change?

### ISSUE THREAD

**Issue by theMonkeyMan** [vuejs/vue-class-component#108]
First of all.
  i'm sorry,i couldn't upload example to 'https://jsfiddle.net/ktsn/nm55jnjk/' or github,because the project so big and my PM not allowed.i can only write some code.
  when i coding the vue-router routes config,i found i can't use lazyload feature.
  ##  can't work example:
  ```
  //main.ts
  import * as Vue from 'vue';
  import App from './App.vue';
  import router from './router';
  new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
  render: h => h(App, {
    props: {  }
  })
});

router.beforeEach((to, from, next) => {
  if (to.meta.title) {
    document.title = to.meta.title
  }
  next()
})

  //App.vue
  <template>
  <div id="app">
    <router-view></router-view>
  </div>
  </template>


  <script lang="ts">
  import * as Vue from 'vue';
  import Component from 'vue-class-component';
  @Component({
    props:{
  
    }
  })
export default class App extends Vue {
  name:string='app';

}
</script>

  //components/Login.vue
  import * as Vue from 'vue';
  import Component from 'vue-class-component';
  @Component({
  })
  export default class Login extends Vue {...}
  

  //router/index.ts
  export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Login',
      component: (resolve:any) => {
        require(['../components/Login.vue'], resolve)
      },
      meta: {
        title: 'user login'
      }
    }]
  });

```
 if the code like above. broswer will throw Error 
```
'[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <App> at ~/frontend-pc-merchant/src/App.vue
         <Root>'
```

 ## can work example:

  ```

  //router/index.ts
  import Login from '../components/Login.vue';
  export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Login',
      component:Login,
      meta: {
        title: 'user login'
      }
    }]
  });
```

 i couldn't know how to config it, have any other solution?
 thanks , and happy weekend.

**Comment by ktsn** [comment]
Could you boil down the code to only include that the thing causes the problem and provide minimal/self-contained reproduction?
We cannot work for you without a reproduction that can run in our machines...

**Comment by theMonkeyMan** [comment]
thank you for your answer. i'm already found the problem.
let's analyze it, at the beginning i suspect that the problem is caused by 'vue-class-component', but this view was soon denied. and then , i open the broswer development tools look at the 'Network', when i change the broswer route i saw the splited code file is loaded. so i think the reason is webpack packing different ways. and then, i compared the webpack before using the 'vue-class-component' and after the configuration. i found the 'vue-loader options' have one extra properties 'esModule', so i go to the www.github.com search vue-loader and look docs, at the last, i found this: https://github.com/vuejs/vue-loader/blob/master/docs/en/options.md#esmodule . so i comment properties 'esModule' .
  for your requirement,i create the example repositories: https://github.com/theMonkeyMan/vue-typescript.

**Comment by ktsn** [comment]
Yes, if you enable `esModule` option of vue-loader, components are exported as default export that compliant with the ESModule. And as AMD style import will provide different format of imported object, you need to refer `default` property of it by yourself. (or disable `esModule` option)

```js
const A = resolve => require(['../components/A.vue'], A => resolve(A.default))
```

**Comment by theMonkeyMan** [comment]
Yes, I am doing it now. My English is not good, Thank you so patiently answered. good luck.
