### ISSUE TITLE
[Question] How create the component with data

### ISSUE THREAD

**Issue by JoniJnm** [vuejs/vue-class-component#112]
Hi,

I tried to create component with data, but I don't know how to do it.

For example, with this component:

```html
<script lang="ts">
    import Vue from 'vue'
    import Component from "vue-class-component";

    @Component({

    })
    export default class TagsComponent extends Vue {
        tags: string[] = [];
    }
</script>
```

Now, to pass data I'm doing the following:

```ts
let vm = new Vue({
	el: '.tags',
	render: h => h(TagsComponent)
});

vm.$children[0].tags = ['tag1', 'tag2'];
```

But I want to pass the data in the constructor, but it doesn't work. I tried:

```ts
let vm = new Vue({
	el: '.tags',+
	data: {
		tags: ['tag1', 'tag2']
	},
	render: h => h(TagsComponent)
});

let vm = new Vue({
	el: '.tags',
	render: h => h(TagsComponent, {
		data: {
			tags: ['tag1', 'tag2']
		}
	})
});
```

How should I pass the data? Thanks

**Comment by ktsn** [comment]
Just use `props`
https://vuejs.org/v2/guide/components.html#Props

**Comment by JoniJnm** [comment]
Thanks for the response.

I don't want to pass the data in the element

```html
<div class="tags" v-bind:tags="['tag1', 'tag2']">
```

I wan't to pass it in the constructor. Is it possible?

**Comment by ktsn** [comment]
Well, I don't understand what you want to do.
If you want to pass some data from parent component to children, `props` is actually the thing that Vue provides. There are no other ways because you can do that by using `props`.

> I wan't to pass it in the constructor

No, you can't pass data to constructor because components are instantiated inside of Vue. Also, you shouldn't use `constructor` if you use vue-class-component because it's doing some hacks around it to provide intuitive API like reactive class properties.

**Comment by kaorun343** [comment]
@JoniJnm 

Hi. How about writing like this below?

```ts
@Component({
  props: ['tags']
})
export default class TagsComponent extends Vue {
  tags: string[]
}
```

```js
let vm = new Vue({
  el: '.tags',
  data: {
    tags: ['tag1', 'tag2']
  },
  render(h) {
    return h(TagsComponent, {
       props: { tags: this.tags } 
    })
  }
})
```

**Comment by JoniJnm** [comment]
There is something called 'propsData': https://vuejs.org/v2/api/#propsData

But I don't know why this doesn't work with vue-class-component

vue file:

```html
<template>
	<div>
		{{ propOne }}
	</div>
</template>

<script lang="ts">
    import Vue from 'vue'
    import Component from "vue-class-component";

    @Component({
        props: {
            propOne: {
                type: String,
                default: 'default value'
            }
        }
    })
    export default class MyComponent extends Vue {
        propOne;
    }
</script>
```

a ts file:

```ts
let vm = new Vue({
	el: '.my-comp',
	propData: {
		propOne: 'a real value'
	},
	render: h => h(MyComponent)
});
```

It always print 'default value'.

I'm doing something wrong?

**Comment by JoniJnm** [comment]
I will try @kaorun343 response

**Comment by JoniJnm** [comment]
With the example of @kaorun343  `tags` is empty :(

**Comment by kaorun343** [comment]
In your case, `propData` is not needed. We use `propData` to pass data to the properties that are defined as `prop` when creating a new vm from a user-defined Component. This is very useful when testing the Component which contains `props`.

For instance,

```js
const TagsComponent = Vue.extend({
  props: ['tags']
})

const vm = new TagsComponent({
  propData: {
    tags: ['tag1', 'tag2']
  }
})
```

**Comment by kaorun343** [comment]
In addition, this issue is not substantially related to `vue-class-component`. It might be better to ask at Vue's official forum or Vue's gitter channel.

**Comment by JoniJnm** [comment]
I asked here because withouth vue-class-component I don't use 'render' function.

I thought you could tell me easily I way to pass the data (props) in the constructor (new Vue() with render).

**Comment by kaorun343** [comment]
Could you tell me why you'd like to use a constructor?
There's no way to use `new TagsComponent` and pass data to its consturctor inside `render` function with (or without) `vue-class-componet`.

According to this document, there' no `new` keyword inside `render` function. https://vuejs.org/v2/guide/render-function.html#createElement-Arguments
So as to pass data, the document represents a code very similar to the code I showed above.

**Comment by JoniJnm** [comment]
When I say "constructor" I refer to:

```ts
let vm = new Vue({
	el: '.my-comp',
	render: h => h(MyComponent)
});
```

and not:

```ts
let comp = new MyComponent()
```

I only want this: https://forum.vuejs.org/t/how-to-initialize-props-of-component-passed-to-vue-constructor/6927/3 working with vue-class-component (that means, working with `render` function)
