### ISSUE TITLE
How to create functional component in @Component?

### ISSUE THREAD

**Issue by lijialing888** [vuejs/vue-class-component#120]
Hi guys,

How to create functional component in @Component?

```typescript
import * as Vue from 'vue'
import Component  from 'vue-class-component'

@Component({
    props: ["a"]
    functional: true
})
export default class XXX extends Vue {

}
```

It prompts error in Visual Studio Code: 
```
[ts] Argument of type '{ functional: boolean; }' is not assignable to parameter of type 'VueClass'.
  Object literal may only specify known properties, and 'functional' does not exist in type 'VueClass'.
```

**Comment by ktsn** [comment]
We need to declare an additional type for `@Component` decorator. Thanks for reporting this.

**Comment by kaorun343** [comment]
I just wondered the benefit of using `@Component` decorator for functional components because `this` is `undefined` in a functional component.

**Comment by ktsn** [comment]
Oh, indeed.

@lijialing888 Why do you want to use `@Component` for function components?

**Comment by ktsn** [comment]
Closing since there would not be benefit to use class style syntax for a function component as @kaorun343 described.

**Comment by marcosmoura** [comment]
@ktsn 
Let's suppose that I don't want to render any template or I need an empty `render` function, but still have the ability to use the decorator while creating functional components. Look at this example:

``` ts
import { Component, Vue } from 'vue-property-decorator'

@Component({
  functional: true,
  props: {
    theme: {
      type: String,
      default: 'default'
    }
  }
})
export default class Stylesheets extends Vue {
  // A bunch of Vue lifecycle methods here and there...
  render () {
    return null
  }
}
```

The `functional: true` will raise an error saying that the functional property is not assignable of type `VueClass<Vue>`.

In the utils.ts file, there is the following [line](https://github.com/vuejs/vue-class-component/blob/48059b87225efde73b99606be87ce4afa94d5780/src/util.ts#L19): 
``` ts
export function createDecorator (factory: (options: ComponentOptions<Vue>, key: string, index: number) => void): VueDecorator {
```

The type is ComponentOptions (that do not have `functional`). By changing the line including the functional component type, the decorator works just fine and will inject the `functional: true`.
``` ts
export function createDecorator (factory: (options: ComponentOptions<Vue> | FunctionalComponentOptions<Vue>, key: string, index: number) => void): VueDecorator {
```

Does it make sense to change it to something like that? There is some side effects that this could raise?

Or maybe a safer `@FunctionalComponent` with the same goods as `@Component`...

If so, a PR on this matter is welcome?

**Comment by DrSensor** [comment]
I think adding the additional decorator `@FunctionalComponent` is a good thing and serve the purpose of supporting [template tag for functional component](https://vuejs.org/v2/guide/render-function.html#Functional-Components)
```html
<template functional>
</template>
```

**Comment by netstuff** [comment]
Does anybody solve this problem? I trying made recursive scoped slots for tree-component and I think that I have to access native render method for injecting `$scopedSlots` property next to children components. What do you think about it, guys?

**Comment by algil** [comment]
Any solution for this?

**Comment by ktsn** [comment]
Just use `Vue.extend`...

```js
import Vue from 'vue'

export default Vue.extend({
  functional: true,
  render(h, ctx) {
    // ...
  }
})
```

As it's already pointed out the former of this issue, using class style syntax for functional component does not have benefit since functional component does not have its instance. It won't included in this lib since class style functional component does not follows standard class semantics (not have instance, `this` is undefined ...).
