### ISSUE TITLE
Inheritens

### ISSUE THREAD

**Issue by CodeLookBook** [vuejs/vue-class-component#121]
Can I do something like this with "vue-class-component"?

```
//file #1
class Inherit extend Vue {
      //.... code
} 

//file #2
@Component
class Child extends Inherit {
      //.... code
}
```
I tried to implement this thoughts, but that doesn't work. When I treid to use getters/setters from the "Inherit"-ed class in the \<template\> of my "Child" component, I got an errors. May be I do it in a wrong way?

**Comment by ktsn** [comment]
Yes, you can.
See: https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L168

**Comment by CodeLookBook** [comment]
@ktsn 

One more question. When I need inheritance, Must I duplicate reactive properties of the class in a data(){ return{.//..}} , like this:

```
  @Component
  class Base extends Vue {
      a: number
      data (): any {
          return { a: 1 }
      }
  }
```

Thank you, for your help.

**Comment by CodeLookBook** [comment]
@ktsn 

Right now I have a class that needs to be inherited:

```
@Component
class VueHTMLBlock extends Vue{

    protected _componentName: string;

    /**
     * Set HTML DOM HTMLElement height.
     * @param newHeight
     */
    public set height(newHeight: ISizePx | null){

        if(this.$el && newHeight !== null) {
            
            const rectangle: ClientRect = this.$el.getBoundingClientRect();

            this.$el.style.height = newHeight.value + newHeight.measure;

            const newValue: ISizePx = newHeight;
            const oldValue: ISizePx = {
                value: Math.abs(rectangle.bottom - rectangle.top),
                measure: 'px'
            };
            const event: ISizeEvent<ISizePx> = {
                newValue: newValue,
                oldValue: oldValue,
                isBigger: newValue > oldValue,
                isSmaller: newValue < oldValue,
                isUnchanged: newValue === oldValue,
                target: this,
            };

            this.$root.$emit(this._componentName + 'HeightChanged', event);
        }
    }

    /**
     * Get HTML DOM Element height.
     * @return {{height: number, unitMeasureName: string}} - Height is
     * calculated based on bounding client rectangle.
     */
    public get height(): ISizePx | null {

        if(this.$el) {
            const rectangle: ClientRect = this.$el.getBoundingClientRect();
            return {
                value: Math.abs(rectangle.bottom - rectangle.top),
                measure: 'px'
            };
        }
        return null;
    }
}
```
and the class that inherits VueHTMLBlock 

``` 
   @Component({ })
    class TopNavbarSlot extends VueHTMLBlock {
         //empty
    }
```


At this moment, when I try to input my inherited getter to TopNavbarSlot component template:

```
<template lang="pug">

    .TOP-NAVBAR-SLOT
        | {{ height.value }}
        slot

</template>
```

I get errors in browser:

> [Vue warn]: Error in render function: "TypeError: Cannot read property 'value' of undefined"
> 
> found in
> 
> ---> <TopNavbarSlot> at C:\xampp\htdocs\WebSite_WhiteLab\resources\assets\js\components\app\layout\top-navbar-slot.vue
>        <MainContentSlot> at C:\xampp\htdocs\WebSite_WhiteLab\resources\assets\js\components\app\layout\main-content-slot.vue
>          <Layout> at C:\xampp\htdocs\WebSite_WhiteLab\resources\assets\js\components\app\layout.vue
>            <AppComponent> at C:\xampp\htdocs\WebSite_WhiteLab\resources\assets\js\components\app\app.vue
>              <Root>


> TypeError: Cannot read property 'value' of undefined
>     at Proxy.render (app.js:sourcemap:16494)
>     at VueComponent.Vue._render (app.js:sourcemap:4684)
>     at VueComponent.updateComponent (app.js:sourcemap:3220)
>     at Watcher.get (app.js:sourcemap:3559)
>     at new Watcher (app.js:sourcemap:3542)
>     at mountComponent (app.js:sourcemap:3224)
>     at VueComponent.Vue$3.$mount (app.js:sourcemap:8352)
>     at VueComponent.Vue$3.$mount (app.js:sourcemap:10451)
>     at init (app.js:sourcemap:4139)
>     at createComponent (app.js:sourcemap:5682)

**Comment by ktsn** [comment]
We encourage you to ask questions in our [forum](https://forum.vuejs.org/) or [chat room](https://vue-land.js.org/) since the issue list is reserved for bug reports and feature requests. Thanks!
