### ISSUE TITLE
'$watchAsObservable' does't exit when I use this with vue-rx & rx

### ISSUE THREAD

**Issue by vincween** [vuejs/vue-class-component#124]
Version: 
Node.js: 8.0.0
Vue: 2.3.4
Typescript: 2.4.1
vue-rx: 3.2.0
rx: 5.4.2

Code will work if I write like this:
![image](https://user-images.githubusercontent.com/5889582/28146309-5890e468-67ab-11e7-9cb7-a6d77d67767a.png)

Code won't work if i use vue-class-component 
![image](https://user-images.githubusercontent.com/5889582/28146363-d04b1bd6-67ab-11e7-88ce-378ec311e7e5.png)

Is this the right way to use these together?

**Comment by ktsn** [comment]
This is because you do not have typescript declaration of vue-rx in your project.
Declare it by yourself or request it for vue-rx repository.

**Comment by vincween** [comment]
Thanks for your replying, I am a little confused, if it needs a typescript declaration why it can work in the first way? the first way also use vue-rx with typescript.
Anyway , thanks for the great work, I will dig in some more to find out.

**Comment by ktsn** [comment]
> why it can work in the first way? 

Since `this` type of the first code is `any` which can have any properties on it.
