### ISSUE TITLE
Add a build that doesn't use any of the module formats

### ISSUE THREAD

**Issue by vhakulinen** [vuejs/vue-class-component#127]
Can you create build that works when you load the javascript file with the good old `<script>` tag. Currently, the `vue-class-component.common.js` doesn't work because `process` variable doesn't exists and with `vue-class-component.js` you'll have to call `VueClassComponent.default` instead of `Component`.

Also, decorations wouldn't be bad. I tried quickly, and just by changing `tsc -p .` to `tsc -p . -d` in `package.json` I was able to use the declaration "correctly" just by wrapping the `Component` stuff from resulting index file under `declare global`scope.

**Comment by ktsn** [comment]
Just assigning `VueClassComponent.default` to `Component` works for that case.
Choosing default export format in umd build is intentional because there are needs to import it from global script via ESModule syntax. Also I'm not a fan of providing different export interfaces in one library.
