### ISSUE TITLE
Can't access some methods defined by plugins. (Using Typescript)

### ISSUE THREAD

**Issue by gnumarcelo** [vuejs/vue-class-component#128]
Hi, as I'm a newbie in Vue.js I'm not sure this is a bug or a misuse of my part but I can't use some methods defined in global vue instance by some plugins (`vue-notification` in this case) inside of my components. Am I missing something?

boot.ts
![image](https://user-images.githubusercontent.com/6064/28473051-99206516-6e19-11e7-9e17-36770628df26.png)

FleetIndex.ts
![image](https://user-images.githubusercontent.com/6064/28473014-7167f016-6e19-11e7-916b-abaf3e5afd14.png)

Thanks!

**Comment by ktsn** [comment]
Because vue-notification does not seem to provide type declaration. Please request it for vue-notification or declare it by yourself.

You may want to see this example to understand how to augment vue typings:
https://github.com/vuejs/vue/blob/dev/types/test/augmentation-test.ts

**Comment by gnumarcelo** [comment]
@ktsn Thanks for your help!
Just for the record, I ended up doing this:

``
declare module 'vue/types/vue' {
   export interface Vue   {
       $notify: Notifications;
   }
}
``

https://stackoverflow.com/questions/43142304/how-to-augment-the-vue-class-and-keep-typescript-definition-in-sync/43232151%2343232151

**Comment by euvl** [comment]
Hey @ktsn,

I am a developer of the plugin. 
How would I provide type declaration? 
I do not have experience using ts so I am not sure what am I can do it.

Thanks

**Comment by ktsn** [comment]
@euvl I just made a PR for that to docs repository 🙂  https://github.com/vuejs/vuejs.org/pull/1042
