### ISSUE TITLE
Component "this" undefiend in component decorator

### ISSUE THREAD

**Issue by rezenvar** [vuejs/vue-class-component#129]
I tried to use vuex helper mapState in component decorator, but module pathname is dynamic and depends on values passed to prop. So i just: 
`
// ....imports
@Component({
     props: ['moduleId'],
     computed: {
          ...mapState('modulepathname/' + this.moduleId, [
                'some',
                'fields'
          ])
     }
})
export default class .....
`
file ext: .vue,
lang: js
 
Is there way to get around this?

**Comment by ktsn** [comment]
You can't because you are refering `this` before an instance is created.
Just use `this.$store` if you want to dynamically access some store assets.
