### ISSUE TITLE
Special properties (for 3rd party plugins) [Question/Feature-request]

### ISSUE THREAD

**Issue by mcongy** [vuejs/vue-class-component#130]
Hello,

I'm trying to use this with vue-apollo https://github.com/Akryum/vue-apollo
Configuring apollo is done through special 'apollo' property on the component instance.
Example: https://github.com/Akryum/vue-apollo-example/blob/master/src/App.vue

Problem is, If I add this special 'apollo' property as normal class-property, vue-class-component transforms it into a vue 'data' property.

Is there a way to tell vue-class-component to treat some properties as 'special'? Something similar to registering router hooks?

Thanks!

**Comment by ktsn** [comment]
You can provide it into decorator's parameter.

```js
@Component({
  apollo: {
    // ...
  }
})
export default class extends Vue {
}
```

**Comment by mcongy** [comment]
Thanks!

Please consider adding it to the docs (if it's not already in and I just couldn't find it).

**Comment by ktsn** [comment]
It actually is in docs. https://github.com/vuejs/vue-class-component#usage

> For all other options, pass them to the decorator function

**Comment by romandragan** [comment]
@ktsn @mcongy 

What if I need to access `this` variable inside decorator's `apollo` parameter?

**Comment by HerringtonDarkholme** [comment]
Please don't ask question about TypeScript in this repo.

You can use https://gitter.im/Microsoft/TypeScript or https://vue-land.js.org/.
