### ISSUE TITLE
Add linting to example.

### ISSUE THREAD

**Issue by pulekies** [vuejs/vue-class-component#133]
Is it possible to add linting to the example? It was really helpful, but I'm running into issues setting up linting for single file components.

**Comment by HerringtonDarkholme** [comment]
Hi, you can try https://github.com/vuejs/eslint-plugin-vue.

ESlint now support SFC and TypeScript.

**Comment by ktsn** [comment]
I think we should not include linting setup in the example in this repo since it's not related with vue-class-component.
