### ISSUE TITLE
Can you add a decorator like @NoXXX and @NotXXX?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue-class-component#140]
能不能加上像@NoXXX,@NotXXX的装饰器禁止转为vue类属性或方法?
Can you add a decorator like @NoXXX and @NotXXX to a Vue class property or method?

**Comment by HerringtonDarkholme** [comment]
Hi, please see https://github.com/vuejs/vue-class-component/issues/96 for more information.

**Comment by ktsn** [comment]
Since current decorator implementations are not standardized yet (babel/ts do different behavior in some cases), I hesitate to include them in vue-class-component. Let's wait until transpilers implement the standard decorator and revisit after that.

**Comment by ktsn** [comment]
Let's integrate this with #96 to track.
