### ISSUE TITLE
How can i add vue-class-component to vue-cli?

### ISSUE THREAD

**Issue by Danieler** [vuejs/vue-class-component#141]
I would like to know what steps i have to do for add the vue-class-component to a vue-cli project
i have to include something in webpack conf??

**Comment by HerringtonDarkholme** [comment]
https://github.com/ducksoupdev/vue-webpack-typescript
https://vue-land.js.org/
https://stackoverflow.com/
http://lmgtfy.com/?q=vue+cli+typescript

**Comment by ktsn** [comment]
Please use [our forum](https://forum.vuejs.org/) or [chat room](https://vue-land.js.org/) to ask your question. Issue tracker is exclusively reserved for bug reports or feature request. Thanks!
