### ISSUE TITLE
Typing confusion

### ISSUE THREAD

**Issue by JVMartin** [vuejs/vue-class-component#143]
Hi all, thanks in advance for any guidance. I'm new to TypeScript.

![screenshot from 2017-09-06 17-07-14](https://user-images.githubusercontent.com/4450814/30139953-f0658e74-9325-11e7-830e-28eeeac28f86.png)

The above error should not exist, because `this.$refs.<name>` can be an instance of `Vue` or of `Element`.

`Element` extends `Node`, and `Node` does indeed have `appendChild<T extends Node>(newChild: T): T;` defined in its TypeScript Declaration File.

You can see that the error appears to be generated because TS is incorrectly assuming this is an instance of `Vue` and not an instance of `Element` - why is this? Shouldn't it see that it might be an `Element` and not give an error?

I'm pretty confident that my environment is set up correctly, I have all node type files loaded.

Thanks again for your guidance. Despite TS complaining, this code does compile and run just fine. The complaint is annoying though.

**Comment by JVMartin** [comment]
Wow... I literally have not changed anything, and now instead of assuming it's a `Vue` instance, it's assuming it's an array of `Element` instances:

![image](https://user-images.githubusercontent.com/4450814/30140281-4beef008-9328-11e7-94ab-12ab741c725a.png)

Does anyone have any ideas?

**Comment by kaorun343** [comment]
@JVMartin 

Hi.

You can do like this below.

```typescript
@Component
class Game extends Vue {
  // please add these codes into yours
  $refs: {
    canvases: HTMLElement
  }

  mounted () {
    this.$refs.canvases.appendChild(gameScreen.getView())
  }
}
```

**Comment by ktsn** [comment]
Vue's typings include all possible type as the union type.
You should manually annotate your `$ref` with expected type as @kaorun343 suggested.

**Comment by JVMartin** [comment]
Awesome - thank you @kaorun343 and @ktsn for your help!

**Comment by ffxsam** [comment]
This no longer works today (with the latest version of Vue & vue-cli 3). @kaorun343 @ktsn Any ideas?

**Comment by kaorun343** [comment]
```typescript
@Component
class Game extends Vue {
  // please add these codes into yours
  $refs!: { // <- "!" is needed
    canvases: HTMLElement
  }

  mounted () {
    this.$refs.canvases.appendChild(gameScreen.getView())
  }
}
```

**Comment by ffxsam** [comment]
@kaorun343 Wow! You rock! Thank you so much. I would've never figured this out. I'm not familiar with the `!` - what's that all about?

**Comment by wonderful-panda** [comment]
documentation about `!` is [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization)

> is it possible to define ref types in standard SFC (non-class) format?

```typescript
import Vue, { VueConstructor } from "vue";

export default (Vue as VueConstructor<Vue & { $refs: { canvases: HTMLElement } }>).extend({
  // ...
})
```

**Comment by ffxsam** [comment]
@wonderful-panda Awesome! The only thing I'm not able to do with SFCs is use a component as a type. E.g.:

```ts
import DataTable from '../components/shared/DataTable.vue'; // exports Vue.extend()

export default (Vue as VueConstructor<
  Vue & { $refs: { dataTable: DataTable } }
>).extend({
```

However, if I switch to class-based components, it works great:

```ts
import DataTable from '../components/shared/DataTable.vue'; // export class

@Component
export default class MyComponent extends Vue {
  $refs!: {
    dataTable: DataTable;
  }
```

**Comment by wonderful-panda** [comment]
@ffxsam If you use TypeScript 2.8 or later, try

```typescript
$refs!: {
  dataTable: InstanceType<typeof DataTable>;
}
```

**Comment by ffxsam** [comment]
@wonderful-panda Ugh, I didn't know about that because it's not in the TypeScript documentation. Thanks, I'll try it tomorrow.

**Comment by ffxsam** [comment]
@wonderful-panda You are indeed a wonderful panda. :grin: Thank you!
