### ISSUE TITLE
Local registered component is not working...

### ISSUE THREAD

**Issue by karateboy** [vuejs/vue-class-component#145]
I am new to vue-class-component. I have a global component App and a local registered component 
Menu.
```
//App.vue
<template>
<menu-view></menu-view>
</template>
<script lang="ts>
import Menu from "./components/Menu.vue"
@Component
export default class App extends Vue {
    name: 'app'
    components = {
        menuView : new Menu()
    }
}
<script>
//Menu.vue
@Component
export default class Menu extends Vue {}

```
The global App component work correct. But the local registered component Menu is not work.
Vue complain as follow
Vue warn]: Unknown custom element: <menu-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
---> <App> at src\App.vue

I have tried 
components:{ menuView:Menu}
components = { menuView:MenuView} // import MenuView from ...
components = { "menu-view" : new Menu}
none of them work...

Do I miss anything?

**Comment by ktsn** [comment]
Please use [our forum](https://forum.vuejs.org/) or [chat root](https://vue-land.js.org/), or carefully read the docs since the issue tracker is reserved for bug reports and feature requests.

```vue
//App.vue
<template>
<menu-view></menu-view>
</template>
<script lang="ts">
import Menu from "./components/Menu.vue"
@Component({
  components: {
    menuView: Menu
  }
}
export default class App extends Vue {
    name: 'app'
}
</script>
```
```js
//Menu.vue
@Component
export default class Menu extends Vue {}
```

**Comment by karateboy** [comment]
@ktsn Thank you.
