### ISSUE TITLE
Inconsistent passing components and directives parameters to @Component decorator

### ISSUE THREAD

**Issue by hehoo** [vuejs/vue-class-component#147]
I made a directive, e.g. direct 
```javascript
export default class Direct extends Vue {
....
}
```
I also made a component and tried to pass the directive to @Component decorator like below
```javascript
import Direct from 'path/to/direct';
@Component({
    directives: {
      Direct
    }
})
export default class Comp extends Vue {
...
}
```
If I do so, I will get an error "error TS2345: Argument of type '{ directives: { Direct: typeof Direct; }; }' is not assignable to parameter of type 'VueClass'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'VueClass'"

What I need to do to correct it is to instantiate the class Direct firstly and then pass to directives like below:
```javascript
const direct = new Direct();
@Component({
    directives: {
      direct
    }
})
``` 
The code above would work, but for components, the instantiation is not needed. Simply I can do this way:
```javascript
@Component({
    components: {
      Comp1,
      Comp2,
     ....
    }
})
```
Can we make them consistent so that manually instantiating the directive is not needed anymore ?
 
Thanks!

**Comment by ktsn** [comment]
How is your directive looks like?

**Comment by hehoo** [comment]
It is a very simple directive which is just to add some attribute to the element. like:
```javascript
export default class Direct extends Vue {
     bind(el, binding) {
        const value = bidning.value['somekey'];
        el.setAttribute('somekey', value);
     }
}
```
There should be nothing wrong with the directive. What I am curious is that why I can just pass the component class to @Component, but cannot for directive Class.  I assume that for component the instantiation will be made inside either in the decorator or in Vue itself. I am not 100% sure about that:)

**Comment by ktsn** [comment]
Ah, I missed the first code block.

You should not use class style declaration for directives because it does not accept constructor and also it does not have its instance. 
The typings error is expected since the `components` option accepts constructor `typeof Component` but `directives` option doesn't. (your `Direct` class does not have `bind` property until you instanciate it)

**Comment by hehoo** [comment]
Thanks for your quick response. 

Ok, I see.  I should not define the directive as a class but a pure object is fine.  Then I am a still confused why the component can be declared as a class?  To my understanding defining a pure object as a component is also ok if TypeScript is not used. What is the advantage to do that?
