### ISSUE TITLE
Error when using Recursive Vue Components (indirectly) in TypeScript

### ISSUE THREAD

**Issue by alexandrevribeiro** [vuejs/vue-class-component#148]
### Versions
- vue.js: 2.4.2
- vue-class-component: 5.0.2

### Reproduction Link
https://github.com/alexandrevribeiro/reproducing-vue-recursive-comp-issue-with-typescript

Steps to reproduce
Run the `vue-app-with-typescript` app and check the browser's console log (find the full reproducing info in the [reproduction repo](https://github.com/alexandrevribeiro/reproducing-vue-recursive-comp-issue-with-typescript)).

### What is Expected?
Indirectly recursive components should be rendered normally, or at least give another warn.

### What is actually happening?
Vue says:

` Unknown custom element: <comp-2> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by ktsn** [comment]
You have a typo in `Comp1.vue`

https://github.com/alexandrevribeiro/reproducing-vue-recursive-comp-issue-with-typescript/blob/master/vue-app-with-typescript/src/components/Comp1.vue#L14

**Comment by alexandrevribeiro** [comment]
Thank you @ktsn. 
In one of my tries to make it work, I made this mistake, but **I still have the same problem** (except that now the error says about the `<comp-1>` instead of `<comp-2>`:

```
[Vue warn]: Unknown custom element: <comp-1> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Comp2> at src\components\Comp2.vue
       <Comp1> at src\components\Comp1.vue
         <App> at src\App.vue
           <Root>
```

**Comment by ktsn** [comment]
Looks like because your components have cyclic dependency. The comp1 in comp2 is empty object because of that.
Consider using dynamic import. https://github.com/ktsn/reproducing-vue-recursive-comp-issue-with-typescript/commit/23121d495bd7311e22fc276a54b7183ec7ad75bf
