### ISSUE TITLE
How to add style import as @Component option?

### ISSUE THREAD

**Issue by micobarac** [vuejs/vue-class-component#149]
So far, I can set name, template and bunch of other options, but what about style?

Something like this would be ideal:

```typescript
@Component({
  name: 'AppComponent',
  template: require('./app.component.html'),
  style: require('./app.component.scss')
})
```

**Comment by kaorun343** [comment]
@micobarac 

Hi. You can import your style files like this below.

```ts
import Component from 'vue-class-component'
require('./app.component.scss') // <- import sass at here

@Component({
  name: 'AppComponent',
  template: require('./app.component.html')
})
export default class AppComponent extends Vue {
}
```

**Comment by micobarac** [comment]
I know this, just adding option to bind it as a @Component property would be nicer, that's all.

**Comment by kaorun343** [comment]
@micobarac 

Then, extending `ComponentOption` enable you doing so.
Adding `style` property into `ComponentOption` will make it work.

https://vuejs.org/v2/guide/typescript.html#Declaring-Types-of-Vue-Plugins

**Comment by micobarac** [comment]
@kaorun343 

Thanks for the tip. I will try this.

**Comment by micobarac** [comment]
@kaorun343 

It works!!!

I created a module declaration file `component.style.d.ts`:

```typescript
import Vue from 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    style?: any;
  }
}
```

Now I can write:

```typescript
@Component({
  name: 'AppComponent',
  template: require('./app.component.html'),
  style: require('./app.component.scss')
})
```

Thanks again :D

**Comment by micobarac** [comment]
Btw, at first I thought that the `name` property denoted html tag, but I found out that wasn't true.
I had to add only after adding this line:

```typescript
// @Component declaration goes here
Vue.component('app', AppComponent);
```
I could use the `<app></app>` tag in `index.html`.

Is there any more elegant solution to this? Should the `name` property of the `@Component` stand for component's HTML tag?

**Comment by kaorun343** [comment]
The usage of `name` property is written in the document.
https://vuejs.org/v2/api/#name

**Comment by ktsn** [comment]
As vue-class-component is intended to be used like syntax sugar of `Vue.extend`, we would not add extra option in it. In addition, you already can do that by using webpack loader as @kaorun343 explained or with single file component.

Please use [our forum](https://forum.vuejs.org/) or [chat root](https://vue-land.js.org) for further questions since the issue tracker is reserved for bug reports and feature requests. Thanks 🙂

**Comment by Bleser92** [comment]
Add to webpack config:
`{
    test: /\.scss$/,
    loader: 'vue-style-loader!css-loader!sass-loader'
  }`

**Comment by gsafety1** [comment]
@micobarac 
I have the same idea as you.  Find a good solution later.
use [vue-css-ts](https://github.com/numsg/vue-css-ts)
[example](https://github.com/numsg/vue-seed)
