### ISSUE TITLE
Styles?

### ISSUE THREAD

**Issue by howesteve** [vuejs/vue-class-component#15]
Hello,

I really like this approach, but I miss styling. How to embed scoped styles in a component? Similiar to *.vue's &lt;style scoped&gt; tags ?

Thanks,
Howe

**Comment by egoist** [comment]
Try css-modules?

**Comment by ktsn** [comment]
As @egoist said, we can use css-module on render hook and vue-loader should also work for class-style component.

**Comment by SpareShade** [comment]
@ktsn 
any chance you can point how to have import scoped css?
thank you!

**Comment by ktsn** [comment]
Just use vue-loader's scoped css.

**Comment by rmartins90** [comment]
I'm currently importing style inside my component.ts file:

`import `'./component.scss`;

Can you please show an example on how to use this on render hook?

**Comment by vekexasia** [comment]
using import doesn't work for me. still trying to understand how to import css.

**Comment by Bleser92** [comment]
##### style.d.ts
```typescript
declare module "*.scss" {
    const content: string;
    export default content;
}
```
##### component.ts
```typescript
import Vue from 'vue';
import Component from 'vue-class-component';
import template from "./component.html"
import style from "./component.scss"

@Component({
    template,
    style
})
export default class Component extends Vue {
   ...
}
```
But I have not yet found a way to import styles as scoped.

**Comment by milewski** [comment]
@Bleser92 having that style key into the @Component is pointless, it is not being understood by the component, in your case it "works" because u might be extracting the .scss to a external file.... so having that style key doesnt change anything..

however i think it's impossible to add styles at the current dev stage of this lib.... i'm rolling back to .vue files :( only

**Comment by gsafety1** [comment]
@howesteve 
I have the same idea as you.  Find a good solution later.
use [vue-css-ts](https://github.com/numsg/vue-css-ts)
[smaples](https://github.com/numsg/vue-seed)

**Comment by howesteve** [comment]
Thanks, I have switched to React because of these and other issues, but I'll look into it.
