### ISSUE TITLE
feat: Want a starter template that includes: Typescript + WebPack + vue-class-component with better folder structure (Enterprise level)

### ISSUE THREAD

**Issue by lanshunfang** [vuejs/vue-class-component#150]
Hey there,

I am curious that if it's possible to provide a `Start Template Github repo` for us with `Typescript + WebPack + vue-class-component` included.

For now, Microsoft official Github has `TypeScript-Vue-Starter` from https://github.com/Microsoft/TypeScript-Vue-Starter, which includes Typescript + WebPack + Vue, but no vue-class-component

Vue.js has `vue-class-component` from https://github.com/vuejs/vue-class-component has Typescript + vue-class-component, but no WebPack, and lack of good project folder structure organization. (Indeed, a snippet of Webpack configuration resides in `./example/`, but it's confusing. Why does webpack.config.js locate in ./example/? I have to move it out and change it so that it could be used into a real enterprise project)

Note that, I come from Angular 4+, and just get used to that style.

#114

**Comment by twocucao** [comment]
I use this repo for a while https://github.com/ducksoupdev/vue-webpack-typescript

**Comment by lanshunfang** [comment]
@twocucao Thanks. I am stilling leaving this issue open since I would like to have a official version from vuejs :), which should have a good maintenance in their devops circle.

**Comment by twocucao** [comment]
Find another repo https://github.com/MMF-FE/vue-typescript , it looks like much more vue-offcial-style

**Comment by ktsn** [comment]
We are planning TypeScript template for upcoming vue-cli version.
https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08

Closing since we cannot anything for this in this repo. Please wait the typescript support of vue-cli.
