### ISSUE TITLE
Global defined components does not work

### ISSUE THREAD

**Issue by r-moiseev** [vuejs/vue-class-component#152]
I have `bootstrap.js` file when I `use` Vuetify
```
require('vuetify/dist/vuetify.min.css');

import Vue from 'vue/dist/vue.js';
import Vuetify from 'vuetify';

Vue.use(Vuetify);

export default Vue;
```

My component loofs line

```
<template>
 ....
</template>

<script>
    import Vue from '../../bootstrap'
    import Component from 'vue-class-component'

    @Component
    export default class App extends Vue {
       //...
    }.
</script>
```

Problem is Vuetify components does not work in this template.

if i do not use `vue-class-component` everyting works fine.

Thx.

**Comment by ktsn** [comment]
You shouldn't write `import Vue from 'vue/dist/vue.js'`. It will load multiple Vue constructor in one script. And this problem is probably caused by it.
See: https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by r-moiseev** [comment]
Now I use `vue.runtime`, but this does not solved subject

**Comment by r-moiseev** [comment]
I`ve tryed ti do this

```
<script>
    import Vue from 'vue'
    import Vuetify from 'vuetify'
    Vue.use(Vuetify);
    import Component from 'vue-class-component'

    @Component
    export default class App extends Vue {
       //...
    }.
</script>
```

Still no effect, vuetify components does not work

**Comment by ktsn** [comment]
Then please provide a complete reproduction to confirm 🙂
