### ISSUE TITLE
with this plugin, how I can use the mapActions , mapGetters & mapStates in vuex ?

### ISSUE THREAD

**Issue by O2O4** [vuejs/vue-class-component#154]
with this plugin, how I can use the mapActions , mapGetters & mapStates in vuex ?

**Comment by ktsn** [comment]
Please use our [forum](https://forum.vuejs.org) or [chat room](https://vue-land.js.org) for asking your questions in the next time.

```js
@Component({
  computed: mapGetters(['someGetter'])
})
class App extends Vue {
  // ...
}
```
