### ISSUE TITLE
Using vue-class-component to instantiate the root Vue instance?

### ISSUE THREAD

**Issue by KokoDoko** [vuejs/vue-class-component#158]
I would like to use a vue-class-component to instantiate the root Vue instance like this:

**index.ts**
```
import App from "./components/app.vue"
let vm = new App();
```

**app.vue**
```
<template></template>

<script lang="ts">
    import Vue from 'vue'
    import Component from 'vue-class-component'
    @Component({
        el: "#app"
    })
    export default class App extends Vue {
        created() {
           console.log("hi there!")
        }
    }
</script>
```

But this generates the error: `option "el" can only be used during instance creation with the new keyword`

Is this approach not possible?

**Comment by ktsn** [comment]
You can use `$mount` instead.
https://vuejs.org/v2/api/#vm-mount
