### ISSUE TITLE
Make imports implicit

### ISSUE THREAD

**Issue by jamelt** [vuejs/vue-class-component#161]
Just as a stylistic point, is there perhaps anyway this library can be tweaked so that importing `Vue` and `Component` isn't needed for every component? Could we somehow make those implicit? I tried fiddling with the webpack ProvidePlugin to no avail.

``` typescript
import Vue from 'vue'
import Component from 'vue-class-component'

@Component
export class FooComponent extends Vue {
}
```

I find that `Vue` and `Component` import so superfluous to have to include in very component.

**Comment by ktsn** [comment]
If you use Babel and don't use class properties, you can omit `extends Vue` otherwise we can't.
