### ISSUE TITLE
How to use local styles without using.Vue files

### ISSUE THREAD

**Issue by wjtGitHub** [vuejs/vue-class-component#165]
example
![111111111111111111111111111111111111111111111111111111](https://user-images.githubusercontent.com/17404628/31536650-fabea9ae-b031-11e7-9320-f544e8859669.png)

Can example use the local style like the scoped of the .vue file?

**Comment by ktsn** [comment]
Hi, thanks for interested in this project. However, your issue seems a usage question.
As the issue tracker is reserved for bug reports and feature requests, we encourage you to ask it in [our forum](https://forum.vuejs.org) or [chat room](https://vue-land.js.org).
Thanks!

**Comment by wjtGitHub** [comment]
@ktsn 
Ok,thank you.
