### ISSUE TITLE
vue-async-computed compitability? 

### ISSUE THREAD

**Issue by s-KaiNet** [vuejs/vue-class-component#166]
Is there any guidance on how to use `vue-class-component` with [vue-async-computed](https://github.com/foxbenjaminfox/vue-async-computed)?  
I did a quick search and haven't found anything.

**Comment by ktsn** [comment]
Hi, thanks for interested in this project. However, your issue seems a usage question.
As the issue tracker is reserved for bug reports and feature requests, we encourage you to ask it in [our forum](https://forum.vuejs.org) or [chat room](https://vue-land.js.org).
Thanks!
