### ISSUE TITLE
The String attributes in a TypeSrcipt class cannot turn into the props in the Vue component

### ISSUE THREAD

**Issue by CasterKKK** [vuejs/vue-class-component#167]
While using the vue with ts, I found when using v-bind to access the String attributes in the ts class, it will throw a "Property or method is not defined" warning, and the string is not accessable also. But the weird point is that when passing a number attribute, everything is ok. So it bothers me a lot.
Here are some code:
``` html
<!-- components/Hello.vue -->
<template>
  <div>
    <div class="greeting">Hello {{name}} {{exclamationMarks}}</div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import Component from 'vue-class-component'

  @Component({
    props: {
      name: String,
      enthusiasm: Number
    }
  })
  export default class Hello extends Vue {
    name: string
    enthusiasm: number

    get exclamationMarks() {
      return Array(this.enthusiasm + 1).join('!');
    }
  }
</script>
```
``` typescript
// index.ts

import Vue from "vue";
import Hello from './components/Hello.vue';

let v = new Vue({
  el: "#app",
  template: `
    <div>
        Name: <input v-model="name" type="text">
        <hello :name="someName" :enthusiasm="6" ></hello>
    </div>
    `,
  components: {
    Hello
  }
});
```
And the result is:
<img width="1277" alt="1" src="https://user-images.githubusercontent.com/16066720/31580132-6a4e47b4-b147-11e7-8a8e-8cf04d00c9ce.png">

But if I change the name to an number, for example: `<hello :name="123" :enthusiasm="6" ></hello>`
The result is:
<img width="1279" alt="2" src="https://user-images.githubusercontent.com/16066720/31580144-bde76d6a-b147-11e7-8ed9-b017f236dd86.png">
Which means the name attribute actually can receive the passing number.
So I am confused. Why does the ts class only receive the number type attribute but not the String attribute?

**Comment by HerringtonDarkholme** [comment]
Please read the doc. https://vuejs.org/v2/guide/syntax.html

In v-bind attribute, the attribute value is a JavaScript expression. So this line 

`<hello :name="someName" :enthusiasm="6" ></hello>`

means an identifier `someName`, so you should have a field `someName` on your Vue isntance.

I think you can change it to 

`<hello :name="'someName'" :enthusiasm="6" ></hello>`

The subtle difference is `'someName'` is a string inside the double quotes.
