### ISSUE TITLE
Unresolved function or method while using ts-vue in WebStorm

### ISSUE THREAD

**Issue by CasterKKK** [vuejs/vue-class-component#168]
Hi guys,
While using vue and ts in WebStorm, I found that WebStorm sometimes cannot resolve the function of another class. Here is an example:
<img width="1280" alt="3" src="https://user-images.githubusercontent.com/16066720/31580188-ab6ec11e-b148-11e7-87fc-9d05bed0045b.png">

<img width="1280" alt="4" src="https://user-images.githubusercontent.com/16066720/31580197-bbc6f2d4-b148-11e7-9ca9-2661e719b90f.png">

But in fact, the `sayHello()` method is existing. And if using VSCode, the `sayHello()` method can be resolved perfectly. So, I wonder if you guys have any solution.

**Comment by HerringtonDarkholme** [comment]
From the code you paste, it seems nothing is wrong with the code. I guess WebStorm cannot check TypeScript in Vue single file. I'm not a user of WebStorm, it's just my guess.

I would suggest WebStorm users open an issue on WebStorm's forum.

**Comment by ktsn** [comment]
There is nothing we can do for this in vue-class-component because this seems an issue of editor's type resolution strategy.
