### ISSUE TITLE
Using component decorator with other components not extending Vue, causes error

### ISSUE THREAD

**Issue by d1820** [vuejs/vue-class-component#171]
I am trying to add a 3rd party component to the components object of the @Component decorator, because the 3rd party vue object does not extend from Vue (its a plan es5 component) I get a typescript error.

3rd party lib:  https://github.com/Justineo/vue-awesome

Component
```
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { IAuthService } from 'interfaces';
import { lazyInject } from '../../kernel';
import { INJECTION_TYPES } from '../../injection-types';
import Icon from 'vue-awesome/components/Icon.vue';
import 'vue-awesome/icons/eye';

@Component({
    components: {
        MenuComponent: require('../navmenu/navmenu.vue'),
        Icon
    }
})
export default class AppComponent extends Vue {
    @lazyInject(INJECTION_TYPES.AuthService)
    private _authService: IAuthService;

    signin() {
        this._authService.signIn();
    }
}
```
![pasted image at 2017_10_23 01_47 pm](https://user-images.githubusercontent.com/377631/31912468-da14db32-b7f8-11e7-8dfe-b76bb575a2fb.png)

Any recommendations on how to get past this issue? Otherwise seems like a common problem that most 3rd party component developers are only coding to es5 standards.

Thanks

**Comment by ktsn** [comment]
This is due to invalid type declaration for SFC.
See: https://github.com/vuejs/vue-class-component/issues/123#issuecomment-315608700
