### ISSUE TITLE
How do I do lazy loading?

### ISSUE THREAD

**Issue by micobarac** [vuejs/vue-class-component#172]
How do I do lazy loading? Is it possible? Are async components possible using this library?

**Comment by ktsn** [comment]
Yes you can.

**Comment by micobarac** [comment]
Why did you close this topic? Is it possible that you are rude enough to do this without giving me any example code or a clue???

**Comment by micobarac** [comment]
Lazy loading can significantly improve loading speed, and it would be nice to include some king of tricks and tips section in Readme.md about this.

**Comment by ktsn** [comment]
Just write as same as you write async component in normal vue way. https://vuejs.org/v2/guide/components.html#Async-Components

As written in README:

> For all other options, pass them to the decorator function.

So you can use `component` option in the decorator:

```js
@Component({
  components: {
    // async components here
  }
})
class App extends Vue {}
```

BTW, issue tracker is dedicated for bug reports and feature request. Please use [our forum](https://forum.vuejs.org/), [chat room](https://vue-land.js.org/) or StackOverflow to ask your question in the future. Thanks!

**Comment by micobarac** [comment]
Thanks.

**Comment by HerringtonDarkholme** [comment]
Github issue isn't a place for q&a.

It's really rude to raise a issue that even doesn't qualify as a stackoverflow question.
