### ISSUE TITLE
No props, hooks, etc when using Jest

### ISSUE THREAD

**Issue by schoening** [vuejs/vue-class-component#173]
I am trying to use Jest to unit test my components. In the browser, everything works fine (using webpack); running the test with Jest gives strange results:

```
<template>
    <li>
        {{ message }}{{ myProp }}
    </li>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";

@Component({
    created() {
        console.log("created")
    },
    props: ["myProp"]
})
class MyComponent extends Vue {

    message: string = "";

}

export default MyComponent;
</script>
```

This runs fine in the browser:
```
import MyComponent from "./components/MyComponent.vue";
import { mount } from "vue-test-utils";

const wrapper = mount(MyComponent, {
    el: "#app",
    data: {
        message: "Hello world",
    },
    propsData: {
        myProp: "!"
    }
});

console.log( wrapper.vm.myProp ); // => "!"
```
*It displays **"Hello world!"** and the console log output is **"created"*** and **"!"**

---

It does **not** work with Jest:
```
import { mount } from "vue-test-utils";
import MyComponent from "../src/components/MyComponent.vue";

describe("MyComponent.vue", () => {
    let wrapper: any;

    beforeEach(() => {
        wrapper = mount(MyComponent, {
            data: {
                message: "Hello world",
            },
            propsData: {
                myProp: "!"
            }
        });
    });

    it("has a message property with the value 'Hello world'", () => {
        expect(wrapper.vm.message).toEqual("Hello world"); // => OK
    });

    it("has a myProp with the value '!'", () => {
        expect(wrapper.vm.myProp).toEqual("!"); // => ERROR
    });

    it("has the expected html structure", () => {
        expect(wrapper.vm.$el).toMatchSnapshot(); // => OK
    });
});
```
***myProp** is **undefined** and created does not console.log anything...*

---

**Additional strangeness:**
*Adding myProp to the data object:*
```
wrapper = mount(MyComponent, {
    data: {
        message: "Hello world",
        myProp: "!"
    }
});
```
Browser:
```
[Vue warn]: The data property "myProp" is already declared as a prop. Use prop default value instead.
```
Jest:
**All Tests OK**

---

I hope this was descriptive enough...
I am adding a link to a copy of my package.json: https://hastebin.com/pamuyicofi.json

**Comment by ktsn** [comment]
same problem as #122?
It would be helpful if you can provide self-contained reproduction.

**Comment by schoening** [comment]
I accidentally fixed it!

I am however unsure WHY it is working now.. I think it has to do with having a proper .babelrc that I copied from @blocka's example repo that you linked [#122](https://github.com/vuejs/vue-class-component/issues/122)

Anyways..  Here is a working repo. With 2 tests. 1 using "regular" vue and one using class-component

(Both using typescript)

[vue + typescript + class-component + jest](https://github.com/vuejs/vue-class-component/issues/122)

**Comment by schoening** [comment]
I added a test using the "vue-property-decorator" and that works fine too :)
Should this be closed, or should I find out why things are working first?

**Comment by ktsn** [comment]
Oh, I see. Let's close this issue :)
