### ISSUE TITLE
How to Exclude a property from the data mixins

### ISSUE THREAD

**Issue by gaoupon** [vuejs/vue-class-component#175]
E.g:
```js
@Component
class Example extends Vue {
  store = new Store()
  bar() {
    // use this.store
  }
}
```
What if I don't wanna`store` appear in the `data` mixin of final options?(No need to observe it.)

Using `get store() {return new Store()}` seems to be a possible solution.  When just use Class Property, what's the solution to make `store` as a property as  the Vue instance(not add to the data mixins)?

**Comment by ktsn** [comment]
Declare it in lifecycle hook as same as the normal vue way.

```js
@Component
class Example extends Vue {
  beforeCreate() {
    this.store = new Store()
  }
}
```

---

Please use [our forum](https://forum.vuejs.org), [chat room](https://vue-land.js.org) or StackOverflow to ask usage question in the next time as the issue tracker is reserved for bug reports and feature requests.
