### ISSUE TITLE
Latest vue releases dosent work with typescript

### ISSUE THREAD

**Issue by andtii** [vuejs/vue-class-component#176]
I have upgraded vue and vue class component to latest release
"vue": "~2.5.2",
"vue-class-component": "~6.0.0",
"vue-property-decorator": "~6.0.0",
"vue-router": "~3.0.1",

But i cant find any examples working with this. Im getting errors on both Vue and Component.

![image](https://user-images.githubusercontent.com/1434571/32107117-f6853c02-bb2d-11e7-9c3e-8b7fc8d00de2.png)
![image](https://user-images.githubusercontent.com/1434571/32107171-18c23c66-bb2e-11e7-904e-18a6c14db00f.png)

What has happened? Do you have any working examples using the new stuff?

**Comment by ktsn** [comment]
What TypeScript version do you use? Vue v2.5 needs TypeScript >= 2.4
FYI: https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08

**Comment by andtii** [comment]
Im using 2.5.3

**Comment by HerringtonDarkholme** [comment]
It works fine for me.

I guess your editor doesn't pick up the correct compiler version.

**Comment by ktsn** [comment]
@andtii Could you provide a self-contained reproduction?

**Comment by andtii** [comment]
@ktsn yea i will do some more testing and come back! Thnx for quick response!

**Comment by andtii** [comment]
@ktsn Visual Studio was running on the 2.3 tooling version even if i did install the newer package. I missed to update the version number in the project file. Lets close this issue.
