### ISSUE TITLE
Add docs for where to ask for support

### ISSUE THREAD

**Issue by mgood** [vuejs/vue-class-component#177]
While I was searching for some information on a few topics I noticed that a number of the issues had suggested using the forum or chat for additional support. I think a few notes in the project docs would help let people know to look there first before opening an issue.

A section in the README titled "Support" or "Where can I get help?" with the links would be helpful.

Updating the Github issue template to include a quick note about asking questions on the forum first would also be great.

The Github [CONTRIBUTING](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file is also a good place to put additional docs on how and when to report an issue vs asking questions.

**Comment by ktsn** [comment]
Thanks for the suggestion.
I've updated the readme and issue template.

**Comment by mgood** [comment]
That was quick, thanks! 👍
