### ISSUE TITLE
Add examples for Vuex

### ISSUE THREAD

**Issue by mgood** [vuejs/vue-class-component#178]
When I was looking for more information about using this with Vuex, I found several people had already asked very similar questions to what I was looking for:
#56 #109 #154 

Thanks for the helpful answers. Since this seems to be a common question, I think it would help users find this information more quickly if it was included in the `examples`.

**Comment by mgood** [comment]
BTW, I can also look into adding a PR for this if it helps. I didn't have time to get to that this morning so I wanted to make a quick note, but I'm happy to help.

**Comment by ktsn** [comment]
Feel free to make a PR!

**Comment by havvg** [comment]
Maybe this will help you getting started. It's step by step from plain VueJS TodoMVC to TypeScript + vue-class-component + vuex + vue-property-decorator more to come: https://github.com/havvg/vuejs-typescript-todo-mvc

**Comment by ktsn** [comment]
add the example via #250
