### ISSUE TITLE
Visual Studio build errors: module '"vue"' has no exported member 'ComponentOptions', cannot find name 'Vue'.

### ISSUE THREAD

**Issue by IvanYur4enk0** [vuejs/vue-class-component#179]
Hello all, sample project that has build errors attached.

**Steps for reproduce**

1. Open project in Visual Studio 2017 or Visual Studio 2015.
2. Install npm dependencies.
3. Press Build.

**Errors**

Severity	Code	Description	Project	File	Line	Suppression State

Error		Build:Module '"vue"' has no exported member 'ComponentOptions'.	{path}\node_modules\vue-class-component\lib\declarations.d.ts	1

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\declarations.d.ts	2	

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\declarations.d.ts	5	

Error		Build:Module '"vue"' has no exported member 'ComponentOptions'.		{path}\node_modules\vue-class-component\lib\index.d.ts	1	

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\index.d.ts	4	

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\index.d.ts	5	

Error		Build:Module '"vue"' has no exported member 'ComponentOptions'.	{path}\node_modules\vue-class-component\lib\util.d.ts	1	

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\util.d.ts	5	

Error		Build:Cannot find name 'Vue'.		{path}\node_modules\vue-class-component\lib\util.d.ts	6

**Questions**

1. Where ComponentOptions interface or class declared, I can't find it in this repository(I can find only imports, but not declaration) or in vue.d.ts?

Best Regards
[TestVueComponentApplication.zip](https://github.com/vuejs/vue-class-component/files/1424072/TestVueComponentApplication.zip)

**Comment by ktsn** [comment]
Because you are using Vue v1.x typings. vue-class-component v6.0.0 only supports Vue v2.5 typings.
Please use vue-class-component v3.x for Vue v1.x

**Comment by IvanYur4enk0** [comment]
@ktsn 
Do Vue v2.5 typings exists in NuGet, because I can't find them?

**Comment by ktsn** [comment]
Vue >= v2 typings is published in npm with core library. You don't need to external typings managers.
https://vuejs.org/v2/guide/typescript.html

**Comment by IvanYur4enk0** [comment]
It is cool if I use not Visual Studio and Visual Studio Code for example, but what I should do to fix provided sample? We are using ASP.NET MVC, not ASP,NET Core + NPM and webpack for JS and NuGet for .d.ts files, we can't add d.ts files from node_modules folder.

**Comment by IvanYur4enk0** [comment]
Only one thing that I see to fix this issue - is to add d.ts files from NPM repository manually to project but using that way - I am losing the ability to automatically detect new versions of vue typings and can't automatically upgrade this version.

**Comment by IvanYur4enk0** [comment]
https://github.com/vuejs/vue/issues/6965 ticket to vue issue tracker added.

**Comment by ktsn** [comment]
Well, it looks like you are using npm for `vue-class-component`, then you can use it for installing Vue's typings? You don't need any extra jobs other than `npm install vue` since TypeScript automatically detect it.
Using npm is also recommended way to download d.ts in TypeScript community in favor of `@types`.

**Comment by IvanYur4enk0** [comment]
Thank you for the suggestion, but it is not working. For ASP.NET(not ASP.NET Core) all *.d.ts files should be included in the project, if they only downloaded to node_modules it is not enough for Visual Studio IntelliSense and build or maybe I doing something wrong. If it easy fix - could you please check it in my uploaded sample and upload fix version of this sample?
