### ISSUE TITLE
Component options as class static members

### ISSUE THREAD

**Issue by noldors** [vuejs/vue-class-component#185]
Hi guys,
What do you think about passing component parameters not as decorator parameters but as static members of the class like this:
```js
@Component
export default class App extends Vue {
  static name = 'MyComponent'

  static props = {
    propMessage: String
  }

  static components = {
    FirstComponent, SecondComponent
  }
}
```
I think this version is a more class-oriented, because the decorator is simple @ Component and its parameters are written directly in the class definition.

If you approve my proposal, I would like to make a PR.

**Comment by ktsn** [comment]
dup of #98
