### ISSUE TITLE
how it works with typescript's generics types？

### ISSUE THREAD

**Issue by AbnerZheng** [vuejs/vue-class-component#188]
it seems @props work terrible with generjcs type？ Is there any plan to support it?

**Comment by HerringtonDarkholme** [comment]
Can you provide a more concrete example?

**Comment by AbnerZheng** [comment]
@HerringtonDarkholme  Of course I can. But when I run your example in your repository with npm run dev. It compiled fail. 
I just fork the repository and exec `npm install`, then exec `npm run dev` .  Could you reproduce the error ?

**Comment by ktsn** [comment]
@AbnerZheng Please describe your proposal more concretely. I don't see what you are suggesting from the current description.
