### ISSUE TITLE
Honoring `name` in ComponentProps

### ISSUE THREAD

**Issue by DanubeRS** [vuejs/vue-class-component#189]
Consider the following component;

```
<template>
    <!-- Component Template -->
</template>

<script lang="ts">
    import Vue from "vue";
    import Component from "vue-class-component";

    @Component({
        name: 'root'
    })
    export default class Hello extends Vue {
        /* Implementation */
    }
</script>
```

Being consumed by the root instance;
```
new Vue({
    el: "#app",
    template: `<root></root>`
});
```

As I understand it, the class is not generated in such a way that is available to the root `Vue` instance, but I have also found that the `name` property is not honoured in the following example;

```
new Vue({
    el: "#app",
    template: `<root></root>`,
    components: {
        RootComponent
    }
});
```
Rather, the name is that of the assigned default import name.

Is this expected, or am I under false assumptions of how the decorator works?

I am thinking of behaviour that mimics [this](https://github.com/vuejs/vue-loader/issues/339)

**Comment by ktsn** [comment]
`name` option does not do anything in regard to component registration.
In your example, you are registering your component as `RootComponent`, so you have to refer it by `<RootComponent>` or `<root-component>` (alias).

The `name` option is intended to be used for recursive components or debugging purpose.

See: https://vuejs.org/v2/api/#name

**Comment by DanubeRS** [comment]
Cool, thanks. Seems as if I have been misinterpreting the motivation behind `name` for quite some time.
