### ISSUE TITLE
Add example for TSX with render function

### ISSUE THREAD

**Issue by jamelt** [vuejs/vue-class-component#196]
Can the docs present an example of a Vue component using it's render function as opposed to a template? 

There is not much of anything, that's coherent, out there that describes how to write Vue components using the vue-class-component and using Vues render function.

Cobbling docs from ts-loader, vue-loader, vue, vue-class-component, babel-plugin-transform-vue-jsx -- it's not clear how to get this working. Considering that the render functions are heavily touted in contrast to React, it would be nice to have a working example somewhere.

**Comment by ktsn** [comment]
PR welcome

**Comment by HellooooNewman** [comment]
Does appear to be that different.
I got this to work for me.

`    render(createElement:any) {
        return createElement(
        'div', {
            'class': {
                'is-red': true
            }
        }, [
            createElement('p', 'Example Text')
        ])
    }`
