### ISSUE TITLE
Class extends work a bit wrong

### ISSUE THREAD

**Issue by fimars** [vuejs/vue-class-component#199]
## Background
```myInputComponent.ts
// base input component
@Component({
  template: require('any.html')
})
export class InputComponent extends Vue {
  // ...something doesn't important

  @Watch('value')
  private valueChange(newVal: string | number, oldVal: string | number) {
    this.setCurrentValue(newVal);
  }
}
```

```myMockInputComponent.ts
// a mock component for test
@Component({
  template: require('any.html'),
})
class MockComponent extends InputComponent {
  constructor() {
    super();
  }
}
```

### How
<img width="340" alt="default" src="https://user-images.githubusercontent.com/16299018/33307803-e5595b14-d452-11e7-99cf-dc76c41bec43.png">

Work very well, but have a bit weird. The MockInputComponent have two duplicate content, 
caused his watcher to be triggered twice.

Like this:
<img width="755" alt="default" src="https://user-images.githubusercontent.com/16299018/33307883-2d3a947a-d453-11e7-8e87-1ba4c980fbd3.png">

Am I doing something wrong?

**Comment by ktsn** [comment]
Could you provide self-contained reproduction?

**Comment by HerringtonDarkholme** [comment]
I guess the problem comes from here.

https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L58

And here 

https://github.com/vuejs/vue-class-component/blob/master/src/util.ts#L22-L28

Note `__decorator__` is inherited, every time `@Component` call will add inherited decorators again, thus duplication happens.

**Comment by fimars** [comment]
@HerringtonDarkholme  I agree your guess. @ktsn  Here is a reproduction [jsfiddle](https://jsfiddle.net/m7koc7uv/).

**Comment by ktsn** [comment]
Thanks for the repro. This seems a regression caused by static member forwarding that introduced in v6.1.0.
