### ISSUE TITLE
How to nest components using this method?

### ISSUE THREAD

**Issue by nmabhinandan** [vuejs/vue-class-component#2]

**Comment by yyx990803** [comment]
Same as you would with `Vue.extend`. The exported class can be registered via `Vue.component` or passed in the `components` option.

**Comment by nmabhinandan** [comment]
Isn't it possible to nest components using class property?
Something like this
```js
import component from 'vue-class-component'
import Test from "./test.component.js"

@component
export default class AppComponent {
  components = {
    test: new Test({ el: "#testcomp" })
  }

  static template = `
    <div>
      <div id="testcomp"></div>
    </div>
  `
}
```

**Comment by yyx990803** [comment]
You need to make all options `static`. Otherwise it will be treated as a data property.

**Comment by nmabhinandan** [comment]
:+1: Thanks!
