### ISSUE TITLE
 TS2345 Loading: typeof NotFound

### ISSUE THREAD

**Issue by testxin** [vuejs/vue-class-component#202]
run well:
<style>....<style>
<temp...>....</temp..>
<script lang="ts" >
.....
</script>
run error:
<style>....<style>
<temp...>....\</temp...>
<script lang="ts" src='./index.ts' ></script>

**Comment by ktsn** [comment]
Please provide a **minimal and self-contained reproduction** if you are reporting a bug.

**Comment by HerringtonDarkholme** [comment]
I don't think this is bug of class-component library but of either ts-loader or of vue-loader.

We encourage you to use [our forum](http://forum.vuejs.org/) or [community chat](https://chat.vuejs.org/) to ask your questions. Thanks!
