### ISSUE TITLE
Declaring Existing Class Options As Component Props Throws Error

### ISSUE THREAD

**Issue by XedinUnknown** [vuejs/vue-class-component#205]
Hi,

And first of all allow me to thank you for this. It's a great piece of work, which brings us one step closer to writing de-coupled, framework-agnostic logic. Big respect.

Of course, I found this package because I want to create vanilla JS models which would contain logic specific to their respective problem domains. Models shouldn't know that they're going to be used as Vue components. They just operate on some data, and represent some things. Together with a dependency injection pattern that I use, this allowed me to create model packages that don't have Vue or `vue-class-component` as hard dependencies. Instead, I am creating the logic, and allowing the consumer use it as they see fit. I myself, as one of the consumers, will use my models as bases for Vue components.

The problem is that sometimes, you need specifically props, not data, such as when dealing with tag attributes, or declaring DI parameters. Class properties become just simple data when decorated with `@Component`. In my case, the packages that declare the classes and the packages that use them as components are different packages, so I cannot just use the `@Prop` decorator. Using `@Component` on an existing - dependency-injected - class constructor results in the following error message:

> The data property "myProperty" is already declared as a prop. Use prop default value instead

### Suggested Solution
One way of resolving this, and allowing consumers to maintain SoC, could be to "transform" a class property to *either* a Vue component prop (if it is in `props`) *or* data; not both.

**Comment by ktsn** [comment]
Could you describe your problem with an example code? I'm still not sure about your problem and suggestion.

**Comment by XedinUnknown** [comment]
### Repo1
```js
// MyModel.js

export default class MyModel
{
  myName = null;

  getMessage()
  {
    console.log(`Hello, ${this.myName}!`);
  }
}
```

### Repo2
```js
// app.js

function createComponent(Component, model, options)
{
  let factory = Component(options);
  
  return factory(model);
}
```

```html
<!-- index.html -->
<div id="my-app">
  <my-component my-name="XedinUnknown">
    {{this.getMessage()}}
  </my-component>
</div>
<script type="text/javascript">
  require(['factory', 'model', 'vue', 'vue-class'], function (createComponent, model, Vue, Component) {
    let component = createComponent(Component, model, {props: ['my-name']});
    let app = new Vue({
      el: '#my-app',
      components: {
        'my-component': component
      }
    });
  });
</script>
```

**Comment by HerringtonDarkholme** [comment]
@XedinUnknown Currently, `Component` requires the decorated class, in this case `factory`, is a subclass of Vue. 

We hook on the `_init` method on Vue, so there is no workaround to make decorated class independent of Vue.

**Comment by ktsn** [comment]
Well, if you mean you don't want to declare the class property as reactive, it's not possible unfortunately. It's because the implementation will be quite complicated and the behavior becomes unpredictable since the way getting the class properties are so limited.

**Comment by XedinUnknown** [comment]
Sorry, I didn't understand that. If you're talking about the `factory` variable in the `createComponent()` function, then it's what your `Component` function returns. The class that is being decorated is `MyModel`. Surely, `MyModel` doesn't have to be a subclass of `Vue`. Right?

**Comment by XedinUnknown** [comment]
@ktsn, it's not about reactivity. It's a conflict between `data` and `props` members.

**Comment by XedinUnknown** [comment]
@HerringtonDarkholme, apparently it does. You really are [hard-unhooking](https://github.com/vuejs/vue-class-component/blob/master/src/data.ts#L7) `_init()`. Then I guess, this will have to be changed. And it's easy: you just check if it really is a `Vue` instance, and only then unhook. Doesn't sound like a big problem to me.

**Comment by ktsn** [comment]
I'm talking about the `data` exactly. All the class properties are declared as `data`. So if you want to declare `props`, you cannot use class properties.

**Comment by HerringtonDarkholme** [comment]
@ktsn OP's original code is quite different from orthodoxical usage. If we rewrite in plain API. It would looks like

```ts
@Component({
  props: ['my-name'] // conflict
})
class MyModel { // no extends Vue
  myName = null;

  getMessage()
  {
    console.log(`Hello, ${this.myName}!`);
  }
}
```

The problem is `myName` is counted as in both `data` and `props`. However, I would argue that this should be a usage problem. In general, you cannot reuse a DataModel as ViewModel in Vue.

**Comment by XedinUnknown** [comment]
> you cannot use class properties
@ktsn, exactly. You cannot. But you should, if you want to keep the model agnostic of Vue. Which is why I want to use your package. It would be super super cool. Separation of Concerns all the way! Give SOLID to JS! :D

**Comment by XedinUnknown** [comment]
@HerringtonDarkholme. yes, exactly. For the model to be able to become a component, `extends Vue` is not really a functional requirement, but a requirement that you are imposing on it. Or am I wrong?

**Comment by XedinUnknown** [comment]
> you cannot reuse a DataModel as ViewModel in Vue

Yes, and that's where your amazing package comes to the rescue. Why would I want to write domain-specific logic that is *coupled to a UI framework*?

**Comment by XedinUnknown** [comment]
Was reading #71, and came across [this code](https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L43-L51). Here, there is both a class property and a declared prop called `foo`. Yet, there doesn't seem to be a conflict. How is that?

Also, #71 kind of intersects with this issue, and again it is being pointed out that one cannot do what I'm trying to do because you ["initialize instance by Vue class and intercept its initialization call"](https://github.com/vuejs/vue-class-component/issues/71#issuecomment-285094459). Could you kindly explain why this is necessary? [This code](https://github.com/vuejs/vue-class-component/blob/master/src/data.ts#L7-L27) appears to exclusively cater for the Vue `props` option, and then expands them and other properties into... getters and setters, apparently. I don't see anything that would require the class to be a Vue instance, really.

**Comment by ktsn** [comment]
* vue-class-component does not just use user defined class, it collects methods/getter/setter from the class and translate them into Vue component options.
* For the class properties, we cannot collect them as same as the methods/getters/setters because it's defined in constructor, so we need to instantiate the user defined class under the hood or you cannot use class property at all.
* To deal with custom decorators like `@Prop`, vue-class-component does not collect class properties as `data` if it is initialized with `undefined`.

**Comment by XedinUnknown** [comment]
Thanks, that's very useful information. Still, not sure what is the answer here. Is it that what I want cannot be done, and you will not be willing to upgrade the lib in order to help facilitate better SoC?

**Comment by ktsn** [comment]
I don't think we can separate the component meta data and implementation because the component class actually would belong to presentation layer rather than domain layer. For example, we may need to write animation logic, event handling from DOM in the class implementation.

We would not willing to cater for this since it probably introduce extra complexity in vue-class-component and the usage is not orthodox.
