### ISSUE TITLE
[Feature Request]vue-class-component can depend on `dist/vue.esm.js`

### ISSUE THREAD

**Issue by plantain-00** [vuejs/vue-class-component#206]
1. I'm using`import Vue from "vue/dist/vue.esm.js;"` because https://github.com/parcel-bundler/parcel/ doesn't support `import Vue from "vue";` (that cause error: `You are using the runtime-only build of Vue where the template compiler is not available`)
2. `vue-class-component` use `import Vue from 'vue'`(https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L1), that cause error: `You are using the runtime-only build of Vue where the template compiler is not available`
3. webpack alias can solve this(`alias: { 'vue$': 'vue/dist/vue.esm.js' }`), but parcel don't support alias: https://github.com/parcel-bundler/parcel/issues/25

So I'm requesting something like:
```ts
// import Vue from "vue";
import Vue from "vue/dist/vue.esm.js";
import Component from "vue-class-component";

Component.use(Vue);
```

webpack can also benefit from that.

**Comment by ktsn** [comment]
Writing `vue/dist/vue.esm.js` causes a problem with hot reload and other libs which imports duplicated Vue object so we recommend to always use alias.
Also, I don't think we can provide different builds depends on external lib as it would increase the maintainance cost so much.

I think you should request the alias feature to percel as it is supported other well-used bundlers.
