### ISSUE TITLE
Reactivity and undefined properties

### ISSUE THREAD

**Issue by MayaWolf** [vuejs/vue-class-component#211]
In #35, a change was made where properties that are `undefined` will not become reactive. I feel like this change was overshooting its intentions a little, since the point is actually to get rid of *uninitialized* properties in the data object.
Considering that in a lot of coding standards the use of `null` is prohibited in favour of using `undefined`, it's a little problematic that `null` has to be used as a default value in class components.
I'm not sure whether there's a better way to fix this for Babel users, but as a TypeScript user, this change has honestly become quite inconvenient as every class component now needs to be littered with warning suppressions for the `null` keyword.
Any chance a better solution could be looked into here?

**Comment by ktsn** [comment]
Unfortunately, we can't since the Babel decorator treats an uninitialized property and a property initialized with `undefined` as the same thing.
I encourage you to use `data` hook instead for now.

I'll revisit with this behavior after Babel and TypeScript implement stage 2 or later decorators.

**Comment by Glandos** [comment]
Hi @ktsn, it seems that it landed long time ago in https://github.com/babel/babel/pull/7976 Apparently, the [changelog mentioned only this](https://github.com/babel/babel/blob/master/CHANGELOG.md#v700-beta45-2018-04-23):
> Make Stage 2 decorators "default" (implementation is still WIP), and require people use the decoratorsLegacy option for easier migration.

But it has been there since nearly  2 years now.
Is there anything left missing to make `undefined` data being reactive again?

**Comment by ktsn** [comment]
Because TypeScript does not support stage 2 yet.

**Comment by msklvsk** [comment]
For anyone who’s wondering: TypeScript still does not support stage 2:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/473012/101216569-69001f80-3688-11eb-825b-1030d60941b2.png">

Not even planned for November.
