### ISSUE TITLE
[Bugs] Extends a base vue component will create an unexpected vue component instance. 

### ISSUE THREAD

**Issue by Ku4nCheang** [vuejs/vue-class-component#217]
Description:
When a component is extends a base component. Unexpected instance is created. It may cause memory leakage. A extended component and base component will be automatically created when you render it in a template or Vue.component(extended_component). Component Extends Vue doesn't have this issue.

Expection:
It should only one vue component instance was initialised because the template only one Vue component is needed to render.

Issue Example:
https://jsfiddle.net/hvcpucu3/1/

Step to Reproduce:
1. Run the example.
2. Open the chrome developer tools.
3. Take a heap snapshot in Memory Tab.
4. FIlter the constructor by input "Vue"
5. Observe the VueComponent Counting.

![screen shot 2018-01-20 at 7 13 53 pm](https://user-images.githubusercontent.com/4996109/35182783-1928ad7c-fe16-11e7-8626-5a3cd311d08d.png)

**Comment by ktsn** [comment]
This looks not actually a vue instance but the `prototype` object of `Problem` referred from [here](https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L28). And it seems not introduce any memory leakage.

You can confirm it does not leak in this example. (Clone it and `npm i && npm start`)
https://github.com/ktsn/vue-class-component-memory-test

**Comment by Ku4nCheang** [comment]
👍  Thanks for quick reply.
