### ISSUE TITLE
TS2307: Cannot find module error but the application compiles and runs properly

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-class-component#219]
I'm trying to set up a TypeScript project with the vue-class-component decorator support.

Everything seems to be fine, the application compiles properly and works fine as well but there's one thing that bothers me.

Code editors (both: WebStorm and Visual Studio Code) complain about the second line of the `index.js` file. The message is:

    TS2307: Cannot find module './components/App.vue'

Here's the code:

**index.js**
``` javascript
import Vue from 'vue';
import App from './components/App.vue';

new Vue({
  el: '#js--app',
  render (createElement) {
    return createElement(App);
  },
});

```

**App.vue**
``` html
<template>
  <button @click="onClick">Click!</button>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  @Component
  export default class App extends Vue {
    message: string = 'Hello!';

    onClick(): void {
      window.alert(this.message)
    }
  }
</script>
```

**tsconfig.json**
``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES5",
    "sourceMap": true,
    "inlineSources": true,
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

And here's a screenshot as a confirmation :slight_smile:

![406e68d7ab6eb9d0cdabb792a4e0b7adf1239749](https://user-images.githubusercontent.com/533954/35704675-31a1bd22-0798-11e8-981b-61526afc69a4.png)

---
**So why am I having this error and what does it really mean?**

...Actually, I know what this error means because I read through the [Typescript documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html) which says that this error shows up when TypeScript compiler can't resolve a module. But it doesn't seem to make much sense to me. If it couldn't resolve the `App.vue` module  then my application wouldn't compile. Am I right?

I tried to set `allowSyntheticDefaultImports ` to `true` in `tsconfig.json`, but it doesn't change anything. 

So I'm a bit lost now. My app compiles and runs, but from what I can see it shouldn't :upside_down_face:

---
PS
I don't know is Github a proper place for such questions... but on the other hand I'm not sure is it a configuration issue or is it a bug in vue-class-component.
[I've already created a topic on the Vue.js forum](https://forum.vuejs.org/t/typescript-configuration-and-ts2307-cannot-find-module-error/26636), but nobody responded to it

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vue-file-cannot-be-imported-in-ts-file

you can also uses https://github.com/HerringtonDarkholme/vue-ts-plugin

**Comment by wujekbogdan** [comment]
@HerringtonDarkholme 
Thanks a lot!

Putting the following `vue-shim.d.ts` declaration file under my `./src` directory solves the problem:
``` typescript
declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}
```

Your [vue-ts-plugin](https://github.com/HerringtonDarkholme/vue-ts-plugin) plugin solves the issue as well.

BTW, could you explain what's the benefit of using your plugin over a simple module declaration? Is there any reason why I should use it instead of the solution that I've already applied?

I'm trying to develop a [vue.js template](https://github.com/wujekbogdan/fuse-vue-ts) based on [FuseBox](https://fuse-box.org/) that anyone can use, so I prefer to keep the dependencies list as short as possible.

**Comment by ktsn** [comment]
Closing as this is not an issue of `vue-class-component` as described by @HerringtonDarkholme .

**Comment by vinayvinu500** [comment]
TS2307: Cannot find module error but the application compiles and runs properly 

I find another solution for this problem in vscode...
I could Give up for this solution after 4 days of working Vue errors with vscode...
Just implement the Vue language in vscode and its optimise the code in Vue framework..
which is implemented default language as Javascript in bottom-right beside of UTF-8 in vscode....
And Thank you for your support and Help, But it could not solved after file is removed in OPEN EDITORS in vscode

![main js - vue-project - Visual Studio Code 13-11-2019 13_05_32](https://user-images.githubusercontent.com/49785350/68742754-f2285c80-0616-11ea-9216-427d8810534c.png)
![main js - vue-project - Visual Studio Code 13-11-2019 13_06_59](https://user-images.githubusercontent.com/49785350/68742755-f2285c80-0616-11ea-9cf5-7e274fde837c.png)

**Comment by riddvanjs** [comment]
This is only for vue 2 wth TypeScript.

I had the same error, what i did was:

1. add this to your main vue file,: 
`import VueCompositionAPI from '@vue/composition-api'
Vue.use(VueCompositionAPI)`
2. Copy this line: `declare module '@vue/composition-api'` and paste it into shims-vue.d.ts

Then it should work.
