### ISSUE TITLE
Add a note about definite assignment assertion of Typescript 2.7 in docs

### ISSUE THREAD

**Issue by skegel13** [vuejs/vue-class-component#221]
Typescript 2.7 introduces a new flag called --strictPropertyInitialization which requires class properties to be property of a class gets initialized in the constructor body, or by a property initializer. 

If I don't initialize props and try to compile the code, I get an error: ` Property 'property' has no initializer and is not definitely assigned in the constructor.`

If I initialize the prop, I get the warning in the browser `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "property"`

I guess the simplest way to handle this would be to turn off the flag or use the new Definite Assignment Assertions feature, which allows an ! to tell Typescript that a variable is indeed assigned for all intents and purposes (`property!: string`).

Would it make sense to either document these requirements, or come up with a new way to handle properties with the component decorator. Could it be possible to initialize props using constructor parameters in the class?

**Comment by ktsn** [comment]
Yes, stated about definite assignment assertion in docs makes sence. PR is welcome!

**Comment by 304NotModified** [comment]
I've created PR #269 for this. 

Thanks for the info @skegel13

**Comment by ktsn** [comment]
Added on https://class-component.vuejs.org/guide/property-type-declaration.html
