### ISSUE TITLE
this.$route error

### ISSUE THREAD

**Issue by flyinhigh** [vuejs/vue-class-component#222]
how to get $route.param when using vue-class-component?  there would be an error like `Property '$route' does not exist on type xxx`  when I write this.$route

**Comment by HerringtonDarkholme** [comment]
Hi! Please make sure to use the [the official forum](http://forum.vuejs.org) or [community chat](https://chat.vuejs.org/) for usage questions. The issue list of this repo is **exclusively** for bug reports and feature requests. Thanks!

**Comment by flyinhigh** [comment]
ok, thanks
