### ISSUE TITLE
beforeRouteEnter not excuted in 6.2.0

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/vue-class-component#226]
It's normal in 6.1.2.

**Comment by ktsn** [comment]
Thanks for reporting the issue. Please provide minimal reproduction to confirm the problem?

**Comment by yuu2lee4** [comment]
l copyed code from readMe.

**Comment by ktsn** [comment]
Again, please provide a reproduction or we cannot help you. 😕 
We have a test code for [possible cases](https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L29-L42) such as an example written in README and all test is passing. I also confirm the example code is working in jsfiddle. https://jsfiddle.net/sg3t5y2e/12/

**Comment by LinusBorg** [comment]
OP doesn't seem to be willing or able to provide a reproduction. Closed.

**Comment by M6stafa** [comment]
@yuu2lee4 the common problem with the router hooks is that they don't call in child component.
this is the vue-router behaviour. i thinks it will be good to mention this in vue-router doc.

sorry for my bad english.

**Comment by yuu2lee4** [comment]
It is fine after i delete node_modules and reinstall the dependencies.

**Comment by Jhonsem** [comment]
@M6stafa vue:2.5.15+vue-router:3.0.1 , had same problems if you use ts script
