### ISSUE TITLE
TS2307 Cannot find module error

### ISSUE THREAD

**Issue by theironcook** [vuejs/vue-class-component#228]
Hi,
I'm trying to get a new project with WebPack 4 + Typescript 2.7 + Vue working.  I'm trying to use the vue-loader with ts-loader etc. but I keep getting the TypeScript compiler error TS2307.

My code can be found here:
https://github.com/theironcook/Kiki/tree/master/TryOne

To run, I use the command: npm run build-client

All I'm trying to do is include this view: https://github.com/theironcook/Kiki/blob/master/TryOne/src/client/Two.vue
Into this ts file:
https://github.com/theironcook/Kiki/blob/master/TryOne/src/client/main.ts

But I get this error:
[tsl] ERROR in /Users/name/projects/Kiki/TryOne/src/client/main.ts(3,17)
      TS2307: Cannot find module './Two'.

I'm pretty sure my webpack configuration is messed up:
https://github.com/theironcook/Kiki/blob/master/TryOne/config/webpack.config.client.js
I don't think I have ts-loader or vue-class-component set up right?

Any help would be appreciated.

**Comment by HerringtonDarkholme** [comment]
You need to add appendSuffixTo option.

https://github.com/Microsoft/TypeScript-Vue-Starter#adding-webpack

**Comment by theironcook** [comment]
@HerringtonDarkholme  Wow, thanks for the quick feedback.  I tried to include the appendTsSuffixTo option (I hope correctly) but still see the same tsc error 2307.

https://github.com/theironcook/Kiki/blob/master/TryOne/config/webpack.config.client.js#L30

Is there still something wrong with my webpack config?

**Comment by theironcook** [comment]
@HerringtonDarkholme  - that linked helped me out.  Thanks - I was missing the vue-shims.d.ts file and my include was missing the suffix of .vue.  Things are working now.  Thanks,

**Comment by HerringtonDarkholme** [comment]
No it should not work.

**Comment by theironcook** [comment]
What shouldn't work?  Adding the vue-shims.d.ts file?  It seems like it did...

**Comment by HerringtonDarkholme** [comment]
vue-loader should work without shim.d.ts. 
Vue-loader will call ts-loader to analyze vue file. ts-loader should correctly find vue file without falling back to shim.d.ts. If it does require shim, I suspect it is configured wrong and doesn't produce correct output.

The shim is for editors which don't read your webpack config.

**Comment by HerringtonDarkholme** [comment]
I can produce correct output in MS' starter, but cannot compile in your project.

**Comment by theironcook** [comment]
@HerringtonDarkholme  I removed the vue-shim.d.ts file.
If I import the vue file via "import Two from './Two.vue" but do NOT use the component in the file I get the TypeScript compiler error TS2307.  If I DO use the Two component in the file I don't get the error:
`const theVue = new Vue({
  el: '#app-main',
  data: {
    message: 'Hello,  Vue!'
    components: [Two]
  }
});`

So, include the Vue but don't use it - get the error.

**Comment by HerringtonDarkholme** [comment]
@theironcook Thanks for debugging. This totally makes sense to me now.

I believe this is an inherent limitation between ts-loader and vue-loader. ts-loader relies on vue-loader to preprocess the file. But vue-loader only processes used file. So in this case it breaks.

**Comment by theironcook** [comment]
Yeah, thanks for the help.  It makes sense now.
