### ISSUE TITLE
Is Calling Vue.component Necessary?

### ISSUE THREAD

**Issue by theironcook** [vuejs/vue-class-component#229]
I kept getting the runtime Vue error:
vue.esm.js:578 [Vue warn]: Unknown custom element: <test-component> - did you register the component correctly? 

In my .vue file I had to add a manual Vue.component call to register the component at the end like this...

@Component
class TestComponent extends Vue { 
...
}

Vue.component('test-component', TestComponent)  // Why is this necessary?
export default TestComponent

I'm new to Vue but I'm kind of surprised this is necessary.  I thought that the component might have been registered automatically via the @Component tag or somewhere else.  Am I doing something wrong?

**Comment by theironcook** [comment]
Nevermind - I figured it out.
If I import a component directly into my main typescript file it seems like the component won't be registered.  But if I import the component via the @Component( { components: {xxx}} ) syntax then the component is registered.

**Comment by gdutwyg** [comment]
@theironcook i meet the same problem. If I import a component directly into my main typescript file it seems like the component won't be registered. just like `Vue.use(component)`, how you solved it? thanks

**Comment by theironcook** [comment]
@gdutwyg 
Here's an example:
```
// File is App.vue
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import TopNavBar from './components/TopNavBar.vue';

@Component({
  components: {
    TopNavBar
  },
})
class App extends Vue { 
}

// need to register the App as a component manually because it isn't registered anywhere else
Vue.component('app', App);
export default App;
</script>
```

**Comment by kaorun343** [comment]
Why do you do so? You don't have to do register `App` component globally.

Instead, how about this?

```ts
// File is App.vue
import { Component, Vue } from 'vue-property-decorator';
import TopNavBar from './components/TopNavBar.vue';

@Component({
  components: TopNavBar
})
export default class App extends Vue {}
```

```
// File in index.ts (entry point)

import Vue from 'vue'
import App from './App.vue'

new Vue({
  el: '#target'
  render: h => h(App)
})
```
