### ISSUE TITLE
migration path for vue-typescript

### ISSUE THREAD

**Issue by davidmoshal** [vuejs/vue-class-component#23]
Hi, I've been using the vue-typescript project, which is excellent, BUT, doesn't support Vue 2.0.
https://github.com/itsFrank/vue-typescript
The issue I filed on 5 weeks ago has had no response.

So, am wondering if you'd consider adding some of the features of that project here.
For example:

`@Watch` - a watcher on computed values and/or properties
`@Prop ({required: true})` - easier way to specify properties.

This would make it easier to transition to your project.

**Comment by mvujica** [comment]
+1 to that! There are couple of libraries I'm testing with vue 2.0 for my project, av-ts looks promising.

**Comment by davidmoshal** [comment]
@mvujica please keep us informed, I took a quick look at av-ts, haven't tried it out, but I agree it looks promising for Vue 2.0.

Having said that, the loss of sync in Vue 2.0, which I agree is a good move going forward, does mean a bit of a re-think regarding emit. At a minimum it seems that emit makes the code more verbose, and given that Vue's main selling point is the lack of verbosity, this is a frustration.

So for me, the requirement to rethink sync->emit and the lack of vue-typescript support, has kept me at Vue 1.x + vue-typescript.

Please post experiences of migrating vue-typescript to av-ts.

**Comment by mvujica** [comment]
@davidmoshal I never used vue-typscript, the lack of events was limiting to me, that is also dropped in Vue 2.0. I used limited amount of sync and was using event model already so I'm plunging to Vue 2.0 and typescript with av-ts. Converted some small components and for now is working fine  (props, data, lifecycle and watch are all working).
I will keep you posted.

**Comment by ktsn** [comment]
Hi, @davidmoshal. Sorry for the late answer.

I guess you are already enjoying [av-ts](https://github.com/HerringtonDarkholme/av-ts). It definitely great library for Vue 2 + TS and it would covers vue-typescript with many additional features!

If you would like to use similar API to vue-typescript, there is [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) that is built on the top of vue-class-component and provides `@prop` and `@watch` decorators.

In addition, vue-class-component itself has some extendable APIs now that means you can [easily create any custom decorators with `createDecorator`](https://github.com/vuejs/vue-class-component#create-custom-decorators) and [add custom hooks with `registerHooks`](https://github.com/vuejs/vue-class-component#adding-custom-hooks).

Unfortunately, we cannot introduce `@prop` decorator to vue-class-component itself for now because it has some problems with Babel decorators. But I think it is suffice to create the decorator in userland by using `createDecorator` to write Vue 2 in TS. So I'm closing this issue.

Thank you for your interest in this project, though!

**Comment by davidmoshal** [comment]
@ktsn looking at this library again.
Am surprised by a couple of things, maybe I'm using it wrongly:

1) Properties have to be declared twice? 
  - @Component({props: {...}} 
  - and also in the class body?
  - libraries like `vue-typescript` do not require that!

2) Mutating properties results in a message like this:

```
vue.common.js?e881:521 [Vue warn]: Avoid mutating a prop directly since 
the value will be overwritten whenever the parent component re-renders. 
Instead, use a data or computed property based on the prop's value. 
Prop being mutated: "propMessage" 
(found in component <app>)
```
 - so, how exactly is one supposed to mutate properties then?

**Comment by LinusBorg** [comment]
> 1) Properties have to be declared twice? 

No. you define props in the @Component decorator, and internal `data` inside of the class, as class properties.

> 2) Mutating properties results in a message like this

This has nothing to do with this package - you should not mutate props in Vue 2. The reason why is given in the warning you saw.

>  - so, how exactly is one supposed to mutate properties then?

You don't, at least not in your component. Instead, you emit an event to the parent, who is the owner of the data that your component received via props, and it's the parent's responsibility

It's mentioned in the Migration guide here: https://vuejs.org/v2/guide/migration.html#Prop-Mutation-deprecated

**Comment by davidmoshal** [comment]
Honestly, I'm not seeing the upside of Vue 2.0, or of the official Typescript library.
I've been using `vue-typescript` for sometime, and even though it's Vue 1.x only, it seems superior.

What's wrong with local mutation?

```ts
import { Component, prop } from 'vue-property-decorator';
import * as Vue from 'vue';

@Component({
  template: `
      <div>
        <div>{{propA}}</div>
        <button @click="propA +=1 ">click</button>
      </div>
  `
}) export class One extends Vue{
    @prop({
      default: 0
    })
    propA: number   
}
```

Why on earth should this throw errors?
Has Vue 'jumped the shark' in 2.0?

**Comment by LinusBorg** [comment]
You seem to feel strongly about this. 

Anyway - Vue 2 tried to focus more on the pattern that data is only ever passed down. 

So it's a bad practice to mutate a prop that was received from a higher component. 

If that prop is a string, of course the mutation will be local. But there is another issue, and as I said, it's explained in the warning... Have you read it? 

Vue 2 uses a virtual DOM now, which come with some changes to the rendering process. One of those changes is that if a parent component re-renders, it passes the props down to the child again - which would override any local changes made in the child. 

You still *can* mutate that prop - Vue will only **warn** you that this might backfire unexpectedly and introduce subtle bugs.

**Comment by davidmoshal** [comment]
> You seem to feel strongly about this.

True, but then again, I did actually propose the RactiveJS pattern upon which Vue is based:

https://github.com/ractivejs/ractive/issues/366
https://github.com/ractivejs/ractive/issues/299

> So it's a bad practice to mutate a prop that was received from a higher component.

Debatable.

> it's explained in the warning... Have you read it?

Yes

> Vue 2 uses a virtual DOM now, which come with some changes to the rendering process. One of those changes is that if a parent component re-renders, it passes the props down to the child again - which would override any local changes made in the child.

That statement is very concerning, even if the virtual DOM is all the rage.
