### ISSUE TITLE
Passing in 'el' - any ideas how ?

### ISSUE THREAD

**Issue by appsolutegeek** [vuejs/vue-class-component#231]
Hi,

I am currently using the following syntax (plain JS) and everything works great.

```
import Vue from 'vue';

var app = new Vue({
    el: '#app',
    data: {
        message: 'IT IS WORKING'
    }
})
```

I have been trying to convert that to the following, but it doesn't seem to work. I couldn't find an example. I am know I am missign something, really appreciate any help. Thanks

import Vue from 'vue'
import Component from 'vue-class-component'

```
@Component
export default class MyComponent extends Vue {
    el = '#app';
    
    message: string = 'IT IS WORKING'
}
```

So the above code, as far as I can see, is duplicate of the standard JS above. The standard JS above works but the new vue-class-componentd doesn't.

Any ideas ?

Thanks in advance

**Comment by ktsn** [comment]
https://github.com/vuejs/vue-class-component#usage

> For all other options, pass them to the decorator function.

```js
@Component({ el: '#app' })
class App extends Vue {}
```

Please ask your usage questions in [forum](https://forum.vuejs.org/) or [chat room](https://chat.vuejs.org) in the next time since the issue list is dedicated for feature request and bug reports. Thanks!
