### ISSUE TITLE
Changelog or Migration Doc

### ISSUE THREAD

**Issue by gsccheng** [vuejs/vue-class-component#233]
Hi, I'm looking to migrate from v5.0.1 to 6.2.0 and am wondering where I can easily see the (breaking) changes and how to migrate. I don't seem to see one (and Discord says I don't have permission to post on Vue-land channel to ask, with nowhere to ask for permission). Thanks!

**Comment by ktsn** [comment]
Please see [release note](https://github.com/vuejs/vue-class-component/releases).
