### ISSUE TITLE
使用webpack.dll打包vue-class-component后template不可用，建议在文档中标注清楚

### ISSUE THREAD

**Issue by luozhihua** [vuejs/vue-class-component#238]
使用webpack.dll打包vue-class-component后template不可用，建议在文档中标注清楚

**Comment by ktsn** [comment]
Could you describe it in English for communication?

**Comment by yushaoyi** [comment]
+1
cannot use  component in vue template  

when use **webpack.DllPlugin** package vue-class-component and link the vendor.dll.js to index.html,
it may cause error 
Unknown custom element: <router-view> - did you register the component correctly

**Comment by ktsn** [comment]
Could you provide a minimal repro to confirm?

**Comment by yushaoyi** [comment]
ok, this is the [repro](https://github.com/yushaoyi/vue-demo)

**Comment by ktsn** [comment]
Because you are not specify `vue` alias in your `webpack.dll.config.js`. Then you are loading duplicated `Vue` instance. It causes the error.

**Comment by yushaoyi** [comment]
yes, that's the reason. Thanks a lot
