### ISSUE TITLE
Using props

### ISSUE THREAD

**Issue by mvujica** [vuejs/vue-class-component#24]
Description for vue-class-component is unclear, at least to me, for using props in typescript class if I define e.g.:
@Component({
props: { 
   id: Number,
   name: String
}
})

 How Can I use prop value in class? Do I define them as class property again?

class Test extends Vue {
 id: number;
name: string;

get NameId() {
  return this.name + this.id;
}
}

Please advise, thanks!

**Comment by mvujica** [comment]
Also what about watching properties, is that supported?

**Comment by ktsn** [comment]
Currently, there are no decorators other than `@Component`, but we are considering to support additional decorators for TypeScript.

**Comment by mvujica** [comment]
Thanks for the update, that's unfortunate. I guess I must try different community solutions like av-ts. Will you consider merging community code like av-ts and provide full official typescript support soon? Vue + Typescript strong typing is so much better.

**Comment by kaorun343** [comment]
Here's my decorator, [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator). I hope it will help you.

**Comment by mvujica** [comment]
thanks @kaorun343.
will this be merged with main vue-class-component @ktsn ?

I don't know how many developers use typescript and vue by for me type checking, code completion and editor warnings are invaluable. I think if there is enough demand core vuejs team should join forces with community (av-ts, vue-typed, vue-typescript ...) and make some official release for Typescript.

Only typings is not enough for this growing framework, we need **fist class typescript** support and documentation for beginners. Sorry if I'm too demanding but I believe both vue and typescript have great future, we don't need full blown switch like angular2 but we need good base.

For the time I will test av-ts some more, it has nice feature for strongly typed watch().

**Comment by ktsn** [comment]
We probably will not merge community code into `vue-class-component`.
But I'm currently thinking about adding essential features like `@Props` for Vue & TypeScript beginners as starting point.
If you want more advanced features, it would be better to use community solution or make your own decorators for now.

**Comment by ktsn** [comment]
P.S. Vue core team is also interested in TypeScript + Vue and I'm working for it. If you want to make vue better for TypeScript, your contribution is welcome :)
(Actually, there are few men using TypeScript in core team now 😂 )

**Comment by yyx990803** [comment]
I do like @kaorun343 's decorator - it seems a lot of users like that in https://github.com/itsFrank/vue-typescript, which unfortunately hasn't been updated in a while.

@kaorun343 : if you are interested, and is willing to maintain your decorator implementation for the long run, I'd like to make it a recommended library for Vue+TS users (in this repo's README and in docs). What do you think?

**Comment by kaorun343** [comment]
@yyx990803 Thanks for adding a link to my decorators into README.
I'm going to maintain my decorator for a long time, so I hope to do so.

**Comment by yyx990803** [comment]
@kaorun343 great!
