### ISSUE TITLE
runtime-only build error (while using with Nativescript-Vue

### ISSUE THREAD

**Issue by championswimmer** [vuejs/vue-class-component#242]
I was trying to use Nativescript-Vue with vue class style components 

Here is my file - pretty standard and simple
```vue
<template>
  <StackLayout xmlns="http://schemas.nativescript.org/tns.xsd">
    <Label :text="message"></Label>
    <TextView v-model="message"></TextView>
  </StackLayout>

</template>
<script>
  import Vue from 'vue'
  import Component from 'vue-class-component'
  @Component
  export default class Home extends Vue {
    message = "HOME IS HERE"
  }
</script>
```
I keep encountering this error "You are using the runtime-only build of Vue where the template compiler is not available." 

I am confused, because in my entire project I have only used sfc. So there are no string templates anywhere.

**Comment by ktsn** [comment]
Could you provide a reproduction?

**Comment by championswimmer** [comment]
Mentioning @tralves here as he as done a lot of webpack work on Nativescript-Vue

And yes, will upload the reproduction ASAP

**Comment by championswimmer** [comment]
@ktsn 
Here you go https://github.com/championswimmer/hasgeek_mobile_nsvue

**Comment by championswimmer** [comment]
If I add this to Events.vue
```vue
<script lang="ts">
    import {Vue, Component} from 'vue-property-decorator'
    @Component({name: 'Events'})
    export default class Events extends Vue {

    }
</script>
```

```
CONSOLE ERROR file:///app/app.js:14093:20: [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
found in
---> <Events> at src/components/pages/Events.vue
<App> at src/App.vue
<Root>
```

**Comment by ktsn** [comment]
How can I run the reproduction? I just run `watch:ios` / `watch:android` command but it looks not work 😕

**Comment by michaeljota** [comment]
For those who end up here playing around with Vuido, you need to set an alias for Vue to Vuido. 

If using webpack directly:
```js

    resolve: {
      extensions: [ '.js', '.vue', '.json' ],
      alias: {
        vue: 'vuido' // This line
      }
    },
```

If you want to use `@vue/cli` I'm still working on that, but you need a `vue.config.js` file.
