### ISSUE TITLE
Mixin class constructors invoked twice

### ISSUE THREAD

**Issue by Foolyou** [vuejs/vue-class-component#244]
Here's the reproduction: https://jsfiddle.net/avdk6cxe/
```javascript
const { default: Component, mixins } = VueClassComponent

let mixinObjects = [];

@Component
class MixinClass extends Vue {
  constructor () {
    super()
    mixinObjects.push(this);
    this.id = mixinObjects.length;
  }
}

@Component({
  template: `
    <h1>{{ id }}</h1>
  `
})
class App extends mixins(MixinClass) {
}

new Vue({
  el: '#app',
  render: h => h(App)
})

let span = document.createElement('span')
span.innerHTML = `Number of mixinObjects: ${mixinObjects.length}`
document.body.appendChild(span)
```

It seems the two `@Component` decorators on `App` and `MixinClass` both push `MixinClass` into `options.mixins` [as here](https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L52), and then `MixinClass` constrcutor will be invoked twice.

There could be some cases the mixins rely on side effects, which will cause unexpected behavior.

**Comment by ktsn** [comment]
Because vue-class-component calls a constructor in the `data` hook to collect class properties. You shouldn't use constructor on decorated class. You can use `created` hook instead.

It may be improved when we support the latest decorator spec.
