### ISSUE TITLE
have vue-class decorators act server side

### ISSUE THREAD

**Issue by yringler** [vuejs/vue-class-component#245]
I was
- using the webpack vue-loader.
- marking all node modules as webpack "externals", so I can get vue from a cdn and not have it as part of my build

When I loaded app, I was surprised when there were errors in my console, stating that VueClassComponent  was not defined.

It would seem that the [decorators are only being applied client side](https://github.com/Microsoft/TypeScript/issues/2900)..
However, being that the purpose of these decorators is simply to transform the code into a vue options object, could that happen server side, perhaps as an extension to vue-loader, during the .vue compilation, removing the need for an additional client-side dependency?

**Comment by ktsn** [comment]
You can transpile your server side code...
