### ISSUE TITLE
vue-class-component not support jest unit

### ISSUE THREAD

**Issue by wjtGitHub** [vuejs/vue-class-component#248]
![image](https://user-images.githubusercontent.com/17404628/39673382-bca7607e-516d-11e8-90f7-43d30867503a.png)
config
![image](https://user-images.githubusercontent.com/17404628/39673385-d1c82f2e-516d-11e8-943a-87345517f324.png)

**Comment by wjtGitHub** [comment]
@ktsn

**Comment by ktsn** [comment]
Please use [our forum](https://forum.vuejs.org), [chat room](https://chat.vuejs.org) or StackOverflow to ask usage question since issue tracker is exclusively for bug reports and feature requests. Thanks.
