### ISSUE TITLE
surport scoped styles

### ISSUE THREAD

**Issue by nailfar** [vuejs/vue-class-component#249]
Surport function like this:
@Component({
style:"./xxx.scss",
scopedStyle:“./xxx.scss”,
})

**Comment by ktsn** [comment]
That is not a feature vue-class-component should provide. Please use vue-loader.

**Comment by nailfar** [comment]
@ktsn 
How can I use vue-loader with .ts file
//in  Purview.ts file 
```
import Toolbar from "@/components/Toolbar";
import { Component, Prop, Vue } from "vue-class-component";
import "./Purview.scss";
@Component({
  template: require("./Purview.html"),
  components: {
    Toolbar,
  },
})
export default class Purview extends Vue {
....
} 
```
"./Purview.scss" is not scoped ;
How should do;

**Comment by ksbomj** [comment]
Hi there!

Why it is not possible to realize a such feature in TypeScript? So you say it's not possible to import separate file and mark it as scoped? No way to avoid to have CSS in the component file if I want it to be scoped?
