### ISSUE TITLE
Mixin static methods inheritance.

### ISSUE THREAD

**Issue by juanfernandoe** [vuejs/vue-class-component#251]
Hi,

is there any way to inherit static methods from mixin ?

**Comment by ktsn** [comment]
You can't because static methods are not supported Vue.js side. You need to directly inherit your constructor.

**Comment by danimoh** [comment]
Hello. Can you elaborate please what you mean by `You need to directly inherit your constructor.`?
From that statement, I'd have expected the following to work: https://jsfiddle.net/ho0e7y23/1/
