### ISSUE TITLE
Non reactive property

### ISSUE THREAD

**Issue by andre-dw** [vuejs/vue-class-component#253]
I'm trying to understand Typescript and how to add a non reactive object to an Vue instance and using the latest vue-cli@3.0.0-beta.16.

```
<script lang="ts">
import User from '@/models/user';
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {

  private user: User = new User();
  // This is a referenced type.
  // User 2 will automatically change when user1 is changed during input
  private user2 = this.user;
  // User 3 will not even be reactive because we set it to undefined
  private user3: undefined;

  private created() {
    // User 3 will not be reactive because it is only declared here
    this.user3 = new User();
  }

}
</script>
```
Where `User` is an class
```
class User {
  public firstName: string = '';
  public lastName: string = '';
}

export default User;
```
The error i get is `Type 'User' is not assignable to type 'undefined'.`

**Comment by ktsn** [comment]
For questions and support please use the [the official forum](https://forum.vuejs.org) or [community chat](https://chat.vuejs.org). The issue list of this repo is exclusively for bug reports and feature requests. Thanks.

**Comment by andre-dw** [comment]
For people searching for an fix.
This seems to work:
```
<script lang="ts">
import User from '@/models/user';
import { Component, Prop, Watch, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {

  private user!: User;

  private created(): void {
    this.user = new User();
  }
}
</script>
```
Where the exclamation mark (!) tells the TS compiler we will set the value later.
Explainded here: https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/
