### ISSUE TITLE
can't support vue-rx

### ISSUE THREAD

**Issue by printjs** [vuejs/vue-class-component#260]
ts
![image](https://user-images.githubusercontent.com/17404628/42615549-4644b086-85dd-11e8-8c3c-d3ba389c7c6f.png)

html
![image](https://user-images.githubusercontent.com/17404628/42615555-4e563e02-85dd-11e8-900f-c83791a87de1.png)

err
![image](https://user-images.githubusercontent.com/17404628/42615565-5ba6eab6-85dd-11e8-92ea-dd045f79a718.png)

**Comment by printjs** [comment]
@ktsn

**Comment by ktsn** [comment]
Please don't use issue tracker for asking support as it's dedicated for bug reports and feature requests. You should use [forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) to do that.
