### ISSUE TITLE
Component.registerHooks broken with Vue CLI 3

### ISSUE THREAD

**Issue by MisterGoodcat** [vuejs/vue-class-component#261]
Versions used:

* vue 2.5.16
* vue-class-component 6.2.0
* vue/cli-service 3.0.0-rc.5

With Vue CLI 3, `Component.registerHooks` does not work reliably anymore. It's a hard to pin-down error, but what I see is:

If your components are reachable by any chain of imports, decorators are invoked before any of your custom code runs, no matter where you put said code. By nature, components are always reachable through imports from your entry point (think main -> router -> component). This results in calls to `Component.registerHooks` being executed only _after_ the component decorators already have been invoked, meaning hooks like `beforeRouteLeave` now are only part of `methods`.

In development mode (serve from dev server), this is an extremely irritating issue, because if you happen to modify your component in a way that will trigger hot reload for it, hooks suddenly start working ($internalHooks at that point is correct), but only until you hit F5 (-> Heisenbug effect). The issue happens in both dev and prod builds though.

The only reliable workaround I found so far is adding a hack to your component, for example in `mounted`:

```ts
// HACK
if ((this.$options as any).__proto__.beforeRouteLeave == undefined) {
    (this.$options as any).__proto__.beforeRouteLeave = this.$options.methods!.beforeRouteLeave;
}
```

This of course does not work for "beforeRouteEnter".

**Comment by MisterGoodcat** [comment]
Okay, after trying to get this to work for a while, I finally moved the `registerHooks` call to a separate file and imported that, which fixes the issue. If you carefully read [the docs](https://github.com/vuejs/vue-class-component#adding-custom-hooks), it seems this is how it's supposed to be anyway.

The only thing puzzling me is why it worked flawlessly the way we had it before, and then only started making problems after the switch to Vue CLI 3 - shouldn't have worked in the first place, should it?

**Comment by Jaeiya** [comment]
This actually gave me a big headache...I almost created a similar issue before finding this one. Even if you import the component and register them above the imports in the `main.ts` file, it still doesn't work properly. I don't like that there's some kind of magic going on with the import statements. But I guess we have to live with that for now.
