### ISSUE TITLE
`@Component({ model:{ prop:"something" } })` does not work!

### ISSUE THREAD

**Issue by nailfar** [vuejs/vue-class-component#262]
when Customizing Component v-model

``` 
import A from './A';
@Component( )
class B extends Vue {
  someting:string="test";

  render(h){
    return  <A v-model={this.someting}/>
  }
}
```
 
---------------------------- it does not work ( this.something got undefined )
```
@Component({
  model:{
    prop:"something"
  }
})
class A extends Vue {
  @prop() something:string;
   ...
  mounted(){
    console.info(this.something); // got undefined;
  }
}
```
----------------------------it does not work ( this.something got 'undefined')
```
@Component
class A extends Vue {
  @Model() something:string;
   ...
  mounted(){
    console.info(this.something); // got 'undefined';
  }
}
```
----------------------------but it does work ( this.value got 'test')
```
@Component({
  model:{
    prop:"value"
  }
})
class A extends Vue {
  @prop() value:string;
   ...
  mounted(){
    console.info(this.value); // got 'test';
  }
}
```
-------------------------------it also does work
```
@Component 
class A extends Vue {
  @Model() value:string;
   ...
  mounted(){
    console.info(this.value); // got 'test';
  }
}
```
-------------------------------

**Comment by ktsn** [comment]
Please provide minimal/self-contained reproduction by JSFiddle, example github repo or so on when reporting a bug.

**Comment by nailfar** [comment]
I have resolve the problem after I coding in jsFiddle. 
babel-plugin-jsx-v-model  only surport `value` and `input`  it's not vue-class-component's bug;
