### ISSUE TITLE
builded error with nested component

### ISSUE THREAD

**Issue by ZenLiuCN** [vuejs/vue-class-component#267]
### Reproduction link

[https://codesandbox.io/s/oxp1oy83q?module=%2Fsrc%2FApp.vue](https://codesandbox.io/s/oxp1oy83q?module=%2Fsrc%2FApp.vue)

### Steps to reproduce

![bug.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b8c6c840-b1cc-11e8-800e-579f93a44685.png)

### What is expected ?

![shouldbe.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f2639f60-b1cc-11e8-800e-579f93a44685.png)

### What is actually happening?

when build static files ,missing nested componet

### Additional comments?

only  when build file in `dist` ,in dev mode is fine

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7695">#c7695</a>)</em></sub></div>

**Comment by ZenLiuCN** [comment]
checked nothing about Nuxt, found may this repo cause it ,will you help to sole it?

**Comment by ZenLiuCN** [comment]
Found must add 
```js
@Component({name:'Tree'})
``` 
then everything is fine

**Comment by sodatea** [comment]
https://vuejs.org/v2/guide/components-edge-cases.html#Recursive-Components
