### ISSUE TITLE
Is `el` property defining available?

### ISSUE THREAD

**Issue by TokugawaTakesi** [vuejs/vue-class-component#268]
Thank you for the library.

 Unfortunately I did not find examples how to define `el` property. How can I rewrite the below code with your library?

```
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```

**Comment by ktsn** [comment]
Thanks for filing the issue. However your issue is a usage question.
For questions and support please use the [the official forum](http://forum.vuejs.org) or [community chat](https://chat.vuejs.org/). The issue list of this repo is **exclusively** for bug reports and feature requests.

**Comment by Taytay** [comment]
Answered here: https://forum.vuejs.org/t/is-el-property-defining-available-in-typescript-vue-property-decorator/42969/5
