### ISSUE TITLE
Parameter 'to' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by wenkanglin** [vuejs/vue-class-component#270]
Maybe it's not a bug...

```js
import Vue from 'vue';
import Component from 'vue-class-component';

@Component
export default class AutoPagination extends Vue {

  beforeRouteEnter(to, from, next) {
    // ...
  }
}
```

When I use vue-router `beforeRouteEnter` hook, TypeScript error with:

```
Parameter 'to' implicitly has an 'any' type.
Parameter 'from' implicitly has an 'any' type.
Parameter 'next' implicitly has an 'any' type.
```

#### Reproduce

1. Use vue-cli to create a ts project includes vue-router.
2. Install package `vue-class-component`.
3. Register custom hooks for vue-router. I'm sure it's before importing any components.
4. Use vue-router hooks at any .vue single file.

Now because this error, I have to close `noImplictAny` rule, but I want to keep this rule. Is there any way to solve this problem?

**Comment by wenkanglin** [comment]
@kaorun343 

Is there a way to provide built-in support for these hooks? 
The purpose of the issue is to confirm whether it is my problem or a known trouble here.

Below is my current solution:

```ts
// component.d.ts
import { NavigationGuard } from 'vue-router';

interface RouteComponent {
  beforeRouteEnter?: NavigationGuard;
  beforeRouteUpdate?: NavigationGuard;
  beforeRouteLeave?: NavigationGuard;
  [key: string]: any;
}
```

```ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { RouteComponent } from '@/types/component'

@Component
export default class AutoPagination extends Vue implements RouteComponent {

  beforeRouteEnter(to, from, next) {
    // ...
  }
}
```

I don't know if there are other more effective solutions?

**Comment by HerringtonDarkholme** [comment]
Sadly this isn't possible for TypeScript. See details in https://github.com/Microsoft/TypeScript/pull/6118

**Comment by wenkanglin** [comment]
Oh okay :cry:
Thank you for reply.
