### ISSUE TITLE
i have some question about this value 

### ISSUE THREAD

**Issue by llfylwg** [vuejs/vue-class-component#271]
export default class App extends Vue {
   arr: any[] = []
  created() {
  console.log(this)   //  （1）
}
    obj: any = {
          name: '111',
          onchange() {
              this.arr = [123];  //（2）
           }
     }
} 
if i want this in (1) is equal to  this in (2), what should i do？
I try some solutions, but they are not reactive

please answer, thank you

**Comment by ktsn** [comment]
For questions and support please use the [the official forum](http://forum.vuejs.org) or [community chat](https://chat.vuejs.org/). The issue list of this repo is **exclusively** for bug reports and feature requests. Thanks!
