### ISSUE TITLE
"webpack": "^4.19.1" the demo can 't be launched

### ISSUE THREAD

**Issue by dashng** [vuejs/vue-class-component#272]
I upgrade the webpack to 4.19.1, the demo can't be lanuched.

Any suggestions, Thanks.

**Comment by ktsn** [comment]
How the error message was?
What do you mean of "can't be launched"? Was it compilation error or runtime error?

**Comment by ktsn** [comment]
Closing until more information is provided as currently we cannot do any action for this as lack of information.
