### ISSUE TITLE
Computed properties (getters) do not work with arrow functions

### ISSUE THREAD

**Issue by andreixk** [vuejs/vue-class-component#273]
This (cleaner) getter does not work

```
@Component
export default class extends Vue {
   get currentYear = () => (new Date()).getFullYear()
}

```

However, this code works (as expected):
```
@Component
export default class extends Vue {
   get currentYear () {
       return (new Date()).getFullYear()
    }
   thisYear = () => (new Date()).getFullYear()
}
```
Is it impossible to use arrow functions with getters or is it a bug?

**Comment by kaorun343** [comment]
@andreixk 

Hi.

It's impossible to use arrow functions with `get` keyword.
Your issue isn't related to this library directly.
