### ISSUE TITLE
Cant use vue-class-component as external library in typescript

### ISSUE THREAD

**Issue by seand88** [vuejs/vue-class-component#276]
trying to use vue-class-component for a multi page application with typescript
i can get vue to work by adding vue to the .html file and using declare var Vue: any; in my typescript file
but when i try to use vue-class-component like that it doesnt work

```
declare var Vue: any;
declare var Component: any;

@Component({
    template: '<button @click="onClick">Click!</button>'
})
export default class Ticket extends Vue {
    // Initial data can be declared as instance properties
    message: string = 'Hello!'

    // Component methods can be declared as instance methods
    onClick (): void {
        window.alert(this.message)
    }
}
```

says component does not exist

**Comment by ktsn** [comment]
`Component` decorator is at `VueClassComponent.default` if you are using umd build.

Please consider to use [our forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) for usage questions. The issue tracker is exclusively for bug reports and feature requests. Thanks.
