### ISSUE TITLE
function in data didn't work as expected ?

### ISSUE THREAD

**Issue by Weiyu-Chen** [vuejs/vue-class-component#279]
Here is jsfiddle: [https://jsfiddle.net/chenweiyu/jyb0gc8a/](https://jsfiddle.net/chenweiyu/jyb0gc8a/)
```
@Component({
  template: `
  <div>
    <span>click  --></span><h1 @click="handleClick">{{ message }}</h1>
    </div>
  `
})
class App extends Vue {
  message = 'Hello!'
  obj = {
     msg: 'hello'
  }
  rules = {
     validator: ()=>{
       console.log('"this" in data, "this.obj.msg" changed, but "this.message" didn\'t change ' , this)
     }
  }
     
  handleClick(){
   this.message = 'world'
   this.obj.msg = 'world'
   console.log('"this" in method work as expected: ' , this)
   
   this.rules.validator()
  }
}
```

**It seems to be becase `this` in data is type `App` while `this` in method is type `VueComponent`**  ?

![image](https://user-images.githubusercontent.com/13402013/46656928-b637f200-cbe1-11e8-9bd4-2e5b38f796b2.png)

**Comment by ktsn** [comment]
You shouldn't use arrow function in property initializers. Please use just methods instead. This is a won't fix until the next decorator proposal will be shipped.
https://github.com/vuejs/vue-class-component#this-value-in-property
