### ISSUE TITLE
[Regression] ReferenceError: Can't find variable: Reflect

### ISSUE THREAD

**Issue by sodatea** [vuejs/vue-class-component#283]
See https://github.com/vuejs/vue-cli/issues/2733 for reproduction.
This regression is introduced in https://github.com/vuejs/vue-class-component/commit/d570fa374195eeaa1e7e565ea34bb165104ff358#diff-5bb099174f678e4d728de8e607013b3aR5

The correct way to detect Reflect support should be:
```js
return typeof Reflect !== 'undefined' && Reflect.defineMetadata
```

**Comment by ktsn** [comment]
Thanks! Fixed via v6.3.1.
