### ISSUE TITLE
`createDecorator` not working properly in inheritance scenarios

### ISSUE THREAD

**Issue by xman85** [vuejs/vue-class-component#287]
Hi!

In inheritance scenarios decorators set on a derived class component will leak to all sibling classes:

- say you have a base class component X and 2 derived class components Y and Z;
- you decorate X with something which sets `CtorX.__decorators__` to an array
- then you decorate something in Y, it will already have `CtorY.__decorators__` set, coming from the prototype, i.e. `CtorX.__decorators__ === CtorY.__decorators__`
- as a result everything that inherits from X - both Y and Z will have a decorator that was intended only for Y.

So, I suggest adding this to `createDecorator`:

```javascript
else if (!Ctor.hasOwnProperty('__decorators__')) {
            Ctor.__decorators__ = Array.from(Ctor.__decorators__);
        }
```

This way `__decorators__` in base class and derived classes will be different array instances (keeping inherited decorators with `Array.from`).

Full code will look like this:

```javascript
function createDecorator(factory) {
    return function (target, key, index) {
        var Ctor = typeof target === 'function'
            ? target
            : target.constructor;
        if (!Ctor.__decorators__) {
            Ctor.__decorators__ = [];
        } else if (!Ctor.hasOwnProperty('__decorators__')) {
            Ctor.__decorators__ = Array.from(Ctor.__decorators__);
        }
        if (typeof index !== 'number') {
            index = undefined;
        }
        Ctor.__decorators__.push(function (options) { return factory(options, key, index); });
    };
}
```

**Comment by ktsn** [comment]
Could you provide a self-contained reproduction for that? I couldn't reproduce it on my side...

**Comment by Gidmark** [comment]
The suggestion fixed the issue for me. I have an abstract class with a @watch decorator on a property. I got this in one of my components extending that class, loading with systemjs.
`Uncaught (in promise) Error: Cannot read property 'call' of undefined
  Evaluating http://localhost:58846/myapp.js
  Loading myapp.js
    at VueComponent.Vue.$watch (vue.js:3609)
    at createWatcher (vue.js:3567)
    at initWatch (vue.js:3549)
    at initState (vue.js:3315)
    at VueComponent.Vue._init (vue.js:4615)
    at new MyComponent (vue.js:4785)
    at createComponentInstanceForVnode (vue.js:4304)
    at init (vue.js:4125)
    at createComponent (vue.js:5595)
    at createElm (vue.js:5542)`

using
` "vue": "~2.5.17",
  "vue-class-component": "~6.3.2"`

**Comment by ktsn** [comment]
I think the case to which OP points cannot be happened because the `@Component` decorator clean up the decorator array after processing it. https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L73
I suspect the inherited class does not decorated by `@Component` decorator which is the case we don't support.

If it is not the case please open a new issue with a proper reproduction. Thanks.
