### ISSUE TITLE
Using the decorator on a class with a static file

### ISSUE THREAD

**Issue by eddow** [vuejs/vue-class-component#296]
When declaring a static function in the class being decorated by `Component` a typescript error (might) occur.
The problem and the solution are here : https://github.com/Microsoft/TypeScript/issues/23704

Note: The problem occurs on some computers and not others, it must depend on some global stuff. Though, the static function is available even after going through the `Component` decorator as it is working on some installations.

**Comment by eddow** [comment]
Well, it is tough for me to do so because that bug does not occur on my system :">
Though, to give you something minimal to reproduce :
```typescript
@Component
class myControl extends Vue {
    static someMethod(blah) { ... }
}
```
The error occuring is exactly the one described in he link I gave;
If I apply the example given in the issue/solution link I gave, this would change the declaration of `componentFactory` like this :
```typescript
export function componentFactory<T extends VueClass<Vue>> (
  Component: T,
  options: ComponentOptions<Vue> = {}
): T {
```

Of course, the signature of the `Component` decorator would change along

**Comment by ktsn** [comment]
Hmm, we cannot do anything without proper reproduction...
Could you boil down the problem to clarify what the root cause is?

> The error occuring

What the error message, by the way?

**Comment by eddow** [comment]
This is what has been given to me :
![bug](https://user-images.githubusercontent.com/27567959/49735072-ca34ba00-fc4b-11e8-98f7-dff138b6179d.png)

I tried to make a reproduction in https://github.com/eddow/eddow-bug-expo in the branch `vcc+static` - unfortunately, as I told you, it compiles just fine for me. (I did add some more complexity like I have in my project just to make it more likely to reproduce)

**Comment by ktsn** [comment]
This is probably the same problem with #294. Please upgrade Vue to v2.5.20.

**Comment by eddow** [comment]
Well, because of the unreproductible(?) nature of the problem, I think about nothing but to close the bug - I personally dodged the question by removing the static function from my library so it's indeed not really a problem even for me.

Just passin' by - sorry to have bothered.
