### ISSUE TITLE
How are types added to registered hook?

### ISSUE THREAD

**Issue by ksnyde** [vuejs/vue-class-component#297]
I am trying to use NUXT with Typescript and really want the class based syntax this module provides but when I looked into the `nuxt-class-components` modules I saw they were mainly just adding lifecycle hooks via your `registerHooks` but then I'm not getting any type information from those hooks which is a shame.

I think it would be nice to state in the documentation how one can achieve this.

**Comment by ktsn** [comment]
You can extend Vue instance method by using module augmentation technique. https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

But I'm not sure we should state it in docs since the methods are not actually in the Vue instance.
