### ISSUE TITLE
Importing Vue component via NPM package causes Typescript error

### ISSUE THREAD

**Issue by dkln** [vuejs/vue-class-component#300]
Not sure if this is the right place (because it might be related to the `ts-loader` package), but here goes:

I have a NPM package that contains several Vue components. When I switch to lang `ts` in a component, the TS compiler spits out the following error:

```
TS2345: Argument of type '{ components: { Button: typeof default; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?
```

Here is a small testcase:

*Main project:*

```js
<template>
  <div>
    <Button />
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import Button from "shared-components/Button.vue";

@Component({
  components: { Button }
})
export default class extends Vue {
};
</script>
```

*Shared component in NPM package: shared-components/Button.vue* 

```js
<template>
  <button class="btn btn--block">{{ label }}</button>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";

@Component({
  components: { Button }
})
export default class extends Vue {
  @Prop() label!: string
};
</script>

```

This error only seems to occur when the component itself is placed in a Node package. It works fine when I copy-paste the component to the main project.

Quick-fix is to just ignore the error on the line `@Component` in the main project but that kind of defeats the purpose of Typescript 😄 

Any thoughts?

**Comment by dkln** [comment]
Seems to be related to https://github.com/vuejs/vue-loader/issues/1281
What seems to work:

_Button.vue_

```js
<template>
  <button class="btn btn--block">{{ label }}</button>
</template>
```

_Button.ts_

```js
<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";

@Component({
  components: { Button }
})
export default class extends Vue {
  @Prop() label!: string
};
</script>
```

**Comment by ktsn** [comment]
Please provide a minimal / self-contained reproduction (e.g. example GitHub repo) to confirm the issue.

**Comment by MrDarkSkil** [comment]
Same here, cannot use Buefy component when i use `vue-property-decorator`

**Comment by ktsn** [comment]
Closing until reproduction is provided.

**Comment by gdpaulmil** [comment]
tf?...
reproduction?
just try to import a component in the  components array...
![image](https://user-images.githubusercontent.com/5796086/59222229-4b541600-8bc9-11e9-9ac2-96669f27ae63.png)

fk is this error?

**Comment by towry** [comment]
https://github.com/vuejs/vue-class-component/issues/123#issuecomment-315608700
