### ISSUE TITLE
Can't access _uid in constrcutor

### ISSUE THREAD

**Issue by NE-SmallTown** [vuejs/vue-class-component#303]
## Version
vue: 2.5.22
vue-class-component: 6.3.2

## Reproduction link
https://jsfiddle.net/heaven_xz/uLy6rpwx/

## Steps to reproduce
open chrome devtools and see the console

## What is expected?
I can access the `_uid`

## What is actually happening?
I can't access the `_uid` in the component constructor if I use the decorator of vue-class-component, but without the decorator, I can access the `_uid`

### ------------------------- update  --------------------------

Seems like I can't access any fields which has been inited in the Vue constructor if I use decorator(see https://jsfiddle.net/heaven_xz/uLy6rpwx/3/), but I don't know why I can access `$root`

**Comment by NE-SmallTown** [comment]
Could anyone have time to look at this?

**Comment by kaorun343** [comment]
@NE-SmallTown 

Hi.

In the constructer with the `@Component` decorator, `this` is not an instance of `Vue` due to the technical reason, so `_uid` is not available.

Also, `_uid` is private, not documented, so maybe it's better I think to generate a unique id by your self.

**Comment by NE-SmallTown** [comment]
Could you tell me more details about what technical reason?

> Also, _uid is private, not documented, so maybe it's better I think to generate a unique id by yourself.

Yea, but a library maybe depend on this, on the other hand, decorator should not change the origin behavior if I understand correctly

**Comment by kaorun343** [comment]
The role of `@Component` is to create a component option from a class. So as to do this, the decorator collect the properties and methods which defined by users. This feature is related to the issue you mentioned.

It's available to pass a component option to `@Component` decorator directly , so inside of `data` function of the argument, you're able to use `this._uid`.

**Comment by ktsn** [comment]
You always should not use private properties as @kaorun343 said.
And you can easily implement such feature as Vue plugin.

```js
let uid = 0

Vue.mixin({
  beforeCreate() {
    this.$uid = ++uid
  }
})
```

**Comment by hanshou101** [comment]
@kaorun343 
Oh,sir thank you very much !!!

I try to read data from father-mixins ,  in constructor() . 

And console  always show TypeError: Cannot read property 'xxx' from undefined.

Your answer helped me , because  【this】  is another reference in   constructor()  .

This is the most important info for me .

Now I move my  read-data-method to  beforeCreate() , it works so well !
