### ISSUE TITLE
Render function responsive problem

### ISSUE THREAD

**Issue by wenkanglin** [vuejs/vue-class-component#304]
### Version

- vue: 2.5.22
- vue-class-component: 6.3.2
- vue-property-decorator: 7.3.0

### Reproduction link

https://github.com/wenkanglin/render-repo

### Steps to reproduce

1. git clone repo link
2. npm install
3. npm run serve

### What is expected?

The `TSRender` and `JSRender` component will be responsive to update value

### What is actually happening?

The `JSRender` component work normal, but the `TSRender` component can't work well

**Comment by kaorun343** [comment]
@wenkanglin 

Hi.

How about using the other function name instead of `render`? 

From README.md
> data, render and all Vue lifecycle hooks can be directly declared as class member methods as well, but you cannot invoke them on the instance itself. When declaring custom methods, you should avoid these reserved names.

**Comment by wenkanglin** [comment]
@kaorun343 I had named it as `renderFn` instead of `render`, but still has this problem.

https://github.com/wenkanglin/render-repo/commit/f8f88b79aee8045ceef737440afc13d8c90329de

**Comment by wenkanglin** [comment]
@kaorun343 nice answer !!!

thx and closed
