### ISSUE TITLE
Custom decorators and data keys duplication

### ISSUE THREAD

**Issue by mrTimofey** [vuejs/vue-class-component#306]
I am trying to define custom decorator which creates a computed property from a component class variable. As an example: I'd like to map some property to a specific `$route.query` item without creating a boilerplate get/set pairs every time I need them. Something like this:

```js
@Component
class MyComponent {
  @MapRouteQuery({ type: Number, default: 1 })
  page!: number
}
```

The problem is that `collectDataFromConstructor` will create a duplicate `vm.data` entry for any custom computed property created by a decorator. Only `prop` keys are omitted.

I guess this issue could be a feature request but may be I miss something and there is a way to avoid data/computed keys duplication.

**Comment by ktsn** [comment]
Are you sure that the code example is an actual code? It should not collect the properties as data if you declare it 1) without initializer and 2) in TypeScript.

In any cases, minimal and runnable reproduction is useful to confirm.

**Comment by mrTimofey** [comment]
My bad, I've tried to apply decorator to initialized property. Works like a charm without initial value. Thank you and sorry for wasting your time :(
