### ISSUE TITLE
call child class methods from mixin

### ISSUE THREAD

**Issue by NarHakobyan** [vuejs/vue-class-component#307]
There is not any way to call component methods from Mixin, can you please implement it? 🥇

**Comment by ktsn** [comment]
That's impossible as mixin does not know about any child component. It also is a code smell because super class should not rely on child class in general.

**Comment by hanshou101** [comment]
@NarHakobyan 
Hi , sir .  
I tried many times , and finally find a relatively and clear way , to call Comp-Method from mixin.

But there is no time for me to write a blob right now .

If you're interested in it ,plz tag me or message me .

**Comment by mukeshghodela-easternts** [comment]
@hanshou101 Can you please share code here?

**Comment by NarHakobyan** [comment]
@mukeshghodela-easternts don't do that :D, don't call any function outside of mixin, it's not a working form of mixin
