### ISSUE TITLE
Custom decorator for hooks

### ISSUE THREAD

**Issue by mailok** [vuejs/vue-class-component#308]
I would like to be able to execute a function when a hook is executed, Is this possible by creating a custom decorator?

For example, this function will be executed when the component executes the hook **destroyed**

```
    @Destroyed()
    cleanSometTing() {
      // my logic
    }
```

If this can not be done today, I would like to propose it, I think it would make my code more readable

**Comment by ktsn** [comment]
You can modify the lifecycle hook in custom decorator.

```js
const noop = () => {}

const Destroyed = createDecorator((options, key) => {
  const original = options.destroyed || noop
  const method = options.methods[key] || noop

  options.destroyed = function() {
    original.call(this)
    method.call(this)
  }
})
```

Please consider to ask your questions in [forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) if you are not sure it's possible or not before opening feature request.
