### ISSUE TITLE
Is "@component" necessary for any situation ?

### ISSUE THREAD

**Issue by NissanYeah** [vuejs/vue-class-component#315]
Is "@Component" necessary for any situation even I don't need  to use any component?

I know we can use @componet  to register component , like this

```
@Component({
  components: {
    mycomponent1,
    mycomponent2,
  },
})
```
but what if  I don't need  to use any component?  should I still write @component?

In my case , when I remove @component, my component (it names "ToggleIcon") will render outside. But it should be inside of other component actually.

```
import { Vue, Component, Watch,
} from 'vue-property-decorator';

@Component
export default class ToggleIcon extends Vue {
}
```

![2019-02-26 11 06 59](https://user-images.githubusercontent.com/34571901/53422897-4d7bd580-3a1b-11e9-84c1-abb19c3e082c.png)

so now I am confused about the @Component  and want to know what's the purpose of "@Component " QQ

**Comment by ktsn** [comment]
Yes, it's needed for technical reason. The decorator converts your class to actual Vue constructor under the hood.
FYI: we will not need it after Vue 3.0 supports class style syntax.
