### ISSUE TITLE
Can I access 'this' in custom method Decorator with createDecorator()?

### ISSUE THREAD

**Issue by hanwong** [vuejs/vue-class-component#317]
Can I access 'this' in custom method Decorator with createDecorator()?

like the method decorator example
```ts
function Test(target: any, propertyKey: string, descriptor: PropertyDescriptor) {
    descriptor.value = function(...args: []) {
        console.log(this);
    };
}
```

**Comment by ktsn** [comment]
Please use [forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) to ask usage questions as the issue list is dedicated for bug reports and feature requests. Thanks.
