### ISSUE TITLE
Do you have plans to implement vue-async-computed functionality in get attributes?

### ISSUE THREAD

**Issue by atxy2k** [vuejs/vue-class-component#320]
When I was writing code in vanilla js, I used this library a lot:

[https://github.com/foxbenjaminfox/vue-async-computed](https://github.com/foxbenjaminfox/vue-async-computed)

I loved it, this library give me the functionality of have computed properties, but asyncronus, do you have plans of implement something like this in getters attributes?

**Comment by ktsn** [comment]
We would keep vue-class-component as small as possible that only having class-style alternative of Vue core lib. So no, sorry.
You can implement such functionality as custom decorator by using `createDecorator` though.
