### ISSUE TITLE
Error Object Literal 'watch' in @Component

### ISSUE THREAD

**Issue by ileonardo-c** [vuejs/vue-class-component#322]
I'd like to avoid two problems with **Eslint**:

- class-methods-use-this
- func-names

I have the following code:

```javascript
// vue-property-decorator

@Watch('styles.height')
private onHeight(val: string) {
  // import Vue.observable
  mutations.setApp({ top: val });
}
```

in this situation I should by function `private static` but for `Vue`, show error. So I should write inside the `@Component`, this way:

```javascript
@Component({
  watch: {
    'styles.height': function (val: string) {
      // import Vue.observable
      mutations.setApp({ top: val });
    },
  },
})
```

But here **Eslint** does not accept this function writing format. So I wanted to write as shown in the `@Watch` example:

```javascript
@Component({
  watch: {
    'styles.height': [
      {
        handler: 'onHeight',
        immediate: false,
        deep: false,
      },
    ],
  },

  methods: {
    onHeight(val: string) {
      // import Vue.observable
      mutations.setApp({ top: val });
    },
  },
})
```

But that's where that error occurs:

`Object literal may only specify known properties, and 'watch' does not exist in type 'VueClass<Vue>'.`

**Comment by ktsn** [comment]
Please use [forum](https://forum.vuejs.org), [discord](https://forum.vuejs.org) or StackOverflow to ask questions. Issue tracker is for feature requests and bug reports exclusively. Thanks.
