### ISSUE TITLE
Support for async components

### ISSUE THREAD

**Issue by mtatarau90** [vuejs/vue-class-component#323]
Hi, guys 

I try to lasy load some components, and work fine if i use the classic way with "'my-component': () => import('./my-async-component')", but i want try to create a factory object like in vue documentation

`const AsyncComponent = () => ({
  // The component to load (should be a Promise)
  component: import('./MyComponent.vue'),
  // A component to use while the async component is loading
  loading: LoadingComponent,
  // A component to use if the load fails
  error: ErrorComponent,
  // Delay before showing the loading component. Default: 200ms.
  delay: 200,
  // The error component will be displayed if a timeout is
  // provided and exceeded. Default: Infinity.
  timeout: 3000
})`

`@Component({
  components: {
    AsyncComponent
  }
})
class App extends Vue {}`

But it gave me an error " Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?".

Now my question is, i do something wrong? or vue-class-component do not support this feature?

**Comment by ktsn** [comment]
Please provide a self-contained reproduction, thanks!

**Comment by exodusanto** [comment]
Hi @ktsn I have the same error

Form.vue
```ts
@Component({
  components: {
    Btn,
    InputText,
  },
})
export default class Form extends Vue {
```
index.ts

```ts
export const Btn = () => import('./Btn.vue');
export const InputText = () => ({
  component: import('./Input/InputText.vue'),
  delay: 0,
  loading: InputPlaceholder,
});
```

Error
```
Argument of type '{ components: { Btn: Component<DefaultData<never>, DefaultMethods<never>, DefaultC...' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?
```

**Comment by exodusanto** [comment]
I try to set component type to `any`and it works
```
export const InputText = () => ({
  component: import('./Input/InputText.vue') as any,
  delay: 0,
  loading: InputPlaceholder,
});
```

**Comment by ktsn** [comment]
Thanks for the info but that is not a reproduction. Reproductions should be executable and able to confirm the problem comprehensively. You can use [jsfiddle](https://jsfiddle.net/ktsn/nm55jnjk/), GitHub repo etc to make it.

**Comment by ktsn** [comment]
Closing until reproduction is provided. Please open a new issue if the problem persists and anyone can provide a reproduction. Thank you.

**Comment by Lstoryc** [comment]
same issue. Is there any news?

**Comment by hckhanh** [comment]
I have the same issue. I cannot use it with typescript

**Comment by paolog22** [comment]
same here
![image](https://user-images.githubusercontent.com/12680745/81139272-c370ba80-8f97-11ea-8891-ecbebb7381e0.png)

**Comment by mtatarau90** [comment]
Hi guys, i let you here a workaround
`const myComponent = () => ({
  component: import('.....'),
  loading: LoadingComponent,
}) as any;`

**Comment by paolog22** [comment]
Hi @mtatarau90 thank you but is there a way without casting it to 'any' ?

**Comment by mtatarau90** [comment]
Hi @paolog22,

this was the only way that works form me but was one years ago, I didn't try another approach.

**Comment by paolog22** [comment]
@mtatarau90  thanks for the reply.

**Comment by saint777** [comment]
```
import { AsyncComponentFactory } from 'vue/types';

const Modal: AsyncComponentFactory = () => ({ /* some modal component that should be lazy loaded */
  component: import('@/components/modal'),
});
```

try this one boys
