### ISSUE TITLE
compute a property object in typescript

### ISSUE THREAD

**Issue by ourfamilygithub** [vuejs/vue-class-component#326]
@Component
export default class Index extends Vue {

    items: Array<Object> = [
        {
            title: 'My first title',
            status: 'In Progress'
        },
        {
            title: 'My second title',
            status: 'Launched'
        }
    ]

    get status(index: number) { 
        
        // 1. i can not pass parameter to get function to access this.items[index]
        // how can i compute status property here???

        return this.items[index].status.trim().toLowerCase().replace(' ', '-')
    
    }
}

**Comment by ktsn** [comment]
Computed properties does not have argument. Use method instead.

Please use [forum](https://forum.vuejs.org) or [discord](https://chat.vuejs.org) to ask questions in the next time as issue tracker is dedicated for feature requests and bug reports.
