### ISSUE TITLE
Support for augmented types?

### ISSUE THREAD

**Issue by Renari** [vuejs/vue-class-component#327]
Does `vue-class-component` support augmented types?

For example https://www.npmjs.com/package/vue-socket.io augments the vue class by adding sockets. However when trying to access said `sockets` element like so:
```js
@Component({})
export default class extends Vue {
  sockets = {
    connected() {},
  };
}
```
This gets treated as a data object.

**Comment by ktsn** [comment]
You can do that by augmenting vue core types.
https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
