### ISSUE TITLE
registering beforeRouteEnter hooks on component class

### ISSUE THREAD

**Issue by apanchati** [vuejs/vue-class-component#335]
I am trying to register beforeRouteEnter hook on component.

I have created js file called "class-component-hooks.js" and add import on first line in app.js and in Pages/Authentication.vue i created "beforeRouteEnter" method, however it's not getting called.

I am using below version with TypeScript:
"vue": "2.6.10",
"vue-class-component": "7.1.0",
"vue-property-decorator": "8.1.1",
"vue-router": "3.0.2"

//class-component-hooks.js file
`import Component from 'vue-class-component'

// before you will make any import
Component.registerHooks([
  'beforeRouteEnter',
  'beforeRouteLeave',
  'beforeRouteUpdate', // for vue-router 2.2+
]);`

//app.js
`import './class-component-hooks'

import Vue from 'vue'
import Authentication from './Pages/Authentication'
import router from './Router/NavigationGuards'

// remove warning message on console tab in developer tools "You are running Vue in development mode..."
Vue.config.productionTip = false

const app = new Vue({
  router,
  render: h => h(Authentication)
})

export { app, router }`

code to reproduce: [https://github.com/apanchati/register-hook](https://github.com/apanchati/register-hook)

Thanks,

**Comment by kaorun343** [comment]
It seems it's related to your issue that you import some components asynchronously.

How about importing `class-component-hooks.ts` at the components that imported asynchronously?

**Comment by apanchati** [comment]
I tested and didn't work.

**Comment by apanchati** [comment]
When i step into the code i noticed both created and beforeRouteEnter are found in the hook if statement.

// Code from vue-class-component.js file:
function componentFactory(Component, options) {
    if (options === void 0) { options = {}; }
    options.name = options.name || Component._componentTag || Component.name;
    // prototype props.
    var proto = Component.prototype;
    Object.getOwnPropertyNames(proto).forEach(function (key) {
        if (key === 'constructor') {
            return;
        }
        // hooks
        if ($internalHooks.indexOf(key) > -1) {
            options[key] = proto[key];
            return;
        }

**Comment by ktsn** [comment]
Because you don't use `router-view` to show your component...
Router hooks only work if the component is shown by router.

**Comment by mediafreakch** [comment]
> Because you don't use router-view to show your component...
Router hooks only work if the component is shown by router.

Mind that the lifecycle hooks won't work for children of components rendered by the router neither.
