### ISSUE TITLE
Property 'options' does not exist on type 'VueConstructor<Vue>'.ts(2339)

### ISSUE THREAD

**Issue by praveenpuglia** [vuejs/vue-class-component#337]
I am trying to write a component and export a plugin that installs that component globally but getting this error.

```
Property 'options' does not exist on type 'VueConstructor<Vue>'.ts(2339)
```
My component doesn't have anything special. Here's the plugin code.

```ts
import BCopy from './BCopy.vue';
import { VueConstructor } from 'vue';

const BCopyPlugin = {
  install(Vue: VueConstructor) {
    Vue.component(BCopy.options.name, BCopy);
  }
};
export default BCopy;
export { BCopyPlugin, BCopy };
```

## More context coming from:
https://github.com/vuejs/vue-cli/issues/4065

**Comment by ktsn** [comment]
`options` is currently undocumented API so we don't declare it as TypeScript typings.
You need to annotate your component with `any`.

`(Bcopy as any).options.name`

**Comment by praveenpuglia** [comment]
Yeah. that's how I was getting it to work. Thought I may have done something stupid to not get the typing correct. 

Thanks for clarification 👍
