### ISSUE TITLE
TS2339 when calling class method

### ISSUE THREAD

**Issue by julaudo** [vuejs/vue-class-component#340]
I'm using vue-cli-service to build my vuejs application.
In my Jest test, I get the component instance, but can't call methods on that instance:

**Test.vue**
```
<template>
    <div>{{method()}}</div>
</template>

<script lang="ts">
    import { Component, Vue } from 'vue-property-decorator';

    @Component
    export default class Test extends Vue {
        public method(): string {
            return 'hello';
        }
    }
</script>
```

**Test.spec.ts**
```
import 'jest';
import {mount} from '@vue/test-utils';
import Test from '@/views/common/Test.vue';

describe('Test.vue', () => {
    let wrapper: any;

    beforeEach(() => {
        wrapper = mount(Test);
    });

    test('test method call', () => {
        const test = wrapper.find(Test).vm as Test;
        expect(test.method()).toEqual('hello');
    });
});
```

In Test.spec.ts, I get this error, both in editor and in typescript window:

> Error:(14, 21) TS2339: Property 'method' does not exist on type 'Vue'.

But the test is OK, so test.method() is resolved successfully at runtime.

**Comment by ktsn** [comment]
This is technically not related with vue-class-component.
If you have `vue-shim.d.ts` and declare `*.vue` file type in it, all your Vue component from `*.vue` file will be `Vue` type. Annotate the instance to `any` would solve the problem.

**Comment by julaudo** [comment]
So, there is no way to have a fully typed instance, like if it were not a Vue instance?

**Comment by ktsn** [comment]
Right, unless you intercept vue file resolution like [ts-vue-plugin](https://www.npmjs.com/package/ts-vue-plugin)

**Comment by gforceg** [comment]
> If you have vue-shim.d.ts and declare *.vue file type in it, all your Vue component from *.vue file will be Vue

Does this mean we can get around this with typescript files where the template is defined in the component decorator?

**Comment by gforceg** [comment]
> > If you have vue-shim.d.ts and declare *.vue file type in it, all your Vue component from *.vue file will be Vue
> 
> Does this mean we can get around this with typescript files where the template is defined in the component decorator?

To answer my own question yes! This works but I did have to convert multiple compnents from '.ts' to  '.vue'. Now my vue component code looks a lot like angular and I do not get linting in the template but I'm okay w/ that.

**Comment by chaithanyaMarripati** [comment]
This is such a disaster, people need to move away from and vue and js in general.
GOD!!!
