### ISSUE TITLE
Can not call method of child component which definitely exists

### ISSUE THREAD

**Issue by TokugawaTakesi** [vuejs/vue-class-component#341]
Child component:

```typescript
<script lang="ts">

  import { Vue, Component } from 'vue-property-decorator';

  @Component({})
  export default class Modal extends Vue {

    // ...

    public close(): void {
      this.displayFlag = false;
    }
  }
}
</script>
```

Below code from the parent component is meaningless from the view point of Vue, but valid TypeScript code:

```typescript
private mounted(): void {
  const modal: Modal = new Modal();
  modal.close();
}
```
I got `TS2339: Property 'close' douse not exist not type Vue` error. TypeScript is absolutely right, but what I imported/exported is  `Modal`, the heir of `Vue`.

```typescript
const modal: Modal = new Modal() as Modal;
```

also does not works.

In real project, I want to get Modal via `this.$refs.modal`, but because of above problem I can not call it's `close` method.

**Comment by ktsn** [comment]
Same as #340. 
You may want to use [ts-vue-plugin](https://www.npmjs.com/package/ts-vue-plugin)

**Comment by Djaler** [comment]
ts-vue-plugin doesn't help me.
Now I got this error:
`TS2749: 'TariffServiceEditDialog' refers to a value, but is being used as a type here.`
code fragment:
```
$refs!: {
    editDialog: TariffServiceEditDialog;
    closeDialog: TariffServiceCloseDialog;
};
```
