### ISSUE TITLE
[Question] ES decorators stage-2 support?

### ISSUE THREAD

**Issue by daiyanze** [vuejs/vue-class-component#345]
Vue-class-component is now based on ES decorators stage-1. After reading the [TC39/proposals-decorators](https://github.com/tc39/proposal-decorators), I just realized that the current decorators we are using will probably end in being replaced with "static decorators".

I wonder if it'd be possible for us to use Vue-class-components and Vue-property-decorators (also in Vue3.0) after the proposal's been carried out some day.

**Comment by ktsn** [comment]
We are waiting that TypeScript supports stage-2 decorators. After it's supported we'll update this lib for new decorator proposal.

**Comment by daiyanze** [comment]
@ktsn Thank you very much! Waiting for your good news!
