### ISSUE TITLE
Error when lazy loading a Vue component in a TSX file

### ISSUE THREAD

**Issue by petervmeijgaard** [vuejs/vue-class-component#347]
Good day!

I'm trying to lazy load a custom Vue component in another component that's using a TSX Class syntax, but I keep getting an error stating:
```
ERROR in /Development/vue-lazy-load-tsx-error/src/App.tsx
18:9 JSX element type 'Promise<typeof import("/Development/vue-lazy-load-tsx-error/src/components/hello-world")>' is not a constructor function for JSX elements.
  Type 'Promise<typeof import("/Development/vue-lazy-load-tsx-error/src/components/hello-world")>' is missing the following properties from type 'Element': isRootInsert, isComment
    16 |       <div id="app">
    17 |         /* This will cause a TypeScript error */
  > 18 |         <HelloWorld />
       |         ^
    19 |       </div>
    20 |     );
    21 |   }
```

To reproduce this error, I've created a new repository at [petervmeijgaard/vue-lazy-load-tsx-error](https://github.com/petervmeijgaard/vue-lazy-load-tsx-error). The most important file to look at is the [src/App.tsx](https://github.com/petervmeijgaard/vue-lazy-load-tsx-error/blob/73b860e560f6c11537065bb2519e02bf32ce46e5/src/App.tsx#L17)-file.

I've searched the forums, StackOverflow and GitHub for a possible solution, but without any success. It would be awesome if someone could help me out with this somewhat annoying issue.

**Comment by ktsn** [comment]
Sorry, this is not related to vue-class-component. The problem is because you are not specifying async component type for TSX. To let typescript recognize JSX node type, you need to specify `ElementClass` type but it cannot have multiple type like `Vue | AsyncComponent`. So there seems to be no clean way to do that.

One possible solution would be just cast async component to `any`.

https://www.typescriptlang.org/docs/handbook/jsx.html#class-component

**Comment by petervmeijgaard** [comment]
Hi @ktsn,

Thanks for the quick reply! You were right. By type-hinting the async component to any will cause the error to disappear. I've updated the code to use the workaround [src/App.tsx](https://github.com/petervmeijgaard/vue-lazy-load-tsx-error/blob/c60cdca761fad7e217af05e15cfc225ff649b908/src/App.tsx#L5). I'm still not happy about this solution and now the async components loses it's type safety, but this will suffice for now.

Yet again, thanks for the quick response.

**Comment by mathewcst** [comment]
@petervmeijgaard I've just got the same error, any news on this?

**Comment by petervmeijgaard** [comment]
@mathewcst I wasn't able to fix the problem, unfortunately. I actually dropped the TypeScript support from my application 🙃 

If you find the solution, I would be happy to know how to fix it.

**Comment by boydaihungst** [comment]
Try this one.
```
component: () =>
      import('~/layouts/default.vue').then((m) => m.default || m)
```

**Comment by vertic4l** [comment]
> I actually dropped the TypeScript support from my application 

Haha. Vue is so awesome. not. :D

**Comment by petervmeijgaard** [comment]
> Haha. Vue is so awesome. not. :D

Just because I dropped TypeScript for my application, doesn't mean that Vue is bad. I love creating web applications using Vue and can't wait for Vue 3 to be released. Turned out that I didn't need TypeScript after all. Not only because importing a component doesn't work that well, but also because it would be a bit of overhead for the project and I couldn't find a reason why I should use it.

Vue is still awesome and will become even more awesome when version 3 will be released.

**Comment by vertic4l** [comment]
@petervmeijgaard your comment tells me everything. 

1. You never build a large enterprise platform.
2. You didnt touched the pain points of vue right now.
3. And you seem to be junior or lazy programmer. Otherwise you wouldnt say that Typescript is Overhead.

But hey... Go on and fail. And then have a look at reactjs + tsx

**Comment by petervmeijgaard** [comment]
@vertic4l Dude, no need to be that toxic and judge me like that. By replying like this, you're the one that seems to be a junior developer. A senior developer would help a person out rather than pointing out that the person who requires help is junior or hasn't contributed to building a large enterprise platform 🤷‍♂

**Comment by seanaye** [comment]
Has anyone discovered a fix for this?
