### ISSUE TITLE
[question] Why do we copy data (new Component) into a new plain object?

### ISSUE THREAD

**Issue by CarterLi** [vuejs/vue-class-component#349]
https://github.com/vuejs/vue-class-component/blob/fa148fe3d29cd7a4ccde08a8039383ca99ef1840/src/data.ts#L38

I'm expecting

```ts
  Object.keys(data).forEach(key => {
    if (data[key] === undefined) {
      delete data[key]
    }
  })

  return data;
```

Because [Vue enumerates properties using `Object.keys`](https://github.com/vuejs/vue/blob/33e669b22f69a1f9c9147528360fe0bba85534f0/src/core/instance/state.js#L126), methods on `Component.prototype` won't cause problems ( besides, class methods are initially unenumerable).

Returning data directly has better performance because TypeScript won't generate code for properties that have no initial value, thus `data[key] === undefined` are mostly false.

In addition, returning data directly avoids [this issue](https://github.com/vuejs/vue-class-component#this-value-in-property) since `this === vm.$data // true`

**Comment by ktsn** [comment]
Because Vue.js discourages to have non-plain object in its data.

> In addition, returning data directly avoids this issue since this === vm.$data // true

It does not solve the problem completely. Imagine when you add non-reactive property in `this` later.

**Comment by CarterLi** [comment]
> Because Vue.js discourages to have non-plain object in its data.

But copying is slow.

> It does not solve the problem completely. Imagine when you add non-reactive property in this later.

In this case, you need `Vue.set`

**Comment by ktsn** [comment]
> But copying is slow.

Is it noticeably slow? Do you have any benchmark on it?
I guess there is no significant difference between them as the computational order is the same and the number of instance properties are not so large.

Actually, copying is faster maybe because the former uses `delete` operator.
https://jsperf.com/convert-plain-object

> In this case, you need Vue.set

I don't mean that, imagine this case:

```ts
@Component
class MyApp extends Vue {
  ctx!: CanvasRenderingContext2D

  render = () => {
    this.ctx // You cannot use it here
  }

  created() {
    this.ctx = this.$refs.canvas.getContext('2d')
  }
}
```

`ctx` won't proxy to `$data` in this case and I commonly see this usage in class component.
