### ISSUE TITLE
async await created/mounted

### ISSUE THREAD

**Issue by patie** [vuejs/vue-class-component#351]
hi, its possible do

async await created/mounted? like 
```
async created() {
   // ...
   let response = await api.read(this.$route.params.id);
   // ...
}
```

something like that is possible in pure vuejs without vue class component extension, im also using with typescript, i get error when put async before created() ```async created()```  like ReferenceError: "regeneratorRuntime is not defined"

(vue 2.6)

thank you

**Comment by ktsn** [comment]
Yes you can. Your error `ReferenceError: "regeneratorRuntime is not defined"` is likely from your build configuration such as Babel but vue-class-component.
