### ISSUE TITLE
Significant overhead when using a @Component-based mixin, compared to a plain object mixin

### ISSUE THREAD

**Issue by Anhil-111** [vuejs/vue-class-component#353]
This may not be common but a project I'm currently working on uses global mixins heavily.

I'm currently in the process of gradually introducing Typescript into it, and I noticed that a particular page started spending 10x as much time executing JS during the initial rendering. I narrowed it down to mixins being rewritten using `vue-class-component`, as reverting them did indeed fix the issue.

While I couldn't make a minimal repro with a difference that huge, here's one where using `vue-class-component`-based mixins makes the browser spend 1.5x as much time executing JS as it does with plain-object mixins: https://github.com/Anhil-111/vue-decorator-mixins/commit/e9bcebc57b7fb70b6340d6428f4616bc533b0468

**Comment by ktsn** [comment]
Sorry, we can't modify the code without proper benchmark...

**Comment by ktsn** [comment]
Closing until benchmark is provided as we cannot know which part affects the performance and whether it's actually reasonable to work without it.
