### ISSUE TITLE
es6 type=module (in browser) is supported? (even with es-module-shims?)

### ISSUE THREAD

**Issue by viT-1** [vuejs/vue-class-component#356]
Where can i found docs about configuring this without webpack plugins (with ttypescript compiler using for ts)?
This package have version on cdn without process.env?

**Comment by viT-1** [comment]
I tried importmap with es-module-shims
```
{
	"imports": {
		"vue": ["https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.esm.browser.js"],
		"vue-class-component": ["https://cdn.jsdelivr.net/npm/vue-class-component@7.1.0/dist/vue-class-component.esm.js"]
	}
} 
```
 and have error:
ReferenceError: process is not defined at vue-class-component.esm.js:249

**Comment by viT-1** [comment]
Workaround: add script in template
`window.process = { env: { NODE_ENV: 'production' } };`

**Comment by ktsn** [comment]
We provide `vue-class-component.esm.browser.js` and `vue-class-component.esm.browser.min.js` from v7.2.0
