### ISSUE TITLE
error of default is not a function with systemjs-importmap

### ISSUE THREAD

**Issue by viT-1** [vuejs/vue-class-component#357]
systemjs-importmap.json:
```
{
	"imports": {
		"vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js",
		"vue-class-component": "https://cdn.jsdelivr.net/npm/vue-class-component@7.1.0/dist/vue-class-component.min.js"
	}
} 

```

[Adding vue-class-component decorator](https://github.com/viT-1/systemjs-ts-es6-vue/commit/ffa78019139f8e760898c3669e7667d644654fa5) to my Vue repo caused an error
TypeError: vue_class_component_1.default is not a function

Way to reproduce:
1) npm run deploy
2) npm run www
3) browser loading http://localhost:3000/

**Comment by viT-1** [comment]
related: https://github.com/systemjs/systemjs/issues/1989

**Comment by ktsn** [comment]
This is because the way UMD build exposes the decorator is different with ESModule. Using ESM build should fix the problem.

**Comment by viT-1** [comment]
@ktsn Thank you for new vue-class-component version! Waiting for vue-property-decorator version update (with esm support).
