### ISSUE TITLE
Be able to declare async components

### ISSUE THREAD

**Issue by kierans** [vuejs/vue-class-component#359]
Currently I can declare a component like
```
@Component()
export default class MyComponent extends Vue {

}
```

which is analogous to 

```
Vue.component('my-component', { /* ... */ });
```

However if I wish to create an [Async Component](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components) there is currently no way to declare it.

What I would expect to see (as a new player) is something like

```
@AsyncComponent({
  init: doSomethingThatReturnsAPromise()
})
export default class MyComponent extends Vue {

}
```

or maybe have the init function be a static member on the class (my preference)

```
@AsyncComponent()
export default class MyComponent extends Vue {
  public static defininition(): Promise {
    // return a promise that does some async thing and resolves
  }
}
```

**Comment by LinusBorg** [comment]
Async Components are not a different "type" of component. They are just normal components wrapped in a function that imports them via a dynamic import:

```
const MyAsyncComponent = () => import('./myNormalComponent')
```

So you can't really create an async component like that. you have to create a normal component in its own file and then import it as an async compont by wrapping it in a function.

And it doesn't matter if you use vue-class-component or not.

You can find documentation about this here:  https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components

**Comment by kierans** [comment]
Thanks @LinusBorg for correcting my understanding :)

**Comment by paolog22** [comment]
hi @LinusBorg 
please correct me. is this the same as this
![image](https://user-images.githubusercontent.com/12680745/81139141-480f0900-8f97-11ea-8eb9-39514ec792e8.png)

**Comment by LinusBorg** [comment]
Looks right.

**Comment by paolog22** [comment]
@LinusBorg thanks for the reply. but why is it giving me an type error ? is there other way to implement this kind of async component ? thank you

**Comment by zealotrahl** [comment]
Can I register component from inside the Class? , because I get the component path from props;

**Comment by Viktors-Bolgovs** [comment]
Hi all, any updates? I have a same issue...

**Comment by zealotrahl** [comment]
>  Hi all, any updates? I have a same issue...

I solved using, 
https://github.com/vuejs/composition-api
defineAsyncComponent(() => import(`@/views/${componentPath}.vue`)
