### ISSUE TITLE
Property does not exist on the type in vue-class-component

### ISSUE THREAD

**Issue by wizardnet972** [vuejs/vue-class-component#360]
I created new vue with typescript application using latest @vue/cli (v3).
When I use component decorator from `vue-class-component` with `computed`/`props`/`methods`, I got an error:
```
Property 'count' does not exist on type 'HelloWorld'.Vetur(2339)
```
![image](https://user-images.githubusercontent.com/4997825/64769299-bbb95d00-d553-11e9-8e91-4f91bdd5325e.png)

Here my code:
```
<script lang="ts">
import { Prop, Vue } from "vue-property-decorator";

import Component from "vue-class-component";

@Component({
  computed: {
    count() {
      return 'blabla';
    }
  }
})
export default class HelloWorld extends Vue {
  @Prop() private msg!: string;

  onClick() {
    const y = this.count;
  }
}
</script>
```

But [according to the example](https://github.com/vuejs/vue-class-component/blob/master/example/src/App.vue) it should be working fine. How do I fix this?

**Comment by ktsn** [comment]
This is because decorator cannot change the class instance type. You have to declare the property type by yourself or use some decorator like [vuex-class](https://github.com/ktsn/vuex-class) to map getters on class properties.
