### ISSUE TITLE
add hooks from base class

### ISSUE THREAD

**Issue by abadakhshan** [vuejs/vue-class-component#367]
Consider my component inherits from a base class and that class inherits from `"Vue"`

If base class contains a hook method like` "created"`  this line 

https://github.com/vuejs/vue-class-component/blob/d024dcce0e0f0e25d472177f0d1c5d8d3dd02f6e/src/component.ts#L31

does not consider these hooks.

I think  you should check base classes for hooks and register them.

**Comment by ktsn** [comment]
It should already work. I guess you don't annotate your base class with `@Component` decorator but it's mandatory for all classes in the prototype chain.
