### ISSUE TITLE
Support in Vue 3

### ISSUE THREAD

**Issue by elitastic** [vuejs/vue-class-component#375]
Are there any plans about the future of these decorators in Vue 3? Can I still use them in future?

According to this [article](https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf) the class API draft for Vue 3 has been dropped.

I know about the composition API, but I'm quite a fan of these decorators...

**Comment by ktsn** [comment]
https://github.com/vuejs/vue-class-component/issues/354#issuecomment-518779219
