### ISSUE TITLE
Mixins do not work

### ISSUE THREAD

**Issue by supproduction** [vuejs/vue-class-component#376]
I extended component from mixins, but values is undefined

![image](https://user-images.githubusercontent.com/16482929/69810335-4ffe9c00-11f4-11ea-9c9f-1ac244b2d3af.png)

![image](https://user-images.githubusercontent.com/16482929/69810320-47a66100-11f4-11ea-809f-a4f6b5df3915.png)

**Comment by ktsn** [comment]
Please provide a reproduction to confirm the problem. Thank you.
See this about reproduction: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

**Comment by supproduction** [comment]
Do you docoumentation correct. Is it proper way to implement mixins?
