### ISSUE TITLE
Mark a certain property as unreactive value

### ISSUE THREAD

**Issue by Timmmm** [vuejs/vue-class-component#377]
As far as I know the current solution for non-reactive class members [is](https://github.com/vuejs/vue-class-component/issues/253#issuecomment-394401746):

```
import User from '@/models/user';
import { Component, Prop, Watch, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {

  private user!: User;

  private created(): void {
    this.user = new User();
  }
}
```

This is... ok. I guess. Well actually it kind of sucks. I have to trust Vue that it will call `created()`. Typescript won't warn me if I forget to do `this.user = new User()`, and it's quite verbose.

Would it be possible to add a decorator to do this instead?

```
import User from '@/models/user';
import { Component, Prop, Watch, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {

  @Unreactive
  private user: User = new User();
}
```

(or `@Nonreactive`)

**Comment by ktsn** [comment]
This is almost impossible (too complicated to implement and bring too much caveats in vue-class-component) in the current decorator transpilation implementation. We need to wait TypeScript implements the latest decorator spec.

**Comment by ktsn** [comment]
This will be possible with Vue v3's `markRaw`.
https://composition-api.vuejs.org/api.html#markraw

**Comment by garyo** [comment]
I just discovered that a big three.js 3d scene has been completely "made reactive" by this, because my scene is a data member of my class. And similarly for another 3rd party deep object. Unfortunately I can't declare it `private` because I'm using some mixins that also need the same scene. Is there any other option? Maybe avoid "reacting" data members that start with underscore or something?

**Comment by ktsn** [comment]
Vue 3 is released and `markRaw` is what we want. https://v3.vuejs.org/api/basic-reactivity.html#markraw

**Comment by adnan-wahab** [comment]
is there a markRaw decorator? how can we use the hook from within a class component?
