### ISSUE TITLE
Support VS Code comment region folding

### ISSUE THREAD

**Issue by ricokennedy** [vuejs/vue-class-component#379]
Add comment-based code folding support.  The following code will be foldable in VS Code if it is in a standard .ts file.  However, it will not fold in a .Vue file script section.  If there is something you can do or an alternative, please advise.  This is indispensable for code focus and organization

`  //#region Computed

  get myProp(): Something[] {
    return this.$store.getters.getSomethings;
  }

  //#endregion`

**Comment by ktsn** [comment]
It's not related to vue-class-component...
You should report it to corresponding vscode extension repo (probably Vetur)
