### ISSUE TITLE
v7.2.0 issue: Argument of type 'xxx' is not assignable to parameter of type 'Vue'.

### ISSUE THREAD

**Issue by song52wow** [vuejs/vue-class-component#385]
I upgrade the version to 7.2.0 after, some vue file will report error about: 

Argument of type 'xxx' is not assignable to parameter of type 'Vue'.

or 

Argument of type 'typeof xxx' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof xxx' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'xxx' is not assignable to type 'Vue'.
      Types of property 'data' are incompatible.
        Type 'Ixxx' is not assignable to type '() => object'.
          Type 'Ixxx' provides no match for the signature '(): object'.

as shown below:

![image](https://user-images.githubusercontent.com/22537086/72201715-014e4e00-3492-11ea-81b7-d56005284c7e.png)

**Comment by song52wow** [comment]
I don't know is my code problem? 

And my solution is downgrade to 7.1.0 is ok.

So I hope the upgrade can compatible with old version.

**Comment by matrunchyk** [comment]
Why is this closed? The downgrading is not a solution.
