### ISSUE TITLE
lifecycle types do not work with Mixins

### ISSUE THREAD

**Issue by GauthierPLM** [vuejs/vue-class-component#387]
Following introduction of lifecycle hooks types in #371 and #386, completion works well for classes extending Vue directly but does not work with Mixins:

``` 
import Component, { mixins } from "vue-class-component";
import MyMixin from "@/mixins/myMixin";

@Component()
export default class Index extends mixins(MyMixin) {}
```

With the above code example (and a valid Mixin), completion does not work in the class for lifecycle hooks such as mounted. The result is the same when imported by `vue-property-decorator`.

Tested using WebStorm 2019.3.2 preview, vue-class-component 7.2.1.

**Comment by ktsn** [comment]
Can you provide self-contained reproduction as example GitHub repo?

**Comment by GauthierPLM** [comment]
[Here is](https://github.com/GauthierPLM/vue-class-component-no-completion-mixins) a minimal project where I was able to reproduce the issue ([commit](https://github.com/GauthierPLM/vue-class-component-no-completion-mixins/commit/6d80f81a202b014f719f59943c94bc17279885c6)).

Completion in index, which extends `Vue`, works, but it does not work in HelloWorld component, which extends `Mixins` (or `mixins`).

**Comment by ktsn** [comment]
Looks like TypeScript problem. If we have `private` member in the class, the IntelliSense does not work. It is reproducible without any libs. y/#code/MYGwhgzhAECC0G8BQ1XTAI2NAvNA5PkgL5JKiQwBC0ApgB4AutAdgCYzzJrpa4EB3APYAnANYQipcuCjQAwnSasOcRCjQAHEQEsAbmGbRN-QmR4B6C9BZDG6AK6MhAWmBCAtppC1mbEkA

I'll fix `This dependency was not found:` problem.

**Comment by ktsn** [comment]
The latest dev version of TypeScript seems already fixed this problem.
