### ISSUE TITLE
vue-class-component seems can't be used for global component

### ISSUE THREAD

**Issue by fireairforce** [vuejs/vue-class-component#392]
I found the issue and don't find my similar issue:
My code as follows:
main.ts:
```ts
import Pagination from './xxx/Pagination.vue'

Vue.component(Pagination.name, Pagination)
Vue.use(Pagination)
// ...
```
Pagination.vue:
```html
<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component'
import { Prop } from 'vue-property-decorator'
import { IPageInfo } from "@/types/common.ts"

@Component({
  name: 'Pagination'
})
export default class extends Vue {
  @Prop() pageInfo: IPageInfo
  
  onChange (page) {
    // ...
  }
}
</script>
```
When i use the component `Pagination`  **in the global without import** ,I will get error such like this :
![image](https://user-images.githubusercontent.com/32598811/73756892-46b91f00-47a3-11ea-9ec7-2bf24b4d8dbb.png)

If I change the code in `Pagination.vue` like this : 
```html
<script>
   export default {
      name :'pagination',
      // ...
  }
</script>
```
The project can work without error。

**Comment by fireairforce** [comment]
And my `package.json` are as follows : 
```json
"vue": "^2.5.17",
"vue-class-component": "^7.0.2",
"vue-property-decorator": "^8.3.0",
```

**Comment by ktsn** [comment]
Thank you for filing the issue. Please provide minimal and self-contained reproduction to confirm.
[What is a reproduction and why we need it?](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro)

**Comment by ktsn** [comment]
Closing until reproduction is provided. Please open a new issue if you can provide it. Thank you.
