### ISSUE TITLE
Different context in class property and method

### ISSUE THREAD

**Issue by SimonaliaChen** [vuejs/vue-class-component#400]
Hi, 

I find a weird problem.  I define a class as below,  and print `this` both in property `foo1` and method `foo2`.

```
@Component
export default class Demo extends Vue {
   private foo1 = () => {
      console.log(this) // Demo instance
  }
  
  private foo2() {
      console.log(this) // Vue component instance
  }

   mounted() {
      this.foo1();
      this.foo2();
   }
}
```

It seems there are different contexts in class properties and methods. I don't know whether is a bug or designed like this. Is there any way to access vue component instance  in properties?

**Comment by ktsn** [comment]
See: https://class-component.vuejs.org/guide/caveats.html#this-value-in-property-initializer

**Comment by SimonaliaChen** [comment]
@ktsn Thanks for your replying. I defined an arrow function as class property just want to reuse the TS declaration. And I thought it might be same behavior as ES class. Thanks anyway ：）
