### ISSUE TITLE
Vue 3.0 support

### ISSUE THREAD

**Issue by kabaluyot** [vuejs/vue-class-component#402]
This issue is a question regarding the **status of vue-class-component** which is aimed for Class-based Typescript users when the Vue3.0 is released with heavy emphasis also in Typescript. 

1. Will the project remain **officially supported** within the Vue ecosystem?

2. Will it have a "smooth" compatibility with the new composition API especially they are both in Typescript?

**Comment by ktsn** [comment]
1. Yes
2. Will provide a bridge api to use compositions in class component. 

I’m currently working on Vue 3 + class component and investigating the implementation and good api interface. I’ll create RFC thread once they are ready.

**Comment by kabaluyot** [comment]
Thank you for the clarification and future support with composition API. Will give it a go :)

**Comment by ktsn** [comment]
Proposals are already up:

- Fundamental change for Vue v3 #406 
- On adaption to composition api #416

**Comment by sreenaths** [comment]
https://github.com/vuejs/vue-next/issues/3373

**Comment by zhoulujun** [comment]
my vue2 project  is  use vuejs/vue-class-component,so  i want  update this project by vue3
why not officially support it!
i get very despress

**Comment by kabaluyot** [comment]
So .... What's the plan @ktsn? Is Vue class component still going to be supported for Vue3 or at least maintained with current vue2?
