### ISSUE TITLE
Using props in initial data?

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vue-class-component#41]
From the example in README there's:

```
// use prop values for initial data
  helloMsg = 'Hello, ' + this.propMessage
```

If I copy the full example into a component and use it, `helloMsg` is always undefined (even when the prop is set to a string). Should this be the case*? It works in other methods and such, but not in initial data.

*The wording in that comment makes it seem like this should not be undefined. :)

**Comment by ktsn** [comment]
Thanks for reporting this.
I'm afraid, I could not reproduce this problem. What module bunder/transpiler are you using?

**Comment by pearofducks** [comment]
Here's an [example repo](https://github.com/pearofducks/component-bug).

**Comment by ktsn** [comment]
The cause seems to be missing inheritance of Vue class. Adding `extends Vue` to Comp class solves this issue.
I'll update README and add a warning message for that...

**Comment by ktsn** [comment]
A warning message will be printed on v4.4.0 or later.
