### ISSUE TITLE
[Nuxt v2.12] New fetch doesn't work on component level

### ISSUE THREAD

**Issue by vslio** [vuejs/vue-class-component#418]
Nuxt introduced a new [`fetch` with their 2.12 release](https://nuxtjs.org/api/pages-fetch), which allows using it on components instead of just pages. 

`vue-class-component` seems to be entirely ignoring the hook. I've put together an example to reproduce the issue [here](https://codesandbox.io/s/zen-kowalevski-vp8om).

**Comment by ktsn** [comment]
We don't add third party hooks as a built-in. You can use `registerHooks` to add it by yourself.
https://class-component.vuejs.org/guide/additional-hooks.html

Also checkout nuxt-class-component.
https://github.com/nuxt-community/nuxt-class-component

**Comment by vslio** [comment]
@ktsn thanks so much!
