### ISSUE TITLE
How to extend single file components

### ISSUE THREAD

**Issue by loeffel-io** [vuejs/vue-class-component#420]
Hey, 

i am trying to extend **methods** of an vue class component like as mentioned [here](https://class-component.vuejs.org/guide/extend-and-mixins.html#extend) with the following output: 

`[Vue warn]: Failed to mount component: template or render function not defined.`

Is there any way to include or load the script and template part of my single file component? 

Thanks! Have a good day

**Comment by loeffel-io** [comment]
Could find this solution: 

```javascript
SuperComponent.extend({
    methods: {
        validateEmail(): boolean | null {
            if (this.user.email === null) {
                return null;
            }

            return this.user.email.length > 6;
        }
    },
```

Would love to see an full class possibility

**Comment by ktsn** [comment]
You just don't have `template` or `render` in your component as the warning saids. Methods are not related with this warning.

Please use our [forum](https://forum.vuejs.org), [chat room](https://chat.vuejs.org) or StackOverflow to ask usage question as the issue list of this repo is dedicated for bug reports and feature requests as we state in [the readme](https://github.com/vuejs/vue-class-component#questions). Thanks.
