### ISSUE TITLE
class get  cache issue

### ISSUE THREAD

**Issue by John0King** [vuejs/vue-class-component#424]
copied from  https://github.com/kaorun343/vue-property-decorator/issues/320.

I do not know which repo should handle this issue, but

the `get/set` should not be cached  to align with the `class`'s  behavior

```ts
@Component
export default class MyComponent extends Vue{
    @Prop({type:Object, default:()=({})})
     value!:any;

    obj:any = {};
    get obj2(){
        console.log("get ")// this will only log once,
        return {...obj, a: new Date()}
    }

    @Watch('value',{ deep:true})
    watchValue(v:any){
        this.obj = {... this.value}
    }

    mounted(){
         this.watchValue(this.value);
    }
}
```

**Comment by ktsn** [comment]
Getters / setters are converted to computed properties as docs saids.
https://class-component.vuejs.org/guide/class-component.html#computed-properties

Vue caches the return value of computed properties, so it's expected behavior.

**Comment by John0King** [comment]
@ktsn   if `Getters / setters are converted to computed properties`  then it should use the `cache:false`  instead of the default cache mode. without cache  ,the behavior is match to the class behavior .
this is what the class do when  you call `this.<property>`  ,
and for vue object style,  they called computed properties not geter/seter.

I suggest:
1.  the default get/set  convert to  computed properties with option `cache:false`
2.  add  `@Computed(options: { cache?:boolean })`  and allow configurate with the `get` or `set` method (configurate only need once  eg.  only add on `getter`  or `setter`  ,  like angular does)

**Comment by John0King** [comment]
@ktsn   reopen this ?

**Comment by ktsn** [comment]
Several reasons I think it doesn't justify the change.

1. This is breaking change
1. Vue doesn't have an option of no cache for computed properties (in public api).
1. Vue Class Component is for making Vue component before being aligning class behavior. If you want to make it behaving everything like standard class behavior, we would also disable making class properties become reactive which is too redundant to define Vue component (computed also can be told).
1. We don't aggressively introduce decorators as its spec is still unstable and we don't see much progress on it.
1. You can use methods if you don't want caching which is known pattern in Vue.js

**Comment by John0King** [comment]
@ktsn  
>Vue doesn't have an option of no cache for computed properties (in public api)

maybe I missing some thing , but from the code I think it indeed have a api for control the cache behavior

```ts
@Component<SearchPanel>({
  computed: {
    txtValue: {
      cache: false, //////  this is the api ?
      get: function() {
        let x = {
          ...this.copyValue,
          timeStart: this.getDateStr(this.copyValue.timeStart),
          timeEnd: this.getDateStr(this.copyValue.timeEnd)
        };
        console.log(x);
        return x;
      }
    }
  }
})
export default class SearchPanel extends Vue{
copyValue: any= {};
txtValue!: any; 
}
```

**Comment by ktsn** [comment]
It's undocumented / private api and we recommend against using it.
