### ISSUE TITLE
will the new version support abstract base component classes ?

### ISSUE THREAD

**Issue by nour-dev** [vuejs/vue-class-component#425]
in the current version this is not working , so can this feature be added to the new version ?

**Comment by ktsn** [comment]
Yes.

**Comment by nour-dev** [comment]
@ktsn :+1:

**Comment by undergroundwires** [comment]
When will it be released? I'd love to use this feature.

**Comment by undergroundwires** [comment]
@ktsn, when will it be released? I'd love to use this feature 👀
