### ISSUE TITLE
[Help] Async Component

### ISSUE THREAD

**Issue by paolog22** [vuejs/vue-class-component#428]
I was trying to load a component in async manner to show a 'Loading' indicator and or add delay and timeout 

Please refer to screenshot
![image](https://user-images.githubusercontent.com/12680745/80438768-883b0f80-8937-11ea-935d-a1f73a4e30d2.png)
`PrescriptionForm` is not recognize and typescript is throwing an error 

What am i missing here ? 

thank you

Plugins
typescript@3.7.5
vue-class-component@7.2.3
vue-property-decorator@8.4.1
vue@2.6.11
vue-router@3.1.6

**Comment by ktsn** [comment]
Thank you for filing this issue.
Please make sure to provide a **minimal and self-contained reproduction** if you are reporting a bug.
You can use the following jsfiddle template or make an example github repository.
https://jsfiddle.net/ktsn/nm55jnjk/

[What is a minimal reproduction, and why is it required?](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro)

**Comment by ktsn** [comment]
Closing as a reproduction is not provided.

**Comment by NikoGrano** [comment]
I am able to reproduce this just plainly with given screenshot. Also the description is enough clean to understand. 

Anyways, this isn't bug, this is **undocumented** feature which I don't either know how to work with.

@ktsn Do you want me to open issue for undocumented feature as it will not have reproductable repository, due it **doesnt make any sense** to create repo for code which has no fault or bug in it.

**Comment by zealotrahl** [comment]
Yes please, also encountered this problem
