### ISSUE TITLE
v7.2.4 breaks "Mixins" decorator usage

### ISSUE THREAD

**Issue by Ky6uk** [vuejs/vue-class-component#435]
After upgrading from `v7.2.3` to `v7.2.4` I'm getting a lot of different TypeScript compilation errors because of using `Mixins` decorator as generics. Something like

```Type 'MixinName<Data>' does not satisfy the constraint 'VueClass<Vue>[]'.```

I'm using mixins like that

```ts
@Component
export class MixinName<T> extends Vue {
  // ...
}
```

```ts
export default class Page extends Mixins<MixinName<Data>>(MixinName) {
  // ...
}
```

It looks like breaking changes has been introduced in `v7.2.4`, but I have no idea what wrong exactly. `v7.2.3` works perfectly.

**Comment by Ky6uk** [comment]
Opened different issue https://github.com/kaorun343/vue-property-decorator/issues/335

**Comment by wangziling** [comment]
Yes. I had encountered this issue.
If you **Mixins** as **Mixins**-ed Component,

```js
class A extends Mixins(B) {
  get a () {
     // This will come up an issue that `b` is nonexistent in `A`
     return this.b;
  }
}

class B extends Mixins(C) {
    b!: number;
}

class C extend Vue {}
```

I think this may be an issue about the declarition type for `Mixins` method.
In previous version, `Mixins` used the  
```ts
export declare function mixins<A, B>(CtorA: VueClass<A>, CtorB: VueClass<B>): VueClass<A & B>;
```

But now using the `infer` keyword.
```ts
export declare type MixedVueClass<Mixins extends VueClass<Vue>[]> = Mixins extends (infer T)[] ? VueClass<UnionToIntersection<ExtractInstance<T>>> : never;

export declare function mixins<T extends VueClass<Vue>[]>(...Ctors: T): MixedVueClass<T>;
```

I just recognized by my `ts` coding experiences, that here maybe a little problem when using `infer` in typescript. It is not very smart and accuracy, sometimes it cannot `infer` a type with a deep and complex logic correctly...

**Comment by wangziling** [comment]
This will not encountered in `7.2.3` version.

**Comment by Ky6uk** [comment]
It looks the breaking change has been introduced in this PR https://github.com/vuejs/vue-class-component/pull/433 @ktsn
