### ISSUE TITLE
vue-property-decorator @component not a function type

### ISSUE THREAD

**Issue by 28development** [vuejs/vue-class-component#449]
I am using VueJs with NuxtJs and Typescript. Currently I am using the `vue-property-decorator` package.
My code works fine in the browser but my ide (intelij) return me this error message:

> Method expression is not of Function type

```
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import Navigation from '~/components/Navigation.vue';
import Footer from '~/components/Footer.vue';

@Component({ // <-- error message here: Method expression is not of Function type
  components: { Navigation, Footer },
})
export default class Default extends Vue {}
</script>
```

If I change the above code to following I get no error message from the ide:

```
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Default extends Vue {}
</script>
```

Further I have a vue-shims.d.ts file configured like this:
```
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}

```

**Comment by ktsn** [comment]
Thank you for filing this issue.
Please make sure to provide a **minimal and self-contained reproduction** if you are reporting a bug.
You can use the following jsfiddle template or make an example github repository.
https://jsfiddle.net/ktsn/nm55jnjk/

[What is a minimal reproduction, and why is it required?](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro)

**Comment by 28development** [comment]
@ktsn jsfiddle won't get the error message since it comes from the ide. The webapp works fine no errors, but the ide error annoys me.

Anyways here is the code for the component:

https://kopy.io/6yUhA

**Comment by ktsn** [comment]
@28development You can create a GitHub repository for reproduction. The snippet is not a reproduction as I cannot run it and evaluate the issue on my local.

**Comment by ktsn** [comment]
Closing until reproduction is provided.

**Comment by yxlolxy** [comment]
I hava the same question!
