### ISSUE TITLE
Unable to access Vue.prototype in a class that extends Vue

### ISSUE THREAD

**Issue by adam-cowley** [vuejs/vue-class-component#455]
I'm getting undefined errors when I attempt to access a property appended to `Vue.prototype` during the installation of a plugin.

Say I have a plugin:

```js
Vue.use((Vue) => {
  Vue.prototype.$foo = 'foo'
})
```

IIf I export an object I'm able to access the 

```js
export default  {
  created() {
    console.log(this.$foo) // foo
  }
}
```

However if I extend `Vue` as recommended in the docs I can no longer access the property:

```js
export default class FooComponent extends Vue {
   $foo!: string;

    created() {
        console.log(this.$foo) // undefined
    }
}
```

I've been searching the docs, stackoverflow but can't see an answer.  I've added the module declaration as recommended and the code is compiling in ts, it just won't run in the browser:

```
declare module 'vue/types/vue' {
    interface Vue {
      $foo: string;
    }
}
```
I've seen a few issues on this repo that hint at the problem (#378, #380) but they were closed immediately without any response?

**Comment by ktsn** [comment]
Thank you for filing this issue.
Please make sure to provide a **minimal and self-contained reproduction** if you are reporting a bug.
You can use the following jsfiddle template or make an example github repository.
https://jsfiddle.net/ktsn/nm55jnjk/

[What is a minimal reproduction, and why is it required?](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro)

**Comment by ktsn** [comment]
Closing until reproduction is provided.
