### ISSUE TITLE
$store error with vue 3 and vuex 4

### ISSUE THREAD

**Issue by LiamJamesWiddop** [vuejs/vue-class-component#460]
Following up from a [recent thread ](https://github.com/vuejs/vetur/issues/2292) vuejs vetur.
I am having the effectively the same issue on a windows machine, where I receive the following error: 
![image](https://user-images.githubusercontent.com/38372612/94366996-bc9b3d80-011a-11eb-8df3-ccc244bb4b93.png)

Interestingly... this causes errors.
![image](https://user-images.githubusercontent.com/38372612/94366963-907fbc80-011a-11eb-8dc8-4b3899f31eb0.png)

But this does not.
![image](https://user-images.githubusercontent.com/38372612/94366972-9d9cab80-011a-11eb-9141-776afd670967.png)

I believe am using the Vue 3 and Vuex 4 correctly: 
![image](https://user-images.githubusercontent.com/38372612/94367022-f79d7100-011a-11eb-8cbd-d5edd3ad0758.png)

Can someone help me clarify where the issue is? The guys at vuejs (see thread above) felt it was related to vue-class-component.
![image](https://user-images.githubusercontent.com/38372612/94367050-1e5ba780-011b-11eb-87a6-22661a0bc14f.png)

Thanks in advance!

**Comment by ktsn** [comment]
You have to declare the `$store` type by yourself. See https://github.com/vuejs/vuex/tree/4.0#typings-for-componentcustomproperties

**Comment by Newfffff** [comment]
/**
 * Custom properties added to component instances in any way and can be accessed through `this`
 *
 * @example
 * Here is an example of adding a property `$router` to every component instance:
 * ```ts
 * import { createApp } from 'vue'
 * import { Router, createRouter } from 'vue-router'
 *
 * declare module '@vue/runtime-core' {
 *   interface ComponentCustomProperties {
 *     $router: Router
 *   }
 * }
 *
 * // effectively adding the router to every component instance
 * const app = createApp({})
 * const router = createRouter()
 * app.config.globalProperties.$router = router
 *
 * const vm = app.mount('#app')
 * // we can access the router from the instance
 * vm.$router.push('/')
 * ```
 */
export interface ComponentCustomProperties {}

> Following up from a [recent thread ](https://github.com/vuejs/vetur/issues/2292) vuejs vetur.
> I am having the effectively the same issue on a windows machine, where I receive the following error:
> ![image](https://user-images.githubusercontent.com/38372612/94366996-bc9b3d80-011a-11eb-8df3-ccc244bb4b93.png)
> 
> Interestingly... this causes errors.
> ![image](https://user-images.githubusercontent.com/38372612/94366963-907fbc80-011a-11eb-8dc8-4b3899f31eb0.png)
> 
> But this does not.
> ![image](https://user-images.githubusercontent.com/38372612/94366972-9d9cab80-011a-11eb-9141-776afd670967.png)
> 
> I believe am using the Vue 3 and Vuex 4 correctly:
> ![image](https://user-images.githubusercontent.com/38372612/94367022-f79d7100-011a-11eb-8cbd-d5edd3ad0758.png)
> 
> Can someone help me clarify where the issue is? The guys at vuejs (see thread above) felt it was related to vue-class-component.
> ![image](https://user-images.githubusercontent.com/38372612/94367050-1e5ba780-011b-11eb-87a6-22661a0bc14f.png)
> 
> Thanks in advance!
