### ISSUE TITLE
Async composition functions and setup helper

### ISSUE THREAD

**Issue by shaci** [vuejs/vue-class-component#463]
Sorry for dumb question, I newbie in vue 3 and vue-class-component. If I define async/await useCounter (initial example of useCounter without async/await here https://github.com/vuejs/vue-class-component/issues/416#issue-607043808), I get error after click on the plus button
![image](https://user-images.githubusercontent.com/1643065/94995923-1a5fd780-05aa-11eb-84be-7adad843b8f1.png)
Error: 
![image](https://user-images.githubusercontent.com/1643065/94996030-cef9f900-05aa-11eb-84ea-88f13e239673.png)

How do I can fix it?

_Originally posted by @shaci in https://github.com/vuejs/vue-class-component/issues/416#issuecomment-703125787_

**Comment by ktsn** [comment]
fixed in beta.4
