### ISSUE TITLE
v8 Migration support

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#464]
Are there any plans to support migration from v7 to v8? Since `vue-class-component` is officially supported by vuejs core team, it would be nice if the migration process from v7 to v8 was as smooth as possible.

Many people have probably created some projects based on the template scaffolded by vue-cli. In this template the project uses two packages: `vue-class-component` and `vue-property-decorator`. I think also that most people are using `@Prop` and `@Watch` decorators from `vue-property-decorators`.

Is there a chance for any migration support?

**Comment by ktsn** [comment]
- For migration from v7 to v8, I'm going to write a migration guide.
- Regarding vue-property-decorator, I asked @kaorun343 and he said he is going to update it to support Vue 3. So you don't have to remove vue-property-decorator from your code if you already use it.
