### ISSUE TITLE
Honoring name on @component

### ISSUE THREAD

**Issue by Mushr0000m** [vuejs/vue-class-component#466]
Hi, I read on other issues that the property `name` from `@component` is not for registering the `tag` but just for recursion. Would it be possible to make it useable ? The fact that de decorator automaticaly take the component file name to make a tag selector for it is kind of an issue for us. We use kind of ABEM pattern where each css/js component have a prefix based on it's type `element`, `block`, etc. So for an `ArticleCard` the css selector will be `.b-article-card`. So being able to to follow the same pattern and have our component file `ArticleCard.vue` matching to `<b-article-card>` without having to renaming it to `BArticleCard.vue` (which is uggly in PascalCase) would be nice.

So having something like : 
```
@Component({
    name: 'BArticleCard'
})
export default class ArticleCard extends Vue {...}
```
Even if it's possible to use the declaration bellow, I don't like it so much because on a team there is always the need to remember to import component this way and can lead human errors importing with or without prefix : 
```
components: {
    'b-article-card': ArticleCard
}
```
I feels like it should be the component responsability. Any thought ?

**Comment by ktsn** [comment]
Seems like you want some sort of eslint rule to restrict the component name on registration time. In any cases, this looks out of the scope of Vue Class Component since 1) `name` property is a general Vue component option, 2) to avoid human errors in writing code is a linter job.

Or if you want to access `name` option in runtime, you can do `ArticleCard.options.name` to validate already.

**Comment by Mushr0000m** [comment]
Even if I understand what you mean seen other framework having things like : 
```
@Component({
  tag: 'b-article-card',
})
```
to declare the html tag that should be use make a lot of sence IMHO.

Large project like here https://github.com/buefy/buefy/blob/dev/src/components/image/Image.vue uses the vuejs component `name` property to tell what the html tag should be. In this example the class is `Image.vue` but the tag to use it is `b-image`. But of course they don't use the Class syntax, so I though it was a missing part for the Class syntax.
