### ISSUE TITLE
Accessing this value from watch, provide and other Vue features

### ISSUE THREAD

**Issue by LifeIsStrange** [vuejs/vue-class-component#468]
@ktsn So we did try the latest vue class component beta and while the new props declaration is working just fine, we need to have Watch, Provide and other related Vue features.
Putting watch in @options works but is not expressive enough at all. The static alternative is not yet implemented but would suffer the same issue being static ?

**The issue** is that we were able to access the class variables through this inside the method that react to the thing it watch.
This expressivity is needed for a lot of behavior and we are unable to migrate to Vue3 until this crucial limitation is fixed.

I am repeating this from a comment because the issue is more than 6 months old and the industry is frozen until this which is very stressful.

**Comment by ktsn** [comment]
You can access `this` via both `@Options` and `this.$watch` already. As for provide/inject, I'm considering an API to achieve it in type safe way currently. Also, you can still use vue-property-decorator if you prefer it since the author said he is going to update it for Vue 3.

**Comment by ktsn** [comment]
Closing since this issue is not actionable. Concrete proposals for each feature would be a separate issue.
