### ISSUE TITLE
How can I use emits in beta4

### ISSUE THREAD

**Issue by rieval** [vuejs/vue-class-component#471]
I found that `emits` has been removed from version beta4, and how can I use `emits` now ?

![Screenshot1.jpg](https://i.loli.net/2020/10/16/F46QI8DitfxGYVa.jpg)

![Screenshot2.jpg](https://i.loli.net/2020/10/16/3QIOeg7nBswPLMR.jpg)

**Comment by ktsn** [comment]
Alternative proposal will come later.
