### ISSUE TITLE
[FEATURE REQUEST] support abstract classes in v8

### ISSUE THREAD

**Issue by nour-dev** [vuejs/vue-class-component#472]
is supporting abstract classes can be considered in the new version ? 
and why it can not be supported if not ?

**Comment by ktsn** [comment]
Please elaborate what "abstract class support" means. Abstract class component? mixin? something else?

**Comment by nour-dev** [comment]
> Please elaborate what "abstract class support" means. Abstract class component? mixin? something else?
I mean typescript abstract classes . for example :
```ts
abstract class Person {
    name: string;
    
    constructor(name: string) {
        this.name = name;
    }

    display(): void{
        console.log(this.name);
    }

    abstract find(string): Person;
}
```

**Comment by ktsn** [comment]
If you mean it's component, we can't because Vue instantiate it. If it's mixin, already supported.
