### ISSUE TITLE
create decorator Inject with v8 undefined value

### ISSUE THREAD

**Issue by daddycarbone** [vuejs/vue-class-component#477]
i copy paste the code how to create decarator from depedency "vue-class-decarator" like this:
```
// @/configs/InjectDecarator.ts

import {createDecorator} from "vue-class-component"

export function Inject(options?: any) {
    return createDecorator((componentOptions, key) => {
        if (typeof componentOptions.inject === 'undefined') {
            componentOptions.inject = {}
        }
        if (!Array.isArray(componentOptions.inject)) {
            componentOptions.inject[key] = options || key
        }
    })
}
```

and in Component
```
import { Options, Vue } from "vue-class-component";
import { Inject } from "@/configs/InjectDecarator"; // from copy paste vue-class-decarator
import globalContainer from "@/configs/di.config"; // iOc container
import { TYPES } from "@/models/Types"; // ideftifier as Symbol
import { DependencyContainer } from "tsyringe";

@Options({
  components: {
    HelloWorld
  }
})
export default class Home extends Vue {
  name!: string;
  private _ninja!: _Ninja;

  @Inject(globalContainer.resolve<DependencyContainer>(TYPES.CONTAINER))
  private _container!: DependencyContainer;

  created() {
    console.log(this._container);
    this.name = "Hello world";
  }
```

i tried console.log `this._container` but got undefined but when i `console.log(globalContainer.resolve<DependencyContainer>(TYPES.CONTAINER))` i got the result, is that something wrong for the inject decarator above?

**Comment by ktsn** [comment]
Thank you for filing this issue.
Please make sure to provide a **minimal and self-contained reproduction** if you are reporting a bug.
You can use the following jsfiddle template or make an example github repository.
https://jsfiddle.net/ktsn/nm55jnjk/

[What is a minimal reproduction, and why is it required?](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro)

**Comment by ktsn** [comment]
Closing until reproduction is provided.
