### ISSUE TITLE
Cannot find name 'Vue'

### ISSUE THREAD

**Issue by neilsimp1** [vuejs/vue-class-component#48]
I've just started a typescript/electron app, and after getting the basics down with normal component files, I tried switching to vue-class-component.

After installing and changing one component over to this format and compiling with `tsc`, I'm getting:

```
> tsc --p tsconfig.json
node_modules/vue-class-component/lib/declarations.d.ts(3,13): error TS2304: Cannot find name 'Vue'.
node_modules/vue-class-component/lib/index.d.ts(4,38): error TS2304: Cannot find name 'Vue'.
node_modules/vue-class-component/lib/index.d.ts(4,52): error TS2503: Cannot find namespace 'Vue'.
node_modules/vue-class-component/lib/util.d.ts(3,60): error TS2503: Cannot find namespace 'Vue'.
node_modules/vue-class-component/lib/util.d.ts(3,119): error TS2304: Cannot find name 'Vue'.
node_modules/vue-class-component/lib/util.d.ts(4,60): error TS2503: Cannot find namespace 'Vue'.
node_modules/vue-class-component/lib/util.d.ts(4,134): error TS2304: Cannot find name 'Vue'.
```

Here's my `tsconfig.json`:
```
{
	"compilerOptions": {
		"target": "es6",
		"moduleResolution": "node",
		"lib": [
			"dom",
			"es2016"
		],
		"rootDir": "src/",
		"outDir": "dist/",
		"module": "commonjs",
		"allowJs": true,
		"removeComments": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true
	}
}
```

package.json:
```
"devDependencies": {
        "copyfiles": "^1.0.0",
        "electron": "^1.4.12",
        "node-sass": "^4.0.0",
        "typescript": "^2.1.4",
        "vue": "^2.1.6",
        "vue-class-component": "^4.4.0"
}
```
src/package.json
```
"dependencies": {
	"@types/electron": "^1.4.29",
	"@types/node": "^6.0.52",
	"@types/vue": "^1.0.31"
}
```

I'm roughly following the project structures from https://github.com/wspl/electron-boilerplate-typescript-vue and https://github.com/bradstewart/electron-boilerplate-vue, hence the two package.json's.

Any input would be appreciated, I really want to use this plugin.

**Comment by ktsn** [comment]
Thanks for trying vue-class-component.
It looks like the compiler failed to find Vue's type declarations. Did you install `vue` via npm? Also what version of Vue and vue-class-component are you using?

**Comment by neilsimp1** [comment]
Yes, I installed Vue via npm.  I'll update my original post.

**Comment by ktsn** [comment]
`"@types/vue": "^1.0.31"` is the types for Vue v1.x.
I guess it would work by just removing `@types/vue`.

FYI: https://vuejs.org/v2/guide/typescript.html

**Comment by neilsimp1** [comment]
I had read that before, but needed to install the types for something else that wasn't working correctly. I removed it and it seems to compile fine now. Thank you.

Now when I try running it, I'm getting the `Failed to mount component: template or render function not defined.(found in root instance)` error.

From index.html:
```
<div id="app"></div>
<script>
	const Vue = require('vue')
		, { App }  = require('./components/App');
	new Vue({
		el: '#app',
		components: { App }
	});
</script>
```
If I switch to `require('vue/dist/vue.common')`, nothing happens, and my html body just stays at
```<div id="app"></div>```.

And if I add in something like `render: h => h(App)` to `new Vue()`, the `mounted()` on `App` does get called, but I get the `You are using the runtime-only build of Vue where the template option is not available...` error. `vue/dist/vue.common` with the render function still gives the same error.

Am I doing something incorrectly still? Should This be a separate issue?

**Comment by ktsn** [comment]
When you use template without `.vue` file, you have to set alias `vue` with the standalone build on webpack or browserify.

For detail information, please see: https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by neilsimp1** [comment]
I'm not currently using Webpack for this. There's just `.ts` files and `tsc --p tsconfig.json`. Do I need Webpack to use vue-class-components?

**Comment by ktsn** [comment]
> Do I need Webpack to use vue-class-components?

Strictly speaking, no, it actually is not related with vue-class-component. The error happens because Vue's runtime build cannot compile template since it does not have template compiler. You can use vue-class-component with the runtime build if you remove all templates in your code by using render option or pre-compile template. ([vue-loader](https://github.com/vuejs/vue-loader) does that under the hood)

I'm not sure about Electron but I guess there are no way to set alias to required module name? If so, unfortunately, we cannot use vue-class-component with standalone build because vue-class-component [directly depends on `vue` module](https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L1). That means vue-class-component will refer the runtime build even if we use standalone build (`require('vue/dist/vue.common.js')`) in our code.

I think the simplest way is using webpack to set alias to standalone build. Or using vue-loader is also an option. I recently make [webpack+typescript+vue template](https://github.com/ktsn/typescript-webpack-simple) - I hope it will help you.

**Comment by neilsimp1** [comment]
Thanks, you just cleared up a lot for me. I'll take a look at your template and see if I can't figure it out from there. You've been a huge help - just another example of how awesome the Vue.js community is. I'll close this since at this point any problems I may have don't really have anything to do with my original issue.
