### ISSUE TITLE
[v8-rc1] Setup function error - Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#481]
I have the following component:

```vue
<template>
  <div class="hello">
    <div>{{ counter.count }}</div>
    <button @click="increment">Increment</button>
  </div>
</template>

<script lang="ts">
import { onMounted, ref } from 'vue';
import { Options, prop, setup, Vue } from 'vue-class-component';

class Props {
  msg = prop({ type: String });
}

function useCounter() {
  const count = ref(0)

  function increment() {
    count.value++
  }

  onMounted(() => {
    console.log('onMounted')
  })

  return {
    count,
    increment
  }
}

@Options({})
export default class HelloWorld extends Vue.with(Props) {
  private counter = setup(() => useCounter());
}
</script>
```

When I click the button I receive the following error:

![Screenshot 2020-11-20 at 22 47 58](https://user-images.githubusercontent.com/17653648/99853028-7f838280-2b82-11eb-95bf-f2dfd0302434.png)

I am using:
- vue 3.0.2
- vue-class-component 8.0.0-rc.1

Repro project:
[class-component-test.zip](https://github.com/vuejs/vue-class-component/files/5576255/class-component-test.zip)

**Comment by ktsn** [comment]
Because you refer to wrong method `increment`. The correct one is `counter.increment`
