### ISSUE TITLE
[v8] Options decorator without arguments

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#483]
In v7 I was able to use `@Component` decorator like this:

```
@Component
export default class App extends Vue {

}
```

However in v8 when I use a decorator like this:
```
@Options
export default class App extends Vue {

}
```

I receive the following error:
![Screenshot 2020-11-21 at 14 11 35](https://user-images.githubusercontent.com/17653648/99878124-7edf0080-2c03-11eb-9c7b-8cd755040472.png)

Repro project:
[class-component-test.zip](https://github.com/vuejs/vue-class-component/files/5577662/class-component-test.zip)

**Comment by ktsn** [comment]
Intentional. If you don't need arguments, you should just remove `@Options`.
