### ISSUE TITLE
Class components in .vue files

### ISSUE THREAD

**Issue by sebastiandedeyne** [vuejs/vue-class-component#49]
Are there any official resources or recommendations on using class components with TypeScript in single file components?

Should vue-ts-loader be used? https://github.com/HerringtonDarkholme/vue-ts-loader

**Comment by HerringtonDarkholme** [comment]
Please use the official ts-loader. Vue support has been merged. https://github.com/TypeStrong/ts-loader#appendtssuffixto-regexp-default

**Comment by Evertt** [comment]
I'm not able to get this to work, even with the information provided by the link. I constantly get errors about a tsconfig.json. What is the tsconfig.json file supposed to look like?
