### ISSUE TITLE
[v8] TypeScript error when extending setup helper

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-class-component#499]
I have the following component:

```vue
<template>
  <div>{{ text }}</div>
</template>

<script lang="ts">
import { ref } from "vue";
import { Vue, setup, mixins } from "vue-class-component";

const Super = setup(() => {
  const text = ref('A')

  return {
    text,
  }
})

export default class HelloWorld extends mixins(Super) {
}
</script>
```

It throws TypeScript error:

![Screenshot 2020-12-21 at 20 28 51](https://user-images.githubusercontent.com/17653648/102814583-28fca480-43cb-11eb-9e81-063b26e0fd98.png)

Here is the repro project:
[class-component-test.zip](https://github.com/vuejs/vue-class-component/files/5726082/class-component-test.2.zip)

**Comment by ktsn** [comment]
`setup` doesn't generate constructor but you should use it for class properties.

**Comment by Mikilll94** [comment]
@ktsn
This is taken from your post:

https://github.com/vuejs/vue-class-component/issues/416#issue-607043808

![Screenshot 2020-12-22 at 12 15 38](https://user-images.githubusercontent.com/17653648/102882904-6acf2e80-444f-11eb-9490-c212002f3856.png)

**Comment by ktsn** [comment]
It's "alternative approach" ...

**Comment by diphuaji** [comment]
> It's "alternative approach" ...

So are you saying it's not implemented yet?
