### ISSUE TITLE
Babel vs Typescript

### ISSUE THREAD

**Issue by davidmoshal** [vuejs/vue-class-component#51]
Just wondering what the thoughts are re choosing between Babel and Typescript for a Vue + TS project?

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
