### ISSUE TITLE
[Vue v3] how to get slots in setupFn 

### ISSUE THREAD

**Issue by AllenYu-BF** [vuejs/vue-class-component#512]
i want to get slots in setupFn,but now there is no document.who can help me to resolve this question

**Comment by LinusBorg** [comment]
https://v3.vuejs.org/guide/composition-api-setup.html#context

**Comment by AllenYu-BF** [comment]
sorry, it's my fault. I want to know how to get slots in setupFn When Vue3 + ts + vue-class-component like the picture below
![Uploading image.png…]()

**Comment by LinusBorg** [comment]
according to https://github.com/vuejs/vue-class-component/issues/416 you should be able to access them through `this.$slots`.

If that doesn't work it's likely a bug.

**Comment by AllenYu-BF** [comment]
thanks a lot,It's I didn't look carefully.
