### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by davidmoshal** [vuejs/vue-class-component#52]
Wondering what and end-to-end test setup with Vue and Typescript would look like, using, say:
- Nightwatch.js
- Jest with snapshots

thanks
David

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
