### ISSUE TITLE
[BUG] Duplicate export of 'default' 

### ISSUE THREAD

**Issue by NWYLZW** [vuejs/vue-class-component#540]
## desc
get a error when use vue-class-component and vite

## logs
![image](https://user-images.githubusercontent.com/51358815/122395908-0deda480-cfaa-11eb-8597-c486ec316560.png)

## versions
vite - 2.3.5
vue-class-component - 8.0.0-rc.1

**Comment by ygj6** [comment]
Duplicate of https://github.com/vitejs/vite/issues/3693 ?

**Comment by NWYLZW** [comment]
> Duplicate of [vitejs/vite#3693](https://github.com/vitejs/vite/issues/3693) ?

If it is fixed, I will try again

**Comment by GongT** [comment]
代码里看到已经修复了，但是npm上最新版是`@vue/compiler-sfc 3.1.1`，还没更新。

可以先把`node_modules/@vue/compiler-sfc/dist/`里面`compiler-sfc.cjs.js`和`compiler-sfc.esm-browser.js`两个文件改一下。

```js
const namedDefaultExportRE = /((?:^|\n|;)\s*)export(.+)as(\s*)default/s; // <<--- 这加个s
```

**Comment by NWYLZW** [comment]
> 代码里看到已经修复了，但是npm上最新版是`@vue/compiler-sfc 3.1.1`，还没更新。
> 
> 可以先把`node_modules/@vue/compiler-sfc/dist/`里面`compiler-sfc.cjs.js`和`compiler-sfc.esm-browser.js`两个文件改一下。
> 
> ```js
> const namedDefaultExportRE = /((?:^|\n|;)\s*)export(.+)as(\s*)default/s;
> //                                                                    ^--- 这加个s
> ```

hhhh
thx ^-^
