### ISSUE TITLE
Hot Module Reload for Components

### ISSUE THREAD

**Issue by Grafikart** [vuejs/vue-class-component#55]
First I want to thank you for this component that bring typescript and VueJS together. 

This reunion comes at a cost since HMR (Hot Module Reload) is not working anymore.
Do you think it's possible to enable HMR when a class is decorated ?
Or should we implement HMR ourself when importing a class using this decorator ?

**Comment by ktsn** [comment]
Unfortunately, we can't introduce HMR in this library.
We should implement that feature on any module bundlers such as webpack or browserify.
Please see #28
