### ISSUE TITLE
how to use with vuex

### ISSUE THREAD

**Issue by tonypee** [vuejs/vue-class-component#56]
How can i use mapActions, or mapGetters with using classes? 

in vuex they use:

computed: {
  ...mapState('foo', {
    // state is the state of the `foo/` module instead of root
    bar: state => state.bar
  }
},
methods: {
  ...mapActions('foo', [
    // map this.doSomething() to this.$store.dispatch('foo/doSomething')
    'doSomething'
  ])
}

**Comment by ktsn** [comment]
We can specify component options object to `@Component` decorator, so you can just use these helpers.

```js
@Component({
  computed: {
    ...mapState('foo', {
      bar: state => state.bar
    }
  },
  methods: {
    ...mapActions('foo', [
      'doSomething'
    ])
  }
})
```

If you would like to write as more class-like style, I encourage you to write some custom decorators.

```js
function Getter (getterType) {
  return createDecorator((options, key) => {
    if (!options.computed) options.computed = {}
    options.computed[key] = function () {
      return this.$store.getters[getterType]
    }
  })
}

@Component
class MyComp extends Vue {
  @Getter('foo') bar

  created () {
    console.log(this.bar)
  }
}
```

**Comment by Kochiya-Yoru** [comment]
@ktsn If use custom decorators, how to pass payload?
`this.data` is not useable in babel.

**Comment by DimaJedi** [comment]
`function MapGetters (namespace, states) {
  return createDecorator(options => {
    if (!options.computed) {
       options.computed = {}
    }
    Object.assign(options.computed, mapGetters(namespace, states))
  })
}
}
`
Inside any class component
`  
@Component
class MyComp extends Vue {
@MapGetters('some/namespace', ['getter1', 'getter2'])

  created () {
    console.log(this.getter1)
  }
}
`
I found this way more functional and common with vue style

**Comment by JakubKoralewski** [comment]
@DimaJedi what's the `namespace` in this context?

**Comment by Augustalex** [comment]
If you are using Typescript I would recommend @ktsn solution 

> ```js
> function Getter (getterType) {
>   return createDecorator((options, key) => {
>     if (!options.computed) options.computed = {}
>     options.computed[key] = function () {
>       return this.$store.getters[getterType]
>     }
>   })
> }
> 
> @Component
> class MyComp extends Vue {
>   @Getter('foo') bar
> 
>   created () {
>     console.log(this.bar)
>   }
> }
> ```

**Comment by Timmmm** [comment]
I couldn't get @ktsn's code to work. As far as I can tell these are the types:

```
import { createDecorator, VueDecorator } from 'vue-class-component';
import { ComponentOptions } from 'vue';

function Getter(getterName: string): VueDecorator {
  return createDecorator((options: ComponentOptions<Vue>, key: string, index: number): void => {
    if (options.computed === undefined) {
      options.computed = {};
    }
    options.computed[key] = function(this: Vue) {
      return this.$store.getters[getterName];
    };
  });
}

@Component
class MyComp extends Vue {
  @Getter('info')
  public info?: Info;
}
```

This compiles but `MyComp::info` doesn't get updated reactively from the store (it is always `undefined`). If I change it to be `public info: Info | null = null` then I get errors that `info` already exists in the `data` type, when it tries to set `options.computer['info']`. That makes sense to me. Declaring the field in the class adds it to `data` and the decorator adds it to `computed` and it can't be the same name in both, so how on earth is this supposed to work?

**Comment by meibegger** [comment]
Just use https://github.com/ktsn/vuex-class

**Comment by IvanKushchenko** [comment]
mapState && mapGetter decorator for pinia.

`
import { createDecorator } from 'vue-class-component';
import useStoreDocuments from '@js/stores/documents';

function Getter (useStore, key?) {
  return createDecorator((options, prop) => {
    if (!options.computed) options.computed = {};
    key = key || prop;
    options.computed[key] = function () { return useStore(this.$pinia)[key] };
  })
}

@Component
export default class Index extends Vue {
  @Getter(useStoreDocuments) documents
  @Getter(useStoreDocuments, 'doc') mainDocument
}
`
