### ISSUE TITLE
[vue3] Component is missing template or render function. 

### ISSUE THREAD

**Issue by kongxiaojian123** [vuejs/vue-class-component#572]
### vue version: 3.2.20

This framework is not available in Vue 3.2.20

**Comment by calebeaires** [comment]
I got stuck on this problem too. Is there some workaround?

Ps. Vue Class Component is os useful and good coding style, but its community seams self motivated to improve it.

**Comment by borkeszmate** [comment]
@calebeaires  Have you tried fixing `@vitejs/plugin-vue` to `1.8.0`? It should temporaty fix the bug. The above mentioned PR is partly accepted, so that I hope it can be merged in the close future. After that the issue should be fixed.

**Comment by calebeaires** [comment]
@borkeszmate... I am following that PR. Happy to see things going on...

**Comment by turbobuilt** [comment]
U guys are amazing... thanks so much for saving me with the 1.8.0 workaround.  Have a lot of stuff I need to get done, wasted enough time dinking around with it as I try to get a new device set up!

**Comment by borkeszmate** [comment]
@turbobuilt the PR fixing the bug was merged this week. Next vitejs/plugin-vue release should not have issue with class components. :) https://github.com/vitejs/vite/pull/5374
