### ISSUE TITLE
Public static class properties/methods

### ISSUE THREAD

**Issue by dmitrykurmanov** [vuejs/vue-class-component#58]
Hello! Thank you for your job. Is it possible to use typescript static properties? For example getter/setter: 

`public static get StaticProp()`

I've tried it, but after decoration I've lost static props.

**Comment by HerringtonDarkholme** [comment]
This is because vue-class-component is just a syntactic sugar of vue.
Your class after decoration is basically the same as:

```ts
var Class = Vue.extend({
  // definition
})
```

So your static properties are lost.

**Comment by dmitrykurmanov** [comment]
@HerringtonDarkholme , thank you for quick answer. So in vue we don't have something like react **tsx** files, when we can create full ts class like:

`export class MyComponent extends React.Component<any, any> ...` 

And we just have Vue Component with type cheking for ts compiler. Am I right?

**Comment by HerringtonDarkholme** [comment]
That's almost true. vue-class-component is just an API wrapper for Vue, providing type checking mechanism and class style feeling for users.

**Comment by dmitrykurmanov** [comment]
@HerringtonDarkholme , ok it is clear now. Thank you.

**Comment by kamlesh-ganar** [comment]
sdfdf
