### ISSUE TITLE
Could you edit this library to make room for a new feature on vue-property-decorator?

### ISSUE THREAD

**Issue by Evertt** [vuejs/vue-class-component#60]
Basically all the info you need to understand what I mean can be found in [this issue](https://github.com/kaorun343/vue-property-decorator/issues/5).

**Comment by Evertt** [comment]
Or could anyone point me in the right direction of how I can update the code myself? Basically I need to edit the `Object.getOwnPropertyNames()` method inside the `componentFactory` to filter out properties decorated with `@prop`. I just have no idea how to do that. I do know it's possible, since other vue-typescript libraries have been able to do it.

**Comment by ktsn** [comment]
In vue-class-component, it collects all class properties in [data.ts](https://github.com/vuejs/vue-class-component/blob/master/src/data.ts#L18) by instantiate decorated class.

We may need to implement two things:

1. Add interface to hook a initial data in `createDecorator` function.
2. Exclude the property key if the decorator is specified the hook.

So, `createDecorator` would look like:

```js
const Prop = createDecorator((options, key) => {
  // ...
}, {
  hookInitialProperty: (options, key, initialValue) => {
    // ...
  }
})
```

**Comment by ktsn** [comment]
@Evertt 
I've implement this feature via #62, but it seems that more discussion is needed as the feature introduce more complexity in vue-class-component. My concern is the feature may not have so much benefit while it introduce much complexity as the original use case can be achievable decorator factory.
I would be appreciated if you comment what you think :slightly_smiling_face:

**Comment by ktsn** [comment]
See https://github.com/vuejs/vue-class-component/pull/62#issuecomment-278047994
