### ISSUE TITLE
Vue 3 + Typescript + Vue Class component + Extending Vue = Uncaught TypeError: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by xEsk** [vuejs/vue-class-component#602]
### Version
3.2.31

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-im6fug?file=package.json&terminal=dev)

### Steps to reproduce
Just run the repo in **dev** mode.

### Steps which I used

1. Create a new project, using Vite or Webpack (this is not important).
2. Configure the project to use Typescript + Vue Class components
3. Create a class name "View" for example, which extends "Vue" (from 'vue-class-component')
4. Then the App class, instead of extending from Vue change it to View

### What is expected?
A console message saying "Hell-o" and the default Vue welcome screen.

### What is actually happening?
Throws an exception:

Uncaught TypeError: Class extends value #\<Object\> is not a constructor or null

---
When you build the project, the **dist** version works like expected (with no errors) and displaying the console message, it only fails on dev mode.

I used this in previous projects, and now it is not working anymore...

**Comment by xjrcode** [comment]
If you are never going to instantiate the `View.vue` class then you can convert it to a normal `View.ts` class and then import it as usual:

<img width="2286" alt="image" src="https://user-images.githubusercontent.com/3817677/159520067-a6b94e07-07fd-4898-b6e0-bc4d4f82f2e8.png">

**Comment by xEsk** [comment]
@xjrcode It works now, thank you.

**Comment by kpturner** [comment]
What if the vue component you are extending contains an HTML template and some CSS. How can that become a .ts file instead?

**Comment by nseb** [comment]
Any body , has a solution ?
