### ISSUE TITLE
how to use this with vue-router

### ISSUE THREAD

**Issue by MoonBottle** [vuejs/vue-class-component#64]
i use this with vue-router, then ... 
Module build failed: Error: Could not find file: 'E:\testproject\src\pages\act\App.vue'

**Comment by ktsn** [comment]
This seems not related to vue-class-component and vue-router...
Please use [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask usage/support questions.
Thanks.
