### ISSUE TITLE
Problem using CSS Modules

### ISSUE THREAD

**Issue by chanon** [vuejs/vue-class-component#66]
Using vue-class-component, I can not reference CSS Module css class name using `$style.className` in the template.

See reproduction:
https://github.com/chanon/ts-vue-hmr/blob/master/src/components/Hello.vue#L13

It creates a runtime error in the browser:
![image](https://cloud.githubusercontent.com/assets/357737/23093711/4accacea-f61d-11e6-9508-c556a04c9a10.png)

I tried to create property / data declaration of $style but I could not get it to work.

**Comment by chanon** [comment]
For reference av-ts does not have this problem.

**Comment by ktsn** [comment]
Move to vuejs/vue#4976

**Comment by snaptopixel** [comment]
Hey @chanon looks like the team is working on this but I had the same issue you mentioned elsewhere. I show a workaround here: https://github.com/vuejs/vue-loader/issues/540

**Comment by Astray-git** [comment]
```
mounted() { console.log(this.$style) }
```
As the original issue is fixed. I still get error `Property '$style' does not exist on type MyComponent` with vue-class-component@7.0.2.
