### ISSUE TITLE
[Question] Same component same instance :S

### ISSUE THREAD

**Issue by CKGrafico** [vuejs/vue-class-component#77]
Probably we are doing something wrong but when we use the same component multiple times, sames that vue is using the same instances:

```
@Component({
    template: require('./menu.component.html'),
})
export class Bymenu extends Vue {
    public email: string = '';
    private userService: UserService;

    created(UserService) {
        this.userService = UserService;
    }

    mounted() {
        this.email = (this.userService.get()).email;
    }
}
```

parent:
```
<div class="by-app-wrapper">
    <bymenu></bymenu>
    <bymenu></bymenu>
</div>
```

console:
![image](http://i.imgur.com/JrH6WXb.png)

Problem?
Both times is executing mounted method but only the first is updating the email value:
![image](http://i.imgur.com/Rik5nCP.png)

**Comment by ktsn** [comment]
Sorry, can't reproduce. Please make sure to follow [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide minimal reproduction.

**Comment by CKGrafico** [comment]
Preparing an example for you seems that the problem is not yours sorry for wasting your time xD
![Image](http://i.imgur.com/XM6ACAu.png)

tested also with vue router and can't reproduce, I'm pretty sure that the problem is to use browserify instead of webpack to bundle our src.

I'm going to close this and try to add more info if I find a solution (to help others)

Thank you
