### ISSUE TITLE
extends option in vue-class-component

### ISSUE THREAD

**Issue by linhhd278** [vuejs/vue-class-component#80]
hi all,
I tried using extends option in vue-class-component 

```
// file test.vue
<template>
  <div>display data tin extend {{msg}}</div>
</template>

<script>
var Child = {
  data: function(){
      return {
          msg: "Child component"
      }
  }
}
@Component({
  props: {
    extends : Child
  }
})
export default class MyComponent extends Vue {
}
</script>
```

Question:  I didn't see that it work , how to using https://vuejs.org/v2/api/#extends option in vue-class-component.

**Comment by HerringtonDarkholme** [comment]
```ts
var Child = Vue.extend({
  data: function(){
      return {
          msg: "Child component"
      }
  }
})

@Component()
export default class MyComponent extends Child {
}
```

**Comment by linhhd278** [comment]
```
@Component()
export default class MyComponent extends Child {
}
```
@HerringtonDarkholme : it seem is inheritance of ES6 class, not extends option of Vue. 
Is that equal function ?

**Comment by HerringtonDarkholme** [comment]
It should be equal. 
https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L67-L70

**Comment by ktsn** [comment]
As @HerringtonDarkholme described, you need to use `extends` keyword of ES Class.
