### ISSUE TITLE
Create decorators for directives not working

### ISSUE THREAD

**Issue by nqthiep** [vuejs/vue-class-component#82]
Hi all,
I tried to create decorator for directives as following:

 ```
 export function Directive(path, hook, options = {}) {
    const { deep = false, immediate = false } = options

    return createDecorator((componentOptions, handler) => {
      if (typeof componentOptions.directives !== 'object') {
        componentOptions.directives = Object.create(null)
      }
      componentOptions.directives[path] = {[hook]:{ handler, deep, immediate }}
      console.log('DIREC-DECO: path', path)
      console.log('DIREC-DECO: hook', hook)
      console.log('DIREC-DECO: ', componentOptions)
    })
  }

....

@Directive('focus', 'inserted')
    focusInserted(el){
      el.focus()
    }
```

And when used that decorator as following:

```
<input v-focus>
```

But I got an error:

> Uncaught TypeError: fn is not a function
>     at callHook$1 (eval at <anonymous> (app.js:741), <anonymous>:5234:5)
>     at callInsert (eval at <anonymous> (app.js:741), <anonymous>:5177:9)
>     at wrappedHook (eval at <anonymous> (app.js:741), <anonymous>:1709:10)
>     at Object.invoker [as insert] (eval at <anonymous> (app.js:741), <anonymous>:1656:16)
>     at invokeInsertHook (eval at <anonymous> (app.js:741), <anonymous>:4960:28)
>     at Vue$3.patch [as __patch__] (eval at <anonymous> (app.js:741), <anonymous>:5124:5)
>     at Vue$3.Vue._update (eval at <anonymous> (app.js:741), <anonymous>:2035:19)
>     at Vue$3.updateComponent (eval at <anonymous> (app.js:741), <anonymous>:2158:10)
>     at Watcher.get (eval at <anonymous> (app.js:741), <anonymous>:2469:25)
>     at new Watcher (eval at <anonymous> (app.js:741), <anonymous>:2452:12)

I don't understanding the cause of this error, Please help me for solve this issue.

**Comment by ktsn** [comment]
The 2nd argument of the callback of `createDecorator` is **key** of the decorated propety/method rather than value. You need to rewrite it like below:

```js
//...
return createDecorator((componentOptions, key) => {
  const handler = componentOptions.methods[key]
  // ...
})
```

**Comment by nqthiep** [comment]
@ktsn Thank you so much :+1:
