### ISSUE TITLE
TypeScript error: has no default export.

### ISSUE THREAD

**Issue by CatsMiaow** [vuejs/vue-class-component#85]
#### Error: vscode editor error
![20170413_160109](https://cloud.githubusercontent.com/assets/1300172/24995555/314afc82-206a-11e7-9696-72a773f7bcf9.png)

#### Error: webpack2 build, using `awesome-typescript-loader`
![20170413_155736](https://cloud.githubusercontent.com/assets/1300172/24995556/352d9292-206a-11e7-8c55-83e114d4baa4.png)

#### Cause
Vue is no default export
https://github.com/vuejs/vue/blob/dev/types/index.d.ts#L37
```js
import Vue from 'vue';
```

#### Fixed
```js
import * as Vue from 'vue'; // Vue, Vue.ComponentOptions...
```

End?

**Comment by ktsn** [comment]
Enable `allowSyntheticDefaultImports` 
https://vuejs.org/v2/guide/typescript.html
https://github.com/vuejs/vue-class-component#usage

**Comment by HerringtonDarkholme** [comment]
https://vuejs.org/v2/guide/typescript.html#Recommended-Configuration

Note the allowSyntheticDefaultImports option allows us to use the following:

        `import Vue from 'vue'`

instead of:

       ` import Vue = require('vue')`

**Comment by donbabbeo** [comment]
@CatsMiaow 
If you want to use 

`import Vue from "vue";`

you should add 
`"allowSyntheticDefaultImports": true,`
to compilerOptions on tsconfig.json
