### ISSUE TITLE
how to use it with vue-loader

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue-class-component#9]
use vue-loader to manage dependency, can I use the es6 class?

**Comment by yyx990803** [comment]
It should work, just export the class.

**Comment by Jokcy** [comment]
This is my code:
```
<template>
  <div class="component">{{ message }}</div>
</template>

<script>
import VueComponent from 'vue-class-component';


function test(a, b, c) {
  console.log('a:', a);
  console.log('b:', b);
  console.log('c:', c);
}

@VueComponent
export default class Component{
  data () {
    return {
      message: 'This is a component'
    }
  }
}

export default Component;
</script>

<style>
  .component{
    color: red;
  }
</style>
```
and this error comes to me:
```
Uncaught TypeError: Cannot set property 'template' of undefined
```

**Comment by michaelkrupp** [comment]
@Jokcy I ran into the same problem. Try replacing `@VueComponent` with `@VueComponent({})`

**Comment by ktsn** [comment]
This works on current version of vue (2.0.5), vue-class-component (4.2.0) and vue-loader (9.8.1). Maybe it has been fixed until now (I have a memory to see such fix on vue-loader). So closing.

@Jokcy If your problem is persist, feel free to reopen this issue 🙂
