### ISSUE TITLE
Passing argument to parent constructor does not work

### ISSUE THREAD

**Issue by vishr** [vuejs/vue-class-component#92]
I just extended your example to reproduce this issue, here is the link https://jsfiddle.net/Lwfy5w24

I am not able to pass properties to the parent class, do you think I am missing something?

**Comment by HerringtonDarkholme** [comment]
No, you cannot pass argument to constructor. 

As a rule of thumb, vue-class-component is just a syntax sugar over `Vue.extend`.

`constructor` is preserved for Vue internal.

You can alternatively use `props` and `created` to mock constructor.

**Comment by vishr** [comment]
> You can alternatively use props and created to mock constructor.

Thanks for your prompt response. Do you have any sample code to get an idea?

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vue-class-component/tree/master/example
