### ISSUE TITLE
Is there a way to call parent class method with super?

### ISSUE THREAD

**Issue by vishr** [vuejs/vue-class-component#93]
I want to explicitly make a call to a parent class method from a local method but `super.baseMethod()` call fails with the following error

```sh
Uncaught TypeError: Cannot read property 'call' of undefined
```

**Comment by ktsn** [comment]
Currently, we can't access super method like that because Vue's constructor does not have their method in prototype.
You need to use options object in the constructor object.
https://jsfiddle.net/ktsn/p6q9a14h/1/

**Comment by vishr** [comment]
@ktsn Thanks for the explanation, feel free to close it.

**Comment by lusess123** [comment]
It's unreasonable. There should be a better way.

**Comment by grreeenn** [comment]
Hi @ktsn, thanks for the explanation. 2 things: 
1. For some reason when I do it exactly as in your fiddle (calling the Parent function with `Child.options.methods.print.call(this)`) I get an endless recursion; although if I call `Parent.options.methods.print.call(this)` everything works as intended.
2. On this very row I get a typescript warning "TS2339: Property 'options' does not exist on type 'typeof ParentClass'". Regardlessly, the code compiles and works; but nevertheless, it's annoying - do you have an idea of how to avoid it?

**Comment by atorscho** [comment]
@grreeenn 
1. Same thing for me. Use must specify the parent class since that it's its method you want to use.
2. Try to put `// @ts-ignore` above the line with TS error.

**Comment by viT-1** [comment]
Some jest test:
```
	it('inheritance is ok', () => {
		expect.assertions(1);

		@Component
		class BaseC extends Vue {
			constructor() {
				super();
				this.text = 'Hello';
			}

			protected text: string;

			getHello(): string {
				return this.text;
			}

			get hello(): string {
				return this.getHello();
			}
		}

		@Component
		class ChildW extends BaseC {
			getHello(): string {
				return `${super.getHello()} World!`;
			}
		}

		const obj = new ChildW();

		expect(obj.hello).toBe('Hello World!');
	});
```
failed with `TypeError: Cannot read property 'call' of undefined` on `${super.getHello()} World!`

If i remove extending Vue from base class & remove @Component decorator test is success.

**Comment by viT-1** [comment]
Workaround:
```
it('inheritance is ok 2', () => {
		expect.assertions(1);

		@Component
		class BaseC extends Vue {
			constructor() {
				super();
				this.text = 'Hello';
			}

			protected text: string;

			getHello(): string {
				return this.text;
			}

			get hello(): string {
				return this.getHello();
			}
		}

		@Component
		class ChildW extends BaseC {
			get hello(): string {
				return `${this.getHello()} World!`;
			}
		}

		const obj = new ChildW();

		expect(obj.hello).toBe('Hello World!');
	});
```

**Comment by WuYuntaoTheGreat** [comment]
I checked the console.log, it turns out
@Component turns your class to a **VueComponent**.
That means, at runtime, your **this** is not a **ChildW** instance at all!
Your **this** is a **VueComponent** instance, with all the variables, methods, etc., you defined in **ChildW** (also, everything inherited from **BaseC**) ```mixin``` into that VueComponent instance. Unfortunately, the super methods are lost in that process.

There is no way to solve that, you have to use another name.
