### ISSUE TITLE
add example of $ref casting to any in documentation

### ISSUE THREAD

**Issue by jraller** [vuejs/vue-class-component#94]
If using `ref` on an element in a template and expecting to reference it with `this.$ref` one needs to change it to the proper element type or to `any` in order to access properties of the referred element `(this.$refs.checkboxElement as HTMLFormElement).checked`. The error `error TS2339: Property 'checked' does not exist on type 'Vue | Element | Vue[] | Element[]'` will be encountered otherwise.

**Comment by kaorun343** [comment]
Please see here.

https://github.com/vuejs/vue/blob/dev/types/test/vue-test.ts#L19

```typescript
class YourComponent extends Vue {
  $refs: {
    checkboxElement: HTMLFormElement
  }

  someMethod () {
    this.$refs.checkboxElement.checked
  }
}
```

**Comment by ktsn** [comment]
PR welcome 🙂

**Comment by grzegorztomasiak** [comment]
Anyone has idea why overriding $refs throws such a crazy errors in TypeScript when compiling the project?

```
ERROR in /var/www/local.studio/app/Resources/public/app/Common/Components/Sortable/Sortable.Component.vue.ts
(12,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type '<V extends VueClass>(target: V) => V' is not assignable to type 'typeof Sortable'.
    Property 'config' is missing in type '<V extends VueClass>(target: V) => V'.

```
```
ERROR in /var/www/local.studio/app/Resources/public/app/Common/Components/Sortable/Sortable.Component.vue.ts
(13,22): error TS2415: Class 'Sortable' incorrectly extends base class 'Vue'.
  Property '$refs' is private in type 'Sortable' but not in type 'Vue'.
```

Here's my component:
```
<template>
    <ul ref="ul">
        <li v-for="item in items">{{ item.name }}</li>
    </ul>
</template>
```

```
<script lang="ts">
    import Vue from 'vue';
    import {Component, Prop} from 'vue-property-decorator';
    import * as SortableJs from 'sortablejs/Sortable.js'

    @Component
    export default class Sortable extends Vue
    {
        @Prop({'default': null})
        public items:Array<Object>;

        public $refs = {
            ul: HTMLElement
        };

        public mounted()
        {
            //let el = document.getElementsByTagName('ul');
            console.log(this.$refs.ul)
            /*SortableJs.create(el, {
                animation: 150,
                onEnd: function (event) {
                    console.log(event.oldIndex);
                    console.log(event.newIndex);
                }
            });*/

            /*this.items = [
                {name:"John"},
                {name:"Joao"},
                {name:"Jean"}
            ];*/
        }
    }
</script>
```

**Comment by 304NotModified** [comment]
FYI, this is also an option:

```
 (this.$refs["checkboxElement"] as HTMLElement).checked
```

**Comment by wonderful-panda** [comment]
@grzegorztomasiak

```
public $refs = {
    ul: HTMLElement
};
```

Probably, this must be

```
public $refs: {
    ul: HTMLElement
};
```

Use `$refs:` instead of `$refs =`.

**Comment by qm3ster** [comment]
Is there a way to extend the original definition of $refs instead of overwriting it?

**Comment by zhangbobell** [comment]
Thanks @qm3ster, I'm facing the same problem. besides this, I have to augment the module declarations import from npm packages. On the other hand, @304NotModified's code will works when there is no  augmentation. 

Thank you all.

**Comment by samiconductor** [comment]
For some reason, my component import resolves to type Vue like @ktsn [expected here](https://github.com/vuejs/vue-class-component/pull/160#discussion_r144302690). Perhaps it's because I split up my Vue files into [separate html/ts/scss](https://github.com/vuejs/vueify/issues/35#issuecomment-161436380)?

To get around this, I had my component implement an interface with whatever methods I wanted to call elsewhere and used a union type for the ref. It's verbose but it works.

```ts
export default interface MyMethods {
  method(): void
}
```

```ts
import Vue from 'vue'
import Component from 'vue-class-component'
import MyMethods from './MyMethods'

@Component
export default class MyMethodsComponent extends Vue implements MyMethods {
  method() {
    console.log('method called')
  }
}
```

```ts
import Vue from 'vue'
import Component from 'vue-class-component'
import MyMethodsComponent from './MyMethodsComponent.vue'
import MyMethods from './MyMethods'

@Component({
  components: {
    MyMethodsComponent
  }
})
export default class MyComponent extends Vue {
  $refs: {
    myMethods: MyMethodsComponent & MyMethods
  }

  mounted() {
    this.$refs.myMethods.method()
  }
}
```

**Comment by lisztj** [comment]
$refs: {
    validate: HTMLFormElement
  }

**Comment by ffxsam** [comment]
Nope.

**Comment by ffxsam** [comment]
Got it. This is the new format:

```ts
export default class HelloWorld extends Vue {
  $refs!: {
    test: MyComponent
  }
}
```

**Comment by qm3ster** [comment]
@ffxsam Perhaps then:
```ts
export default class HelloWorld extends Vue {
  $refs!: Vue["$refs"] & {
    test: MyComponent
  }
}
```

**Comment by navmed** [comment]
None of these worked for me. I ended up using a different approach:

````
const password = this.$refs.password as HTMLElement;
password.focus();
````

**Comment by ffxsam** [comment]
I stopped using class style, not a fan. I'm using TypeScript with the "traditional" functional approach, and it works perfectly.

@navmed You might need to use `HTMLInputElement` to be more specific and gain access to properties/methods that only exist on inputs.

**Comment by 304NotModified** [comment]
offtopic, but IMO the TS class style it fabulous! Makes me really happy. Decorators, subclassing, better auto completion, less conflicts when make a method watched (from non-watched) - same for computed.. etc..etc..

**Comment by baixiaoji** [comment]
> ```
> public $refs = {
>     ul: HTMLElement
> };
> ```
> Probably, this must be
> 
> ```
> public $refs: {
>     ul: HTMLElement
> };
> ```
> Use `$refs:` instead of `$refs =`.

Thx for you guide，but I have some pulzze about why use `:` instead of `=`?

**Comment by baixiaoji** [comment]
> Because, it's of type HTMLElement. In typescript this usage of colon, means you're specifying the type.

Thx

**Comment by qm3ster** [comment]
@navmed what didn't work for you in my example?

**Comment by qm3ster** [comment]
@LissetteIbnz why is that better than my solution that doesn't do any `as` casts?

**Comment by ffxsam** [comment]
@LissetteIbnz Yeah, that's actually what I'm doing now and it works great. 😄

**Comment by phshy0607** [comment]
@304NotModified I really like this approach! Thank you!

**Comment by ajmontoya516** [comment]
> @ffxsam Perhaps then:
> 
> ```ts
> export default class HelloWorld extends Vue {
>   $refs!: Vue["$refs"] & {
>     test: MyComponent
>   }
> }
> ```

Works perfectly! I ended up making a type out of it.
```ts
type Refs<T extends object> = Vue['$refs'] & T;

export default class HelloWorld extends Vue {
  $refs!: Refs<{
    test: MyComponent
  }>
}
```

**Comment by flyinhigh** [comment]
![image](https://user-images.githubusercontent.com/681094/55273534-bea6f500-5307-11e9-83cb-d02bdef897fc.png)

**Comment by skyrpex** [comment]
@flyinhigh looks like eslint isn't able to parse typescript. You may check out https://github.com/typescript-eslint/typescript-eslint

**Comment by grreeenn** [comment]
> For some reason, my component import resolves to type Vue like @ktsn [expected here](https://github.com/vuejs/vue-class-component/pull/160#discussion_r144302690). Perhaps it's because I split up my Vue files into [separate html/ts/scss](https://github.com/vuejs/vueify/issues/35#issuecomment-161436380)?
> 
> To get around this, I had my component implement an interface with whatever methods I wanted to call elsewhere and used a union type for the ref. It's verbose but it works.

I split ts/html/css too and experience the same issue. I'm wondering if there's a less verbose and more straightforward way to do this... I have it literally like that:
```
const childRef: ChildComponent = this.$refs.childRef as ChildComponent;
(<ChildComponent>childRef).childMethod();
```
and still get "TS2339: Property 'scrollToElement' does not exist on type 'Vue'." error on the childMethod call; the interesting thing as, though, that this code compiles (even builds with --prod flag) without a warning and works perfectly. Is there any relevant issue or discussion about this behavior? Couldn't find it on Google :(

**Comment by vintprox** [comment]
> ```js
> import Vue, { VueConstructor } from 'vue';
> 
> export default (Vue as VueConstructor<Vue &
>   { $refs: 
>     { ul: HTMLElement },
>   }
> >).extend
> ```

Oh yes, @LissetteIbnz has just found solution for those who don't comprehend class-component. Seems like the only convenient way of defining types on $refs. It's a pity that syntax is getting bonkers fast with this, but still better than casting to HTMLElement every time I address field I just want to `.focus`...

**Comment by ktmouk** [comment]
It can write concisely using interface or type 

```js
interface $refs {
  ul: HTMLElement
}

export default (Vue as VueConstructor<Vue & { $refs: $refs }>).extend({
 ...
}
```

**Comment by vintprox** [comment]
> It can be written more readable using the interface
> 
> ```js
> interface $refs {
>   ul: HTMLElement
> }
> 
> export default (Vue as VueConstructor<Vue & { $refs: $refs }>).extend({
>  ...
> }
> ```

Nice, you even can:
```javascript
type VueExtended = Vue & {
  $refs: {
    el: HTMLElement
  }
}

export default (Vue as VueConstructor<VueExtended>).extend({
  ...
}
```

**Comment by tbrand-aa** [comment]
This definitely works fine to cast the $refs, but now my methods aren't 'recognised' in my editor. The compiler still runs fine and without errors, but my editor (VS Code and WebStorm) don't like this. As soon as I use `(Vue as ....).extend` instead of `Vue.extend` it stops resolving.
Any idea how to fix this?

**Comment by jacobg213** [comment]
To anyone still having an issue with either the `$refs` property or the `@Ref()` decorator type not being resolved correctly in one of JetBrains' IDEs - be sure to check out https://youtrack.jetbrains.com/issue/WEB-36966 and bump it up if you can so we can get it fixed. :)

**Comment by andrewvasilchuk** [comment]
Check out  [vue-typed-refs](https://github.com/bluecanvas/vue-typed-refs) library. The library provides a convenient way for `$refs` typing.

**Comment by vincerubinetti** [comment]
What is the modern -- Vue v3 and `defineComponent` and functional components (as opposed to class components) -- way to do this. Specifically, how could do I access a child component's method through refs, as [shown here in the docs](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements).

Here's my simplified example:

```HTML
<template>
<SomeComponent ref="someComponent" />
</template>

<script lang="ts">
...
export default defineComponent({
  mounted: function () {
    this.$refs.someComponent.childMethod();
  }
});
</script>
```

Casting the `someComponent` ref to `any` throws a linter warning, so this does not feel like the right answer. Also I cannot cast it to `HTMLElement` (which is what the component is under the hood), because the `HTMLElement` type does not have my custom `childMethod` on the component.
