### ISSUE TITLE
How to annotate Vuex store type?

### ISSUE THREAD

**Issue by spiffytech** [vuejs/vue-class-component#97]
How can I annotate my component to declare the type of my Store, such that my component doesn't give `this.$store` the type `Vue.$store: Store<any>`?

**Comment by ktsn** [comment]
If you import `vuex` it is automatically declared in Vue constructor.
https://github.com/vuejs/vuex/blob/dev/types/vue.d.ts

**Comment by IlyaSemenov** [comment]
https://github.com/vuejs/vuex/blob/dev/types/vue.d.ts lists `$store` as `Store<any>` and the question was how to annotate it to be `Store<MyState>`.

**Comment by eljenso** [comment]
Anyone found a solution for this?
It would be great to fully type the store and then have auto-completion for `this.$store` (e.g. for `this.$store.getters`). Currently `this.$store.getters` has type `any`, which is not ideal.

**Comment by Niedzwiedzw** [comment]
solution is still needed...
