### ISSUE TITLE
Where to put complex object that don't need to be reactive?

### ISSUE THREAD

**Issue by chenzhutian** [vuejs/vue-class-component#99]
I have a complex object which does not need to be reactive.
When working in Vue single file component, I can directly store and consume it in a component like this:
```js
// app.js
export default { 
    complexObject: new ComplexObject();
    data(){
         return {
              simpleObject: {}
         }
    },
    methods:{
        foo() {
            console.log(this.complexObject); 
       }
    }
}
```

However, when using `vue-class-component`, all the members defined in a class will be pass to `data` option and make this complexObject reactive:
```ts
// app.ts
@Component
export default class App extends Vue {
    public complexObject = new ComplexObject();
}
```

My question is where should I put the `complexObject` to achieve the same goal as in vue single file component?

**Comment by ktsn** [comment]
Just as same as when we use pure Vue API, declare it in lifecycle hook in that case.

```js
@Component
class App extends Vue {
  created () {
    this.complexObject = new ComplexObject()
  }
}
```

**Comment by chenzhutian** [comment]
But the typescript will raise an error that `[ts] Property 'complexObject' does not exist on type ...` if we declare the complex object like this.

```ts
@Component
class App extends Vue {
  created () {
    this.complexObject = new ComplexObject()
  }
}
```

**Comment by ktsn** [comment]
So, you should declare the property type.

```ts
@Component
class App extends Vue {
  complexObject: ComplexObject

  created () {
    this.complexObject = new ComplexObject()
  }
}
```

**Comment by chenzhutian** [comment]
I think I should assign the `complexObject` with `undefined` as an initial value to avoid reactively.
Thanks very much.

**Comment by andre-dw** [comment]
I'm trying to understand Typescript and how to add a non reactive object to an Vue instance and using the latest vue-cli@3.0.0-beta.16.

```
<script lang="ts">
import User from '@/models/user';

@Component
export default class HelloWorld extends Vue {

  private user: User = new User();
  // This is a referenced type.
  // User 2 will automatically change when user1 is changed during input
  private user2 = this.user;
  // User 3 will not even be reactive because we set it to undefined
  private user3: undefined;

  private created() {
    // User 3 will not be reactive because it is only declared here
    this.user3 = new User();
  }

}
</script>
```
Where `User` is an class
```
class User {
  public firstName: string = '';
  public lastName: string = '';
}

export default User;
```
The error i get is `Type 'User' is not assignable to type 'undefined'.`
